var CARDS_HEADERS={Users:['UserID','Email','Name','Role','Status','CreatedAt','UpdatedAt','LastLoginAt'],Sessions:['SessionID','UserID','TokenHash','ExpiresAt','CreatedAt','RevokedAt','Status'],OTP:['OtpID','Email','Purpose','OtpHash','ExpiresAt','Attempts','MaxAttempts','CreatedAt','UsedAt','Status'],BankAccounts:['BankAccountID','UserID','BankName','AccountName','AccountType','AccountNumberMasked','IFSC','OpeningBalance','CurrentBalance','Currency','Status','CreatedAt','UpdatedAt'],BankTransactions:['TransactionID','UserID','BankAccountID','TxnDate','Description','Reference','Debit','Credit','Balance','Category','Status','CreatedAt'],DebitCards:['DebitCardID','UserID','BankAccountID','Issuer','CardName','Last4','Type','DailyLimit','MonthlyLimit','RewardProgram','AnnualFee','Status','ExpiryMonth','ExpiryYear','CreatedAt','UpdatedAt'],CreditCards:['CreditCardID','UserID','Issuer','CardName','Last4','Network','CreditLimit','AvailableLimit','StatementDate','DueDate','Outstanding','MinimumDue','AnnualFee','InterestRate','RewardProgram','RewardRate','Status','ExpiryMonth','ExpiryYear','CreatedAt','UpdatedAt'],FDBackedCards:['FDCardID','UserID','Issuer','CardName','Last4','FDID','FDEndDate','FDPrincipal','CreditLimit','AvailableLimit','InterestRate','AnnualFee','RewardProgram','Status','CreatedAt','UpdatedAt'],Purchases:['PurchaseID','UserID','PurchaseDate','CardType','CardID','Merchant','Category','Reference','Amount','RewardPoints','Cashback','Status','ReturnEligibleUntil','CreatedAt','UpdatedAt'],Returns:['ReturnID','UserID','PurchaseID','ReturnDate','Merchant','Amount','RefundMethod','RefundReference','Status','CreatedAt','UpdatedAt'],Rewards:['RewardID','UserID','CardType','CardID','Program','TxnDate','Reference','Points','Cashback','Value','ExpiryDate','Status','RedeemedAt','CreatedAt','UpdatedAt'],Investments:['InvestmentID','UserID','InvestmentType','Provider','Name','AccountReferenceMasked','PurchaseDate','Cost','CurrentValue','ReturnValue','ReturnPercent','MaturityDate','Status','CreatedAt','UpdatedAt'],FixedDeposits:['FDID','UserID','BankName','FDNumberMasked','StartDate','MaturityDate','Principal','InterestRate','MaturityValue','InterestEarned','LinkedCardID','Status','CreatedAt','UpdatedAt']};
function cardsSetup_(){var ss=cardsSpreadsheet_();Object.keys(CARDS_HEADERS).forEach(function(n){var s=ss.getSheetByName(n);if(!s)s=ss.insertSheet(n);var h=CARDS_HEADERS[n];if(s.getLastRow()===0)s.getRange(1,1,1,h.length).setValues([h]);});if(!cardsFind_('Users','Email',cardsAdminEmail_()))cardsAppend_('Users',{UserID:cardsId_('USR'),Email:cardsAdminEmail_(),Name:'Admin',Role:'ADMIN',Status:'ACTIVE',CreatedAt:cardsIso_(),UpdatedAt:cardsIso_(),LastLoginAt:''});return{message:'Trusted Circle Cards initialized.',spreadsheetId:ss.getId(),adminEmail:cardsAdminEmail_(),sheets:Object.keys(CARDS_HEADERS)};}
function cardsRows_(sheet){var sh=cardsSpreadsheet_().getSheetByName(sheet);cardsRequire_(sh,'Cards sheet not initialized: '+sheet);if(sh.getLastRow()<2)return[];var v=sh.getDataRange().getValues(),h=v.shift();return v.filter(function(r){return r.some(function(x){return x!=='';});}).map(function(r){var o={};h.forEach(function(k,i){o[k]=r[i]});return o});}
function cardsAppend_(sheet,obj){var sh=cardsSpreadsheet_().getSheetByName(sheet);cardsRequire_(sh,'Cards sheet not initialized: '+sheet);var h=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0];sh.appendRow(h.map(function(k){return obj[k]===undefined?'':obj[k]}));}
function cardsFind_(sheet,field,value){var rows=cardsRows_(sheet);for(var i=0;i<rows.length;i++)if(field==='Email'?cardsEmail_(rows[i][field])===cardsEmail_(value):String(rows[i][field])===String(value))return rows[i];return null;}
function cardsUpdate_(sheet,idField,id,patch){var tab=cardsSpreadsheet_().getSheetByName(sheet);cardsRequire_(tab,'Cards sheet not initialized: '+sheet);var data=tab.getDataRange().getValues(),h=data[0],idc=h.indexOf(idField);for(var r=1;r<data.length;r++)if(String(data[r][idc])===String(id)){Object.keys(patch).forEach(function(k){var c=h.indexOf(k);if(c>=0)tab.getRange(r+1,c+1).setValue(patch[k])});return true}return false;}

function runCardsSetup(){return cardsSetup_();}
function testCardsSetup(){var ss=cardsSpreadsheet_();return{ok:true,spreadsheetId:ss.getId(),adminEmail:cardsAdminEmail_(),sheets:Object.keys(CARDS_HEADERS)};}
