/** Trusted Circle Books - extended business, workflow, reporting and administration service. */
var TC_FULL_HEADERS={
OrganisationMembers:['MembershipID','OrganisationID','OrganisationCode','UserID','Email','Name','Role','Status','JoinedAt','ApprovedBy','ApprovedAt','RejectedBy','RejectedAt','Remarks','CreatedAt','UpdatedAt'],
JoinRequests:['JoinRequestID','OrganisationID','OrganisationCode','UserID','Email','Name','Status','RequestedAt','ReviewedBy','ReviewedAt','Remarks'],
Employees:['EmployeeID','OrganisationID','EmployeeCode','FirstName','LastName','Email','Mobile','DateOfBirth','Gender','EmergencyContact','Department','Designation','JoiningDate','EmploymentType','ReportingManagerID','Branch','Location','PAN','BankName','AccountNumberMasked','IFSC','UAN','PFApplicable','ESIApplicable','ProfessionalTaxApplicable','UserID','Status','CreatedAt','UpdatedAt'],
Roles:['RoleID','OrganisationID','Name','Permissions','Status','CreatedAt','UpdatedAt'],
Permissions:['PermissionID','Code','Name','Module','Description','Status','CreatedAt'],
Quotes:['QuoteID','OrganisationID','QuoteNumber','QuoteDate','ExpiryDate','CustomerID','Status','Subtotal','TaxAmount','Discount','Total','Notes','CreatedAt','UpdatedAt'],
SalesOrders:['SalesOrderID','OrganisationID','OrderNumber','OrderDate','ExpectedDate','CustomerID','Status','Subtotal','TaxAmount','Discount','Total','Notes','CreatedAt','UpdatedAt'],
CreditNotes:['CreditNoteID','OrganisationID','CreditNoteNumber','CreditNoteDate','CustomerID','InvoiceID','Status','Amount','Reason','CreatedAt','UpdatedAt'],
PurchaseOrders:['PurchaseOrderID','OrganisationID','OrderNumber','OrderDate','ExpectedDate','VendorID','Status','Subtotal','TaxAmount','Discount','Total','Notes','CreatedAt','UpdatedAt'],
VendorCredits:['VendorCreditID','OrganisationID','CreditNumber','CreditDate','VendorID','BillID','Status','Amount','Reason','CreatedAt','UpdatedAt'],
RecurringInvoices:['RecurringInvoiceID','OrganisationID','ProfileNumber','CustomerID','Frequency','NextDate','Status','Amount','CreatedAt','UpdatedAt'],
PriceLists:['PriceListID','OrganisationID','Name','Type','Currency','Status','CreatedAt','UpdatedAt'],
Projects:['ProjectID','OrganisationID','ProjectCode','Name','CustomerID','StartDate','EndDate','Status','Budget','CreatedAt','UpdatedAt'],
Expenses:['ExpenseID','OrganisationID','ExpenseNumber','ExpenseDate','AccountID','Payee','Amount','TaxAmount','Mode','Reference','JournalID','Status','CreatedAt'],
Notifications:['NotificationID','OrganisationID','UserID','Type','Title','Message','Status','CreatedAt','ReadAt'],
Approvals:['ApprovalID','OrganisationID','EntityType','EntityID','RequestedBy','ApproverID','Status','RequestedAt','ReviewedAt','Remarks'],
TDSRecords:['TDSID','OrganisationID','TxnDate','PartyType','PartyID','Section','BaseAmount','TDSRate','TDSAmount','Status','CreatedAt'],
FixedAssets:['AssetID','OrganisationID','AssetCode','Name','PurchaseDate','Cost','DepreciationMethod','UsefulLife','AccumulatedDepreciation','Status','CreatedAt','UpdatedAt'],
Budgets:['BudgetID','OrganisationID','FiscalYear','AccountID','Amount','Notes','Status','CreatedAt','UpdatedAt']
};
function tcFullEnsure_(){var ss=booksSpreadsheet_();Object.keys(TC_FULL_HEADERS).forEach(function(n){var s=ss.getSheetByName(n);if(!s)s=ss.insertSheet(n);var h=TC_FULL_HEADERS[n];if(s.getLastRow()===0)s.getRange(1,1,1,h.length).setValues([h]);});return ss;}
function tcFullOrg_(token){var u=booksAuth_(token);booksRequire_(u.OrganisationID,'Organisation setup is required.');return u.OrganisationID;}
function tcFullRows_(sheet,orgId){tcFullEnsure_();return booksRows_(sheet).filter(function(r){return !orgId||String(r.OrganisationID)===String(orgId);});}
function tcFullSave_(sheet,idField,obj){tcFullEnsure_();var id=obj[idField]||booksId_('ROW'),old=booksFind_(sheet,idField,id),now=booksIsoNow_();obj[idField]=id;if(!old){obj.CreatedAt=obj.CreatedAt||now;obj.UpdatedAt=now;booksAppend_(sheet,obj);}else{obj.UpdatedAt=now;booksUpdate_(sheet,idField,id,obj);}return booksFind_(sheet,idField,id)||obj;}
function tcFullCrud_(input,sheet,idField,requiredRole){var u=booksAuth_(input.token),org=tcFullOrg_(input.token);if(requiredRole)booksRequire_(String(requiredRole).split('|').indexOf(String(u.Role))>=0,'You do not have permission for this action.');var d=input.record||input.data||{};d.OrganisationID=org;var r=tcFullSave_(sheet,idField,d);tcAuditOrg_('SAVE_'+sheet,org,u.UserID,sheet,r[idField],{},true,'');return{record:r};}
function tcFullList_(input,sheet){var org=tcFullOrg_(input.token);return{rows:tcFullRows_(sheet,org)};}
function tcFullDelete_(input,sheet,idField){var u=booksAuth_(input.token),org=tcFullOrg_(input.token);booksRequire_(u.Role==='OWNER'||u.Role==='ADMIN','Only owner/admin can delete records.');var id=String(input[idField]||input.id||''),rows=tcFullRows_(sheet,org),found=rows.filter(function(r){return String(r[idField])===id;})[0];booksRequire_(found,'Record not found.');booksUpdate_(sheet,idField,id,{Status:'DELETED',UpdatedAt:booksIsoNow_()});return{deleted:true,id:id};}
function tcFullMemberships_(input){var u=booksAuth_(input.token);return{members:tcFilter_('OrganisationMembers',function(r){return String(r.OrganisationID)===String(u.OrganisationID);})};}
function tcFullJoinRequests_(input){var u=booksAuth_(input.token);tcRequireOrgAdmin_(u,u.OrganisationID);var status=String(input.status||'PENDING').toUpperCase();return{requests:tcFilter_('JoinRequests',function(r){return String(r.OrganisationID)===String(u.OrganisationID)&&String(r.Status).toUpperCase()===status;})};}
function tcFullUpdateMember_(input){var u=booksAuth_(input.token),org=tcFullOrg_(input.token);tcRequireOrgAdmin_(u,org);var id=String(input.membershipId||''),m=tcFind_('OrganisationMembers','MembershipID',id);booksRequire_(m&&String(m.OrganisationID)===String(org),'Membership not found.');var patch=input.patch||{};var allowed=['Role','Status','Remarks','Name'];Object.keys(patch).forEach(function(k){if(allowed.indexOf(k)<0)delete patch[k];});booksUpdate_('OrganisationMembers','MembershipID',id,patch);return{member:tcFind_('OrganisationMembers','MembershipID',id)};}
function tcFullDashboard_(input){var org=tcFullOrg_(input.token),inv=tcFullRows_('Invoices',org),bills=tcFullRows_('Bills',org),receipts=tcFullRows_('Receipts',org),payments=tcFullRows_('Payments',org),expenses=tcFullRows_('Expenses',org);var sum=function(a,k){return a.reduce(function(s,r){return s+Number(r[k]||0);},0)};var pl=booksProfitLoss_({token:input.token,fiscalYear:input.fiscalYear||booksFiscalYear_(Utilities.formatDate(new Date(),BOOKS_CONFIG.TIMEZONE,'yyyy-MM-dd'))});return{receivables:sum(inv,'BalanceDue'),payables:sum(bills,'BalanceDue'),cashReceived:sum(receipts,'Amount'),cashPaid:sum(payments,'Amount'),expenses:sum(expenses,'Amount'),income:pl.income||0,netProfit:pl.netProfit||0,invoiceCount:inv.length,billCount:bills.length};}
function tcFullAging_(input){var org=tcFullOrg_(input.token),today=new Date(),rows=tcFullRows_('Invoices',org).filter(function(r){return Number(r.BalanceDue||0)>0&&String(r.Status).toUpperCase()!=='CANCELLED';}).map(function(r){var due=new Date(r.DueDate||r.InvoiceDate),days=Math.max(0,Math.floor((today-due)/86400000)),bucket=days===0?'Current':days<=30?'1-30':days<=60?'31-60':days<=90?'61-90':'90+';return{invoiceId:r.InvoiceID,invoiceNumber:r.InvoiceNumber,customerId:r.CustomerID,dueDate:r.DueDate,balanceDue:Number(r.BalanceDue||0),daysOverdue:days,bucket:bucket};});return{rows:rows};}
function tcFullReport_(input){var org=tcFullOrg_(input.token),type=String(input.reportType||'dashboard'),fy=String(input.fiscalYear||booksFiscalYear_(Utilities.formatDate(new Date(),BOOKS_CONFIG.TIMEZONE,'yyyy-MM-dd')));if(type==='aging')return tcFullAging_(input);if(type==='dashboard')return tcFullDashboard_(input);if(type==='trial_balance')return booksTrialBalance_(input);if(type==='profit_loss')return booksProfitLoss_(input);if(type==='balance_sheet')return booksBalanceSheet_(input);var ranges=booksFiscalRange_(fy),journals=tcFullRows_('JournalEntries',org).filter(function(r){return String(r.JournalDate)>=ranges.from&&String(r.JournalDate)<=ranges.to;});return{reportType:type,fiscalYear:fy,rows:journals};}
function tcFullSearch_(input){var org=tcFullOrg_(input.token),q=String(input.q||'').toLowerCase(),sheets=['Customers','Vendors','Items','Invoices','Bills','Quotes','SalesOrders','PurchaseOrders','Projects','Employees'];var out=[];sheets.forEach(function(s){tcFullRows_(s,org).forEach(function(r){if(JSON.stringify(r).toLowerCase().indexOf(q)>=0)out.push({type:s,id:r[Object.keys(r)[0]],record:r});});});return{results:out.slice(0,100)};}
function tcFullRoute_(action,input){tcFullEnsure_();switch(action){case'booksDashboard':return tcFullDashboard_(input);case'booksSearch':return tcFullSearch_(input);case'booksAging':return tcFullAging_(input);case'booksListOrganisationMembers':return tcFullMemberships_(input);case'booksListJoinRequests':return tcFullJoinRequests_(input);case'booksUpdateOrganisationMember':return tcFullUpdateMember_(input);case'booksListEmployees':return tcFullList_(input,'Employees');case'booksSaveEmployee':return tcFullCrud_(input,'Employees','EmployeeID','OWNER|ADMIN');case'booksListCustomers':return tcFullList_(input,'Customers');case'booksSaveCustomer':return tcFullCrud_(input,'Customers','CustomerID','OWNER|ADMIN|ACCOUNTANT|SALES');case'booksListVendors':return tcFullList_(input,'Vendors');case'booksSaveVendor':return tcFullCrud_(input,'Vendors','VendorID','OWNER|ADMIN|ACCOUNTANT|PURCHASE');case'booksListItems':return tcFullList_(input,'Items');case'booksSaveItem':return tcFullCrud_(input,'Items','ItemID','OWNER|ADMIN|ACCOUNTANT|INVENTORY');case'booksListQuotes':return tcFullList_(input,'Quotes');case'booksSaveQuote':return tcFullCrud_(input,'Quotes','QuoteID','OWNER|ADMIN|SALES');case'booksListSalesOrders':return tcFullList_(input,'SalesOrders');case'booksSaveSalesOrder':return tcFullCrud_(input,'SalesOrders','SalesOrderID','OWNER|ADMIN|SALES');case'booksListPurchaseOrders':return tcFullList_(input,'PurchaseOrders');case'booksSavePurchaseOrder':return tcFullCrud_(input,'PurchaseOrders','PurchaseOrderID','OWNER|ADMIN|PURCHASE');case'booksListProjects':return tcFullList_(input,'Projects');case'booksSaveProject':return tcFullCrud_(input,'Projects','ProjectID','OWNER|ADMIN');case'booksListFixedAssets':return tcFullList_(input,'FixedAssets');case'booksSaveFixedAsset':return tcFullCrud_(input,'FixedAssets','AssetID','OWNER|ADMIN|ACCOUNTANT');case'booksListBudgets':return tcFullList_(input,'Budgets');case'booksSaveBudget':return tcFullCrud_(input,'Budgets','BudgetID','OWNER|ADMIN|ACCOUNTANT');case'booksListNotifications':return tcFullList_(input,'Notifications');case'booksListTDS':return tcFullList_(input,'TDSRecords');case'booksSaveTDS':return tcFullCrud_(input,'TDSRecords','TDSID','OWNER|ADMIN|ACCOUNTANT');case'booksListRoles':return tcFullList_(input,'Roles');case'booksSaveRole':return tcFullCrud_(input,'Roles','RoleID','OWNER|ADMIN');case'booksListPermissions':return{rows:tcRows_('Permissions')};case'booksDeleteRecord':return tcFullDelete_(input,String(input.sheet||''),String(input.idField||'ID'));default:return null;}}
var TC_BOOKS_ORIGINAL_ROUTE=booksRoute_;
booksRoute_=function(action,input){var extended=tcFullRoute_(action,input);return extended!==null?extended:TC_BOOKS_ORIGINAL_ROUTE(action,input);};
function runBooksFullSetup(){tcFullEnsure_();booksSetupProduction_();return 'Trusted Circle Books full modules initialized';}
