/** Trusted Circle Books - Organisation, membership and employee layer. */

var TC_BOOKS_ORG_HEADERS={
  Organisations:['OrganisationID','OrganisationCode','Name','LegalName','OrganisationType','BusinessDescription','Industry','Website','GSTIN','PAN','TAN','CIN','LLPIN','UDYAM','IEC','Email','Phone','AlternatePhone','ContactPerson','Address','Address2','City','District','State','Country','Pincode','BaseCurrency','BooksStartDate','FinancialYearStartMonth','GSTRegistered','GSTRegistrationType','GSTState','DefaultTaxTreatment','AccountingMethod','Status','CreatedAt','UpdatedAt'],
  Users:['UserID','OrganisationID','Email','Name','Role','Status','CreatedAt','UpdatedAt','LastLoginAt'],
  OrganisationMembers:['MembershipID','OrganisationID','UserID','Email','Name','Role','Status','JoinedAt','ApprovedBy','ApprovedAt','RejectedBy','RejectedAt','Remarks','CreatedAt','UpdatedAt'],
  JoinRequests:['JoinRequestID','OrganisationID','OrganisationCode','UserID','Email','Name','Status','RequestedAt','ReviewedBy','ReviewedAt','Remarks'],
  Roles:['RoleID','OrganisationID','Name','Permissions','Status','CreatedAt','UpdatedAt'],
  Permissions:['PermissionID','Code','Name','Module','Description','Status','CreatedAt'],
  Employees:['EmployeeID','OrganisationID','EmployeeCode','FirstName','LastName','Email','Mobile','DateOfBirth','Gender','EmergencyContact','Department','Designation','JoiningDate','EmploymentType','ReportingManagerID','Branch','Location','PAN','BankName','AccountNumberMasked','IFSC','UAN','PFApplicable','ESIApplicable','ProfessionalTaxApplicable','UserID','Status','CreatedAt','UpdatedAt']
};

function tcEnsureBooksOrgSheets_(){
  var ss=booksSpreadsheet_();
  Object.keys(TC_BOOKS_ORG_HEADERS).forEach(function(name){
    var sh=ss.getSheetByName(name);
    if(!sh)sh=ss.insertSheet(name);
    var headers=TC_BOOKS_ORG_HEADERS[name];
    if(sh.getLastRow()===0){sh.getRange(1,1,1,headers.length).setValues([headers]);return;}
    var existing=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0];
    var changed=false;
    headers.forEach(function(h){if(existing.indexOf(h)<0){existing.push(h);changed=true;}});
    if(changed)sh.getRange(1,1,1,existing.length).setValues([existing]);
  });
  return ss;
}
function tcRows_(name){tcEnsureBooksOrgSheets_();return booksRows_(name);}
function tcAppend_(name,obj){tcEnsureBooksOrgSheets_();booksAppend_(name,obj);}
function tcFind_(name,field,value){var rows=tcRows_(name);for(var i=0;i<rows.length;i++)if(String(rows[i][field]||'')===String(value||''))return rows[i];return null;}
function tcFilter_(name,pred){return tcRows_(name).filter(pred);}
function tcNow_(){return booksIsoNow_();}
function tcEmail_(v){return booksNormalizeEmail_(v);}
function tcMembership_(userId,orgId){var rows=tcFilter_('OrganisationMembers',function(r){return String(r.UserID)===String(userId)&&String(r.OrganisationID)===String(orgId)&&String(r.Status).toUpperCase()==='ACTIVE';});return rows[0]||null;}
function tcActiveMemberships_(userId){return tcFilter_('OrganisationMembers',function(r){return String(r.UserID)===String(userId)&&String(r.Status).toUpperCase()==='ACTIVE';});}
function tcUserMemberships_(userId){return tcFilter_('OrganisationMembers',function(r){return String(r.UserID)===String(userId);}).map(function(m){var o=tcFind_('Organisations','OrganisationID',m.OrganisationID);return{membershipId:m.MembershipID,organisationId:m.OrganisationID,organisationCode:m.OrganisationCode||o&&o.OrganisationCode||m.OrganisationID,name:o?o.Name:m.OrganisationID,role:m.Role,status:m.Status,joinedAt:m.JoinedAt,approvedAt:m.ApprovedAt};});}
function tcPublicUser_(u){var memberships=tcUserMemberships_(u.UserID),active=memberships.filter(function(m){return String(m.status).toUpperCase()==='ACTIVE';}),pending=memberships.filter(function(m){return String(m.status).toUpperCase()==='PENDING';});return{userId:u.UserID,organisationId:u.OrganisationID||'',email:u.Email,name:u.Name,role:u.Role,status:u.Status,organisationAccess:active.length?'ACTIVE':(pending.length?'PENDING':'NONE'),memberships:memberships,organisationMemberships:memberships};}

var TC_BOOKS_ORIGINAL_AUTH=booksAuth_;
booksAuth_=function(token){var u=TC_BOOKS_ORIGINAL_AUTH(token),hash=booksHash_(String(token||'')),sessions=tcRows_('Sessions');for(var i=sessions.length-1;i>=0;i--)if(String(sessions[i].TokenHash)===hash&&String(sessions[i].Status)==='ACTIVE'){if(sessions[i].OrganisationID)u.OrganisationID=sessions[i].OrganisationID;break;}return u;};
function tcCreateSession_(user,orgId){var token=Utilities.getUuid()+'.'+Utilities.getUuid(),expires=new Date(Date.now()+BOOKS_CONFIG.SESSION_TTL_SECONDS*1000);tcAppend_('Sessions',{SessionID:booksId_('SES'),UserID:user.UserID,OrganisationID:orgId||'',TokenHash:booksHash_(token),ExpiresAt:expires.toISOString(),CreatedAt:tcNow_(),RevokedAt:'',Status:'ACTIVE'});return{token:token,expiresAt:expires.toISOString()};}
function tcSelectDefaultOrg_(user){var active=tcActiveMemberships_(user.UserID);return active.length?active[0].OrganisationID:'';}

function tcBooksVerifyOtp_(input){tcEnsureBooksOrgSheets_();var email=tcEmail_(input.email),otp=String(input.otp||'').trim(),rows=booksRows_('OTP'),row=null;booksRequire_(email&&otp,'Email and OTP are required.');for(var i=rows.length-1;i>=0;i--)if(rows[i].Email===email&&rows[i].Purpose==='LOGIN'&&rows[i].Status==='ACTIVE'){row=rows[i];break;}booksRequire_(row,'OTP not found.');booksRequire_(new Date(row.ExpiresAt).getTime()>Date.now(),'OTP expired.');var attempts=Number(row.Attempts||0)+1;booksUpdate_('OTP','OtpID',row.OtpID,{Attempts:attempts});booksRequire_(attempts<=BOOKS_CONFIG.OTP_MAX_ATTEMPTS,'Too many OTP attempts.');booksRequire_(booksHash_(otp)===String(row.OtpHash),'Invalid OTP.');booksUpdate_('OTP','OtpID',row.OtpID,{Status:'USED',UsedAt:tcNow_()});var user=tcFind_('Users','Email',email);if(!user){user={UserID:booksId_('USR'),OrganisationID:'',Email:email,Name:email.split('@')[0],Role:'VIEWER',Status:'ACTIVE',CreatedAt:tcNow_(),UpdatedAt:tcNow_(),LastLoginAt:tcNow_()};tcAppend_('Users',user);}else booksUpdate_('Users','UserID',user.UserID,{LastLoginAt:tcNow_(),UpdatedAt:tcNow_()});user=tcFind_('Users','UserID',user.UserID);var orgId=tcSelectDefaultOrg_(user),session=tcCreateSession_(user,orgId);if(orgId)booksUpdate_('Users','UserID',user.UserID,{OrganisationID:orgId});user=tcFind_('Users','UserID',user.UserID);var memberships=tcUserMemberships_(user.UserID),access=memberships.some(function(m){return String(m.status).toUpperCase()==='ACTIVE';})?'ACTIVE':(memberships.some(function(m){return String(m.status).toUpperCase()==='PENDING';})?'PENDING':'NONE');return{user:tcPublicUser_(user),session:session,memberships:memberships,organisationAccess:access,requiresOrganisation:!orgId};}
function tcBooksMe_(input){var u=booksAuth_(input.token),memberships=tcUserMemberships_(u.UserID),active=memberships.filter(function(m){return String(m.status).toUpperCase()==='ACTIVE';});return{user:tcPublicUser_(u),memberships:memberships,organisationAccess:active.length?'ACTIVE':(memberships.some(function(m){return String(m.status).toUpperCase()==='PENDING';})?'PENDING':'NONE'),organisation:u.OrganisationID?tcFind_('Organisations','OrganisationID',u.OrganisationID):null};}

function tcCreateOrganisation_(input){var u=booksAuth_(input.token),d=input.organisation||{};booksRequire_(String(d.Name||'').trim(),'Organisation name is required.');booksRequire_(String(d.LegalName||'').trim(),'Legal name is required.');booksRequire_(String(d.PAN||'').trim(),'PAN is required.');booksRequire_(String(d.Address||'').trim(),'Address is required.');booksRequire_(String(d.City||'').trim(),'City is required.');booksRequire_(String(d.State||'').trim(),'State is required.');booksRequire_(String(d.Pincode||'').trim(),'Pincode is required.');booksRequire_(String(d.Phone||'').trim(),'Phone is required.');var id=booksId_('ORG'),now=tcNow_(),code='TC-ORG-'+String(Math.floor(100000+Math.random()*900000));var row={OrganisationID:id,OrganisationCode:code,Name:String(d.Name||'').trim(),LegalName:String(d.LegalName||'').trim(),OrganisationType:String(d.OrganisationType||''),BusinessDescription:String(d.BusinessDescription||''),Industry:String(d.Industry||''),Website:String(d.Website||''),GSTIN:String(d.GSTIN||'').toUpperCase(),PAN:String(d.PAN||'').toUpperCase(),TAN:String(d.TAN||'').toUpperCase(),CIN:String(d.CIN||'').toUpperCase(),LLPIN:String(d.LLPIN||'').toUpperCase(),UDYAM:String(d.UDYAM||'').toUpperCase(),IEC:String(d.IEC||'').toUpperCase(),Email:tcEmail_(d.Email||u.Email),Phone:String(d.Phone||''),AlternatePhone:String(d.AlternatePhone||''),ContactPerson:String(d.ContactPerson||u.Name),Address:String(d.Address||''),Address2:String(d.Address2||''),City:String(d.City||''),District:String(d.District||''),State:String(d.State||''),Country:String(d.Country||'India'),Pincode:String(d.Pincode||''),BaseCurrency:String(d.BaseCurrency||'INR'),BooksStartDate:String(d.BooksStartDate||''),FinancialYearStartMonth:String(d.FinancialYearStartMonth||'4'),GSTRegistered:String(d.GSTRegistered||'NO'),GSTRegistrationType:String(d.GSTRegistrationType||''),GSTState:String(d.GSTState||''),DefaultTaxTreatment:String(d.DefaultTaxTreatment||''),AccountingMethod:String(d.AccountingMethod||'ACCRUAL'),Status:'ACTIVE',CreatedAt:now,UpdatedAt:now};tcAppend_('Organisations',row);var member={MembershipID:booksId_('MEM'),OrganisationID:id,OrganisationCode:code,Email:u.Email,Name:u.Name,UserID:u.UserID,Role:'OWNER',Status:'ACTIVE',JoinedAt:now,ApprovedBy:u.UserID,ApprovedAt:now,RejectedBy:'',RejectedAt:'',Remarks:'Organisation creator',CreatedAt:now,UpdatedAt:now};tcAppend_('OrganisationMembers',member);booksUpdate_('Users','UserID',u.UserID,{OrganisationID:id,Role:'OWNER',UpdatedAt:now});var user=tcFind_('Users','UserID',u.UserID),session=tcCreateSession_(user,id);tcAuditOrg_('CREATE_ORGANISATION',id,u.UserID,'Organisation',id,{name:row.Name},true,'');return{organisation:row,organisationCode:code,organisationId:id,user:tcPublicUser_(user),session:session,organisationAccess:'ACTIVE'};}
function tcFindOrganisation_(input){booksAuth_(input.token);var code=String(input.organisationCode||'').trim().toUpperCase(),rows=tcRows_('Organisations'),found=null;for(var i=0;i<rows.length;i++){var r=rows[i];if(String(r.OrganisationID).toUpperCase()===code||String(r.OrganisationCode||'').toUpperCase()===code){found=r;break;}}booksRequire_(found&&found.Status==='ACTIVE','Organisation not found or inactive.');return{organisation:{OrganisationID:found.OrganisationID,OrganisationCode:found.OrganisationCode||'',Name:found.Name,LegalName:found.LegalName,GSTIN:found.GSTIN,PAN:found.PAN,State:found.State,City:found.City,Status:found.Status}};}
function tcRequestJoin_(input){var u=booksAuth_(input.token),orgId=String(input.organisationId||''),org=tcFind_('Organisations','OrganisationID',orgId);booksRequire_(org&&org.Status==='ACTIVE','Organisation not found or inactive.');booksRequire_(orgId!==String(u.OrganisationID||''),'You are already linked to this organisation.');booksRequire_(!tcMembership_(u.UserID,orgId),'You already have membership in this organisation.');var existing=tcFilter_('JoinRequests',function(r){return String(r.UserID)===String(u.UserID)&&String(r.OrganisationID)===orgId&&String(r.Status)==='PENDING';})[0];booksRequire_(!existing,'A join request is already pending.');var now=tcNow_(),id=booksId_('JREQ');tcAppend_('JoinRequests',{JoinRequestID:id,OrganisationID:orgId,OrganisationCode:String(input.organisationCode||org.OrganisationCode||orgId),UserID:u.UserID,Email:u.Email,Name:u.Name,Status:'PENDING',RequestedAt:now,ReviewedBy:'',ReviewedAt:'',Remarks:''});tcAppend_('OrganisationMembers',{MembershipID:booksId_('MEM'),OrganisationID:orgId,OrganisationCode:org.OrganisationCode||'',UserID:u.UserID,Email:u.Email,Name:u.Name,Role:'EMPLOYEE',Status:'PENDING',JoinedAt:'',ApprovedBy:'',ApprovedAt:'',RejectedBy:'',RejectedAt:'',Remarks:'Join request pending',CreatedAt:now,UpdatedAt:now});tcAuditOrg_('REQUEST_JOIN',orgId,u.UserID,'Organisation',orgId,{},true,'');return{requestId:id,status:'PENDING',message:'Join request submitted. Organisation admin approval is required before access is granted.'};}
function tcRequireOrgAdmin_(u,orgId){booksRequire_(u.Role==='OWNER'||u.Role==='ADMIN','Only Organisation Owner/Admin can approve membership requests.');booksRequire_(String(u.OrganisationID)===String(orgId),'You do not have access to this organisation.');}
function tcApproveJoin_(input){var u=booksAuth_(input.token),req=tcFind_('JoinRequests','JoinRequestID',input.joinRequestId);booksRequire_(req,'Join request not found.');tcRequireOrgAdmin_(u,req.OrganisationID);booksRequire_(req.Status==='PENDING','Join request is no longer pending.');var now=tcNow_();booksUpdate_('JoinRequests','JoinRequestID',req.JoinRequestID,{Status:'APPROVED',ReviewedBy:u.UserID,ReviewedAt:now,Remarks:String(input.remarks||'')});var ms=tcFilter_('OrganisationMembers',function(r){return String(r.OrganisationID)===String(req.OrganisationID)&&String(r.UserID)===String(req.UserID)&&String(r.Status)==='PENDING';});if(ms[0])booksUpdate_('OrganisationMembers','MembershipID',ms[0].MembershipID,{Status:'ACTIVE',JoinedAt:now,ApprovedBy:u.UserID,ApprovedAt:now,Remarks:String(input.remarks||'Approved')});tcAuditOrg_('APPROVE_JOIN',req.OrganisationID,u.UserID,'JoinRequest',req.JoinRequestID,{},true,'');return{approved:true,requestId:req.JoinRequestID};}
function tcRejectJoin_(input){var u=booksAuth_(input.token),req=tcFind_('JoinRequests','JoinRequestID',input.joinRequestId);booksRequire_(req,'Join request not found.');tcRequireOrgAdmin_(u,req.OrganisationID);booksRequire_(req.Status==='PENDING','Join request is no longer pending.');var now=tcNow_(),remarks=String(input.remarks||'Rejected by Organisation Admin');booksUpdate_('JoinRequests','JoinRequestID',req.JoinRequestID,{Status:'REJECTED',ReviewedBy:u.UserID,ReviewedAt:now,Remarks:remarks});var ms=tcFilter_('OrganisationMembers',function(r){return String(r.OrganisationID)===String(req.OrganisationID)&&String(r.UserID)===String(req.UserID)&&String(r.Status)==='PENDING';});if(ms[0])booksUpdate_('OrganisationMembers','MembershipID',ms[0].MembershipID,{Status:'REJECTED',RejectedBy:u.UserID,RejectedAt:now,Remarks:remarks});tcAuditOrg_('REJECT_JOIN',req.OrganisationID,u.UserID,'JoinRequest',req.JoinRequestID,{remarks:remarks},true,'');return{rejected:true,requestId:req.JoinRequestID};}
function tcListJoinRequests_(input){var u=booksAuth_(input.token);booksRequire_(u.OrganisationID,'Organisation setup is required.');var status=String(input.status||'PENDING').toUpperCase();return{requests:tcFilter_('JoinRequests',function(r){return String(r.OrganisationID)===String(u.OrganisationID)&&String(r.Status).toUpperCase()===status;})};}
function tcListMembers_(input){var u=booksAuth_(input.token);booksRequire_(u.OrganisationID,'Organisation setup is required.');return{members:tcFilter_('OrganisationMembers',function(r){return String(r.OrganisationID)===String(u.OrganisationID);})};}
function tcUpdateMember_(input){var u=booksAuth_(input.token),m=tcFind_('OrganisationMembers','MembershipID',input.membershipId);booksRequire_(m,'Membership not found.');tcRequireOrgAdmin_(u,m.OrganisationID);var p=input.member||{},patch={};['Role','Status','Remarks','Name'].forEach(function(k){if(p[k]!==undefined)patch[k]=p[k];});patch.UpdatedAt=tcNow_();booksUpdate_('OrganisationMembers','MembershipID',m.MembershipID,patch);if(p.Role||p.Status){var up={UpdatedAt:tcNow_()};if(p.Role)up.Role=p.Role;if(p.Status==='INACTIVE')up.Status='INACTIVE';if(p.Status==='ACTIVE')up.Status='ACTIVE';booksUpdate_('Users','UserID',m.UserID,up);}return{member:tcFind_('OrganisationMembers','MembershipID',m.MembershipID)};}
function tcListEmployees_(input){var u=booksAuth_(input.token);booksRequire_(u.OrganisationID,'Organisation setup is required.');return{employees:tcFilter_('Employees',function(r){return String(r.OrganisationID)===String(u.OrganisationID);})};}
function tcSaveEmployee_(input){var u=booksAuth_(input.token);booksRequire_(u.Role==='OWNER'||u.Role==='ADMIN','Only owner/admin can manage employees.');booksRequire_(u.OrganisationID,'Organisation setup is required.');var d=input.employee||{},id=d.EmployeeID||booksId_('EMP'),old=tcFind_('Employees','EmployeeID',id),now=tcNow_(),row={EmployeeID:id,OrganisationID:u.OrganisationID,EmployeeCode:String(d.EmployeeCode||''),FirstName:String(d.FirstName||''),LastName:String(d.LastName||''),Email:tcEmail_(d.Email||''),Mobile:String(d.Mobile||''),DateOfBirth:String(d.DateOfBirth||''),Gender:String(d.Gender||''),EmergencyContact:String(d.EmergencyContact||''),Department:String(d.Department||''),Designation:String(d.Designation||''),JoiningDate:String(d.JoiningDate||''),EmploymentType:String(d.EmploymentType||'FULL_TIME'),ReportingManagerID:String(d.ReportingManagerID||''),Branch:String(d.Branch||''),Location:String(d.Location||''),PAN:String(d.PAN||'').toUpperCase(),BankName:String(d.BankName||''),AccountNumberMasked:String(d.AccountNumberMasked||''),IFSC:String(d.IFSC||'').toUpperCase(),UAN:String(d.UAN||''),PFApplicable:String(d.PFApplicable||'NO'),ESIApplicable:String(d.ESIApplicable||'NO'),ProfessionalTaxApplicable:String(d.ProfessionalTaxApplicable||'NO'),UserID:String(d.UserID||''),Status:String(d.Status||'ACTIVE'),CreatedAt:old?old.CreatedAt:now,UpdatedAt:now};if(old)booksUpdate_('Employees','EmployeeID',id,row);else tcAppend_('Employees',row);return{employee:row};}
function tcAuditOrg_(action,orgId,userId,entity,entityId,metadata,success,error){try{booksAppend_('AuditLogs',{AuditID:booksId_('AUD'),OrganisationID:orgId||'',UserID:userId||'',Action:action,Entity:entity||'',EntityID:entityId||'',Metadata:JSON.stringify(metadata||{}),CreatedAt:tcNow_(),Success:success?'TRUE':'FALSE',Error:error||''});}catch(ignore){}}
function tcBooksOrganisationRoute_(action,input){switch(action){case'booksCreateOrganisation':return tcCreateOrganisation_(input);case'booksFindOrganisation':return tcFindOrganisation_(input);case'booksRequestJoinOrganisation':return tcRequestJoin_(input);case'booksApproveJoinRequest':return tcApproveJoin_(input);case'booksRejectJoinRequest':return tcRejectJoin_(input);case'booksListJoinRequests':return tcListJoinRequests_(input);case'booksListOrganisationMembers':return tcListMembers_(input);case'booksUpdateOrganisationMember':return tcUpdateMember_(input);case'booksListEmployees':return tcListEmployees_(input);case'booksSaveEmployee':return tcSaveEmployee_(input);case'booksVerifyOtp':return tcBooksVerifyOtp_(input);case'booksMe':return tcBooksMe_(input);}return null;}
var TC_BOOKS_ORIGINAL_ROUTE=booksRoute_;
booksRoute_=function(action,input){var extension=tcBooksOrganisationRoute_(action,input);return extension!==null?extension:TC_BOOKS_ORIGINAL_ROUTE(action,input);};
