import { useState } from 'react'
import { ArrowLeft, Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react'
import BrandLogo from '../components/BrandLogo'

const money = value => `₹${Number(value || 0).toLocaleString('en-IN', { maximumFractionDigits: 2 })}`

export default function CartPage({ items, brandName, subtotal, savings, total, onQty, onDenomination, onRemove, onContinue, onCheckout }) {
  const [editing, setEditing] = useState({})
  const saveDenomination = (item, value) => { const amount = Number(value); if (!Number.isFinite(amount) || amount < 100 || amount > 10000) return; onDenomination(item, amount); setEditing(current => ({ ...current, [item.CartID]: undefined })) }
  return <main className="page-shell"><div className="page-banner compact"><button className="back-link" onClick={onContinue}><ArrowLeft size={16}/> Continue shopping</button><span className="eyebrow">YOUR CART</span><h1>Your saved vouchers.</h1><p>{items.length} voucher line{items.length === 1 ? '' : 's'} ready for checkout.</p></div>{items.length ? <div className="cart-layout-page"><div className="cart-lines">{items.map(item => { const amount = Number(item.denomination || item.product.FaceValue || 0); return <article className="cart-line-card" key={item.CartID}><BrandLogo name={brandName(item.product.BrandID)} size="lg"/><div className="cart-line-copy"><span>{brandName(item.product.BrandID)}</span><h3>{item.product.Title}</h3><div className="cart-denomination"><small>DENOMINATION</small>{editing[item.CartID] !== undefined ? <input autoFocus type="number" min="100" max="10000" step="50" defaultValue={amount} onBlur={e => saveDenomination(item, e.target.value)} onKeyDown={e => { if (e.key === 'Enter') saveDenomination(item, e.currentTarget.value); if (e.key === 'Escape') setEditing(current => ({ ...current, [item.CartID]: undefined })) }} /> : <button onClick={() => setEditing(current => ({ ...current, [item.CartID]: amount }))}>₹{amount.toLocaleString('en-IN')} <span>Edit</span></button>}</div><strong>{money(item.unitPrice || amount * (1 - Number(item.product.DiscountPercent || 0) / 100))} each</strong></div><div className="qty-control"><button onClick={() => onQty(item, Number(item.Quantity) - 1)} disabled={Number(item.Quantity) <= 1}><Minus size={15}/></button><b>{item.Quantity}</b><button onClick={() => onQty(item, Number(item.Quantity) + 1)} disabled={Number(item.Quantity) >= 20}><Plus size={15}/></button></div><button className="remove-line" onClick={() => onRemove(item)} aria-label="Remove voucher"><Trash2 size={16}/></button></article>})}</div><aside className="summary-card"><span className="eyebrow">ORDER SUMMARY</span><div><span>Subtotal</span><strong>{money(subtotal)}</strong></div><div className="saving-row"><span>Savings</span><strong>- {money(savings)}</strong></div><hr/><div className="summary-total"><span>Total</span><strong>{money(total)}</strong></div><button className="btn-primary wide" onClick={onCheckout}>Proceed to payment <ShoppingBag size={16}/></button></aside></div> : <div className="empty-panel"><ShoppingBag size={30}/><h3>Your cart is empty</h3><p>Add a voucher and it will stay linked to your account.</p><button className="btn-primary" onClick={onContinue}>Browse vouchers</button></div>}</main>
}
