import { ArrowRight,Gift,ShieldCheck,Sparkles,WalletCards,Zap } from 'lucide-react'
import BrandLogo from '../components/BrandLogo'

const priority=['Amazon Pay','Flipkart','MakeMyTrip','Myntra','Swiggy','Zomato','Croma','AJIO','Nykaa','BookMyShow']
const sortBrands=brands=>[...brands].sort((a,b)=>{const ai=priority.findIndex(x=>x.toLowerCase()===String(a.Name||'').toLowerCase()),bi=priority.findIndex(x=>x.toLowerCase()===String(b.Name||'').toLowerCase());return(ai<0?999:ai)-(bi<0?999:bi)||String(a.Name).localeCompare(String(b.Name))})
export default function HomePage({brands,onBrowse}){
 const ordered=sortBrands(brands)
 return <main className="page-home"><section className="home-hero home-hero-premium"><div className="home-hero-copy"><span className="eyebrow"><Sparkles size={15}/> TRUSTED CIRCLE</span><h1>Gift better.<br/><em>Get cashback.</em></h1><p>Choose a brand, select your voucher value and pay the full value. Your discount comes back to your Trusted Circle wallet after payment is verified.</p><div className="hero-buttons"><button className="btn-primary" onClick={()=>onBrowse('brands')}>Explore brands <ArrowRight size={17}/></button><button className="btn-quiet" onClick={()=>onBrowse('vouchers')}>Shop vouchers</button></div><div className="hero-points"><span><ShieldCheck size={16}/> Secure checkout</span><span><Zap size={16}/> Digital vouchers</span><span><WalletCards size={16}/> Cashback wallet</span></div></div><div className="hero-art"><div className="hero-orbit hero-orbit-a"/><div className="hero-orbit hero-orbit-b"/><div className="hero-gift-card"><div className="hero-card-top"><span><img src="https://raw.githubusercontent.com/trustedcircle2026-cloud/Trusted-Circle/main/Logo%20new.jpg" alt="Trusted Circle"/> Trusted Circle</span><small>CASHBACK WALLET</small></div><strong>₹2,000</strong><div><span>PAY FULL VALUE</span><b>GET CASHBACK</b></div></div><div className="hero-save"><small>YOUR BENEFIT</small><strong>₹</strong><span>WALLET</span></div></div></section><section className="home-section"><div className="section-title"><div><span className="eyebrow">POPULAR BRANDS</span><h2>Shop by brand</h2></div><button className="text-action" onClick={()=>onBrowse('brands')}>View all <ArrowRight size={15}/></button></div><div className="brand-logo-grid home-brand-grid">{ordered.slice(0,12).map(b=><button key={b.BrandID} className="brand-logo-tile" onClick={()=>onBrowse('vouchers',String(b.BrandID))}><BrandLogo name={b.Name} size="lg"/><strong>{b.Name}</strong></button>)}</div></section><section className="home-section home-how"><div className="section-title"><div><span className="eyebrow">SIMPLE FLOW</span><h2>Buy in three steps</h2></div></div><div className="home-step-grid"><article><span>01</span><Gift size={23}/><h3>Choose a brand</h3><p>Pick the voucher you want.</p></article><article><span>02</span><ShieldCheck size={23}/><h3>Pay full value</h3><p>Your cashback is calculated from the voucher value.</p></article><article><span>03</span><WalletCards size={23}/><h3>Get cashback</h3><p>Once payment is verified, cashback reaches your wallet.</p></article></div></section><section className="home-final-cta"><div><span className="eyebrow">READY?</span><h2>Start with your favourite brand.</h2><p>Browse every available brand and choose your voucher.</p></div><button className="btn-primary" onClick={()=>onBrowse('brands')}>Browse all brands <ArrowRight size={17}/></button></section></main>
}
