import { ArrowRight, ChevronRight, Mail, MessageCircle, ShieldCheck } from 'lucide-react'

const CONTENT = {
  about: { label:'ABOUT TRUSTED CIRCLE', title:'A simpler way to gift more value.', intro:'Trusted Circle brings popular gift vouchers, transparent savings and a straightforward digital shopping experience together in one place.', sections:[['What we do','We help customers discover gift vouchers from familiar brands, compare visible discounts and place orders through a simple account-based checkout.'],['Built around clarity','Prices, savings and order status are presented clearly so customers know what they are buying and what happens next.'],['Need help?','Our support team can help with order questions, voucher delivery and checkout assistance.']] },
  'how-it-works': { label:'HOW IT WORKS', title:'Choose. Save. Gift.', intro:'Buying a voucher takes only a few simple steps.', sections:[['1. Browse','Explore brands or search the gift voucher catalogue. Open a voucher to review its value, price and available savings.'],['2. Add to cart','Sign in with your email and OTP, then add the vouchers you want to your persistent cart.'],['3. Checkout','Review your order and choose an available payment route. Your order is created as pending until payment is verified.'],['4. Receive your voucher','After successful payment verification and fulfilment, your digital voucher is delivered according to the applicable product terms.']] },
  offers: { label:'OFFERS', title:'More value on the brands you love.', intro:'Browse the live catalogue for current voucher discounts. Offers and denominations can change based on availability.', sections:[['Transparent pricing','The voucher face value, selling price and saving are shown together before you add an item to your cart.'],['Availability','Only active catalogue products are displayed. Product availability and pricing may change without notice.']] },
  help: { label:'HELP CENTRE', title:'Need a hand?', intro:'Find the quickest route to assistance.', sections:[['Order help','For an order question, keep your Order Number ready and contact us by email or WhatsApp.'],['Payment help','A payment should not be considered successful merely because a pending order was created. Verified payment information is required before an order is marked paid.'],['Account help','Shopping accounts use email verification by OTP. If you cannot access your account, request a fresh verification code.']] },
  contact: { label:'CONTACT', title:'We are here to help.', intro:'For order and shopping support, use either channel below.', sections:[['Email','Send your order details and question to info@trustedcircle.in.'],['WhatsApp','Message +91 94424 56039 with your Order Number and the assistance you need.']] },
  faq: { label:'FAQ', title:'Frequently asked questions.', intro:'A few quick answers about shopping on Trusted Circle.', sections:[['How do I sign in?','Enter your email and verify the one-time code sent to you.'],['When is an order paid?','An order remains pending until payment is independently verified by the backend/payment integration.'],['Can I contact support after checkout?','Yes. Keep the Order Number available so the team can locate the order quickly.']] },
  terms: { label:'LEGAL', title:'Terms & Conditions', intro:'These are general shopping terms for the current Trusted Circle website experience. Product-specific terms may also apply.', sections:[['Orders','Orders are subject to catalogue availability and successful payment verification.'],['Voucher terms','Brand vouchers may have their own validity, redemption and usage conditions. Customers should review applicable product terms before purchase.'],['Changes','Catalogue, pricing, payment methods and availability may change as the service evolves.']] },
  privacy: { label:'LEGAL', title:'Privacy Policy', intro:'We aim to collect and use only the information needed to provide the shopping service.', sections:[['Account information','Email and profile information are used to authenticate your account and associate shopping activity with you.'],['Order information','Order and payment records are maintained for fulfilment, support, reconciliation and security.'],['Protection','Sensitive information should be handled through authorised backend systems and not exposed in public pages or source code.']] },
  refund: { label:'LEGAL', title:'Refund & Cancellation', intro:'Refund and cancellation treatment depends on order status, voucher fulfilment and the applicable product terms.', sections:[['Before fulfilment','Where cancellation is technically available, eligibility may depend on whether payment has been verified and fulfilment has started.'],['After fulfilment','Digital vouchers that have been issued or delivered may be subject to additional restrictions. Contact support with your Order Number.']] },
}

export default function InfoPage({ type='about', onNavigate }) {
  const content = CONTENT[type] || CONTENT.about
  return <main className="info-page"><section className="info-hero"><span className="eyebrow">{content.label}</span><h1>{content.title}</h1><p>{content.intro}</p></section><section className="info-grid">{content.sections.map(([title,text]) => <article key={title} className="info-card"><div className="info-icon"><ShieldCheck size={18}/></div><h2>{title}</h2><p>{text}</p></article>)}</section><section className="info-contact"><div><span className="eyebrow">SUPPORT</span><h2>Need help with an order?</h2><p>Contact us with your Order Number and we will help you with the next step.</p></div><div className="info-contact-actions"><a href="mailto:info@trustedcircle.in"><Mail size={16}/> Email us</a><a href="https://wa.me/919442456039" target="_blank" rel="noreferrer"><MessageCircle size={16}/> WhatsApp</a><button onClick={() => onNavigate('vouchers')}>Shop vouchers <ArrowRight size={16}/></button></div></section><button className="info-back" onClick={() => onNavigate('home')}>Home <ChevronRight size={15}/></button></main>
}
