import { CheckCircle2, Mail, MessageCircle, PackageCheck, ShoppingBag } from 'lucide-react'
const money=value=>`₹${Number(value||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`
export default function OrderPlacedPage({ order, onOrders, onShop, emailHref, whatsappHref }) {
  const items=order?.snapshot?.items||[]
  return <main className="page-shell order-placed-page"><section className="order-success"><div className="success-ring"><CheckCircle2 size={42}/></div><span className="eyebrow">ORDER CREATED</span><h1>Your order is ready for payment.</h1><p>This order is currently <strong>PENDING PAYMENT</strong>. Before payment is completed, you can send the complete order details directly to Trusted Circle by email or WhatsApp.</p>{order?.order&&<div className="success-order"><div><small>ORDER NUMBER</small><strong>{order.order.OrderNumber}</strong></div><div><small>TOTAL</small><strong>{money(order.order.Total)}</strong></div></div>}
    <div className="contact-order-card"><div><span className="eyebrow">SEND ORDER DETAILS</span><h2>How would you like to continue?</h2><p>Your order number, customer name, email, voucher items, quantities, savings and total will be pre-filled in the message.</p></div><div className="contact-order-actions"><a className="contact-action email" href={emailHref}><Mail size={19}/><span><strong>Send by Email</strong><small>info@trustedcircle.in</small></span></a><a className="contact-action whatsapp" href={whatsappHref} target="_blank" rel="noreferrer"><MessageCircle size={20}/><span><strong>Send on WhatsApp</strong><small>+91 94424 56039</small></span></a></div>{items.length>0&&<div className="contact-order-preview"><strong>Order summary</strong>{items.map((item,index)=><div key={`${item.title}-${index}`}><span>{item.brand} — {item.title} × {item.quantity}</span><b>{money(item.total)}</b></div>)}</div>}</div>
    <div className="order-payment-note"><CheckCircle2 size={17}/><span>Sending the order does not mark it as paid. Payment status will only be updated after verified payment is received.</span></div>
    <div className="success-actions"><button className="btn-primary" onClick={onOrders}><PackageCheck size={17}/> View orders</button><button className="btn-quiet" onClick={onShop}><ShoppingBag size={17}/> Continue shopping</button></div>
  </section></main>
}
