import { useMemo, useState } from 'react'
import { ArrowLeft, Check, CheckCircle2, Minus, Plus, ShoppingBag, ShieldCheck, Zap } from 'lucide-react'
import BrandLogo from '../components/BrandLogo'

const money = value => `₹${Number(value || 0).toLocaleString('en-IN', { maximumFractionDigits: 2 })}`

export default function VoucherPage({ product, brandName, onBack, onAdd }) {
  const defaultAmount = Number(product?.FaceValue || 1000)
  const [denomination, setDenomination] = useState(defaultAmount),[quantity,setQuantity]=useState(1),[amountError,setAmountError]=useState(''),[adding,setAdding]=useState(false)
  const discount = Number(product?.DiscountPercent || 0)
  const payable = useMemo(() => Math.round(denomination * (1 - discount / 100) * 100) / 100, [denomination, discount])
  if (!product) return <main className="page-shell"><div className="empty-panel"><h3>Voucher not found</h3><button className="btn-primary" onClick={onBack}>Back to vouchers</button></div></main>
  const updateAmount = value => { const numeric=value===''?'':Number(value);setDenomination(numeric);setAmountError(value===''||numeric<100||numeric>10000?'Choose an amount between ₹100 and ₹10,000.':'') }
  const add = async () => { if(!Number.isFinite(Number(denomination))||Number(denomination)<100||Number(denomination)>10000){setAmountError('Choose an amount between ₹100 and ₹10,000.');return} if(adding)return;setAdding(true);try{await onAdd(product,quantity,Number(denomination));if(localStorage.getItem('tc_session')){window.dispatchEvent(new CustomEvent('tc:cart-added',{detail:{title:product.Title}}));setTimeout(()=>{window.location.hash='#/cart'},120)}}finally{setTimeout(()=>setAdding(false),350)} }
  return <main className="page-shell"><button className="back-link" onClick={onBack}><ArrowLeft size={16}/> Back to vouchers</button><section className="voucher-detail"><div className="voucher-detail-art"><span className="voucher-discount">{discount}% OFF</span><BrandLogo name={brandName} size="xl"/><span>{brandName}</span><h1>{product.Title}</h1><p>Digital gift voucher</p></div><div className="voucher-detail-info"><span className="eyebrow">{brandName.toUpperCase()}</span><h2>{product.Title}</h2><p>{product.Description || 'Use this digital gift voucher with the selected brand, subject to the issuer terms.'}</p><div className="denomination-box"><div className="control-heading"><div><small>VOUCHER DENOMINATION</small><strong>Choose your gift value</strong></div><span>₹100 – ₹10,000</span></div><div className="amount-presets">{[500,1000,2000,5000].map(amount=><button key={amount} className={Number(denomination)===amount?'active':''} onClick={()=>updateAmount(amount)}>₹{amount.toLocaleString('en-IN')}</button>)}</div><label className="amount-input-label">Custom amount<input type="number" min="100" max="10000" step="50" inputMode="decimal" value={denomination} onChange={e=>updateAmount(e.target.value)}/></label>{amountError&&<span className="amount-error">{amountError}</span>}</div><div className="quantity-box"><div><small>QUANTITY</small><strong>{quantity} voucher{quantity===1?'':'s'}</strong></div><div className="qty-control"><button onClick={()=>setQuantity(value=>Math.max(1,value-1))} disabled={quantity<=1}><Minus size={15}/></button><b>{quantity}</b><button onClick={()=>setQuantity(value=>Math.min(20,value+1))} disabled={quantity>=20}><Plus size={15}/></button></div></div><div className="detail-price"><div><small>FACE VALUE</small><del>{money(denomination*quantity)}</del></div><div><small>YOU PAY</small><strong>{money(payable*quantity)}</strong></div><b>Save {discount}%</b></div><button className="btn-primary wide voucher-add-cta" onClick={add} disabled={adding}>{adding?<><Check size={17}/> Added — opening cart</>:<><ShoppingBag size={17}/> Add {quantity} to cart · {money(payable*quantity)}</>}</button><div className="detail-trust"><span><CheckCircle2/> Instant digital delivery</span><span><ShieldCheck/> Secure account checkout</span><span><Zap/> Clear savings before payment</span></div></div></section></main>
}
