import { useMemo, useState } from 'react'
import { ArrowLeft, Check, CheckCircle2, Minus, Plus, ShoppingBag, ShieldCheck, Zap } from 'lucide-react'
import BrandLogo from '../components/BrandLogo'

const DENOMINATIONS=[500,1000,1500,2000]
const money=value=>`₹${Number(value||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`

export default function VoucherPage({product,brandName,onBack,onAdd}){
  const defaultAmount=DENOMINATIONS.includes(Number(product?.FaceValue))?Number(product.FaceValue):1000
  const [denomination,setDenomination]=useState(defaultAmount),[quantity,setQuantity]=useState(1),[adding,setAdding]=useState(false)
  const discount=Number(product?.DiscountPercent||0)
  const cashback=useMemo(()=>Math.round(denomination*discount)/100,[denomination,discount])
  if(!product)return <main className="page-shell"><div className="empty-panel"><h3>Voucher not found</h3><button className="btn-primary" onClick={onBack}>Back to vouchers</button></div></main>
  const add=async()=>{if(adding)return;setAdding(true);try{await onAdd(product,quantity,denomination);if(localStorage.getItem('tc_session')){window.dispatchEvent(new CustomEvent('tc:cart-added',{detail:{title:product.Title}}));setTimeout(()=>{window.location.hash='#/cart'},120)}}finally{setTimeout(()=>setAdding(false),350)}}
  return <main className="page-shell"><button className="back-link" onClick={onBack}><ArrowLeft size={16}/> Back to vouchers</button><section className="voucher-detail"><div className="voucher-detail-art"><span className="voucher-discount">{discount}% CASHBACK</span><BrandLogo name={brandName} size="xl"/><span>{brandName}</span><h1>{product.Title}</h1><p>Digital gift voucher</p></div><div className="voucher-detail-info"><span className="eyebrow">{brandName.toUpperCase()}</span><h2>{product.Title}</h2><p>{product.Description||'Digital gift voucher for the selected brand.'}</p><div className="denomination-box"><div className="control-heading"><div><small>GIFT VALUE</small><strong>Choose your voucher value</strong></div><span>4 options</span></div><div className="amount-presets">{DENOMINATIONS.map(amount=><button key={amount} className={denomination===amount?'active':''} onClick={()=>setDenomination(amount)}>₹{amount.toLocaleString('en-IN')}</button>)}</div></div><div className="quantity-box"><div><small>QUANTITY</small><strong>{quantity} voucher{quantity===1?'':'s'}</strong></div><div className="qty-control"><button onClick={()=>setQuantity(value=>Math.max(1,value-1))} disabled={quantity<=1}><Minus size={15}/></button><b>{quantity}</b><button onClick={()=>setQuantity(value=>Math.min(9999,value+1))}><Plus size={15}/></button></div></div><div className="detail-price"><div><small>VOUCHER VALUE</small><strong>{money(denomination*quantity)}</strong></div><div><small>CASHBACK</small><strong>+ {money(cashback*quantity)}</strong></div><b>{discount}% cashback</b></div><button className="btn-primary wide voucher-add-cta" onClick={add} disabled={adding}>{adding?<><Check size={17}/> Added — opening cart</>:<><ShoppingBag size={17}/> Add {quantity} to cart · {money(denomination*quantity)}</>}</button><div className="detail-trust"><span><CheckCircle2/> Digital delivery</span><span><ShieldCheck/> Secure checkout</span><span><Zap/> Cashback after payment</span></div></div></section></main>
}
