import { ChevronDown,Search,X } from 'lucide-react'
import VoucherCard from '../components/VoucherCard'
const priority=['Amazon Pay','Flipkart','MakeMyTrip','Myntra','Swiggy','Zomato','Croma','AJIO','Nykaa','BookMyShow']
const rank=name=>{const i=priority.findIndex(x=>x.toLowerCase()===String(name||'').toLowerCase());return i<0?999:i}
export default function VouchersPage({products,brands,brandFilter,setBrandFilter,query,setQuery,brandName,liked,onLike,onAdd,onOpen}){
 const ordered=[...products].sort((a,b)=>rank(brandName(a.BrandID))-rank(brandName(b.BrandID))||String(a.Title||'').localeCompare(String(b.Title||'')))
 const orderedBrands=[...brands].sort((a,b)=>rank(a.Name)-rank(b.Name)||String(a.Name||'').localeCompare(String(b.Name||'')))
 return <main className="page-shell"><div className="page-banner"><span className="eyebrow">GIFT VOUCHERS</span><h1>Choose a brand you love.</h1><p>Select a voucher value from ₹500, ₹1,000, ₹1,500 or ₹2,000.</p></div><div className="catalog-toolbar"><label className="catalog-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search brands or vouchers"/>{query&&<button onClick={()=>setQuery('')}><X size={15}/></button>}</label><label className="catalog-select"><select value={brandFilter} onChange={e=>setBrandFilter(e.target.value)}><option value="">All brands</option>{orderedBrands.map(b=><option key={b.BrandID} value={b.BrandID}>{b.Name}</option>)}</select><ChevronDown size={15}/></label></div>{brandFilter&&<div className="active-filter">{brandName(brandFilter)}<button onClick={()=>setBrandFilter('')}><X size={13}/></button></div>}{ordered.length?<div className="voucher-grid">{ordered.map(p=><VoucherCard key={p.ProductID} product={p} brandName={brandName(p.BrandID)} liked={liked.includes(p.ProductID)} onLike={onLike} onAdd={onAdd} onOpen={()=>onOpen(p.ProductID)}/>)}</div>:<div className="empty-panel"><h3>No matching vouchers</h3><p>Try another brand or search.</p></div>}</main>
}
