/** Fast admin overview for the automated shopping operation. */
function adminCachedRows_(name){var key='tc_admin_rows_'+String(name),cache=CacheService.getScriptCache(),hit=cache.get(key);if(hit){try{return JSON.parse(hit);}catch(e){}}var rows=getRows_(TC_CONFIG.SHEETS[name]||name);try{cache.put(key,JSON.stringify(rows),12);}catch(e){}return rows;}
function adminDashboardFast_(data){
  var admin=adminAuthenticate_(data.token),names=['Users','Orders','Payments','PaymentLinkRequests','PaymentLinkStock','Vouchers','Products','Brands','Cart','Notifications','CashbackWallet','CashbackTransactions','WalletRedemptions'],raw={};names.forEach(function(name){raw[name]=adminCachedRows_(name);});
  var tables={};['Users','Orders','Payments','PaymentLinkRequests','PaymentLinkStock','Vouchers','Products','Brands','CashbackWallet','CashbackTransactions','WalletRedemptions'].forEach(function(name){var rows=raw[name]||[];tables[name]={idField:TC_ADMIN_SHEETS[name],columns:rows.length?Object.keys(rows[0]):getSheetHeaders_(name),rows:rows.slice(-200).reverse()};});
  var orders=raw.Orders||[],users=raw.Users||[],payments=raw.Payments||[],requests=raw.PaymentLinkRequests||[],stock=raw.PaymentLinkStock||[],vouchers=raw.Vouchers||[],redemptions=raw.WalletRedemptions||[],wallets=raw.CashbackWallet||[];
  var worklist=[];
  vouchers.forEach(function(r){var st=String(r.Status||'').toUpperCase();if(['PENDING','PROCESSING','READY'].indexOf(st)>=0)worklist.push({sheet:'Vouchers',type:'Voucher',priority:'High',title:'Voucher needs delivery',detail:st.replace(/_/g,' '),status:st,when:r.IssuedAt||r.CreatedAt,recordId:r.VoucherID});});
  redemptions.forEach(function(r){var st=String(r.Status||'').toUpperCase();if(['REQUESTED','PROCESSING'].indexOf(st)>=0)worklist.push({sheet:'WalletRedemptions',type:'Cashback',priority:'Normal',title:'Cashback redemption request',detail:st.replace(/_/g,' ')+' · ₹'+Number(r.Amount||0).toLocaleString('en-IN'),status:st,when:r.CreatedAt||r.UpdatedAt,recordId:r.RedemptionID});});
  var availableByDenom={500:0,1000:0,1500:0,2000:0};stock.forEach(function(r){if(String(r.Status||'').toUpperCase()==='AVAILABLE'&&availableByDenom[Number(r.Denomination)]!==undefined)availableByDenom[Number(r.Denomination)]++;});
  [500,1000,1500,2000].forEach(function(d){if(availableByDenom[d]<1)worklist.push({sheet:'PaymentLinkStock',type:'Link stock',priority:'High',title:'₹'+d.toLocaleString('en-IN')+' payment links need restocking',detail:'No available payment link',status:'LOW_STOCK',when:isoNow_(),recordId:'stock-'+d});});
  (raw.Notifications||[]).forEach(function(r){if(!r.ReadAt)worklist.push({sheet:'Notifications',type:'Notification',priority:'Normal',title:r.Title||'Unread notification',detail:r.Message||'Unread notification',status:'UNREAD',when:r.CreatedAt,recordId:r.NotificationID});});
  worklist.sort(function(a,b){return String(b.when||'').localeCompare(String(a.when||''));});
  var paidOrders=orders.filter(function(r){return ['PAID','PROCESSING','DELIVERED'].indexOf(String(r.Status||'').toUpperCase())>=0;});
  var grossSales=paidOrders.reduce(function(sum,r){return sum+Number(r.Total||0);},0),cashback=paidOrders.reduce(function(sum,r){return sum+Number(r.Discount||0);},0),collected=payments.filter(function(r){return ['VERIFIED','PAID','CAPTURED'].indexOf(String(r.Status||'').toUpperCase())>=0;}).reduce(function(sum,r){return sum+Number(r.Amount||0);},0),refundedOrders=orders.filter(function(r){return String(r.Status||'').toUpperCase()==='REFUNDED';}),refunds=refundedOrders.reduce(function(sum,r){return sum+Number(r.Total||0);},0);
  var status={};orders.forEach(function(r){var st=String(r.Status||'UNKNOWN').toUpperCase();status[st]=(status[st]||0)+1;});
  var byUser={};orders.forEach(function(r){var uid=String(r.UserID||'');if(!uid)return;if(!byUser[uid])byUser[uid]={orders:0,paidOrders:0,pendingOrders:0,deliveredOrders:0,value:0};var x=byUser[uid],st=String(r.Status||'').toUpperCase();x.orders++;if(['PAID','PROCESSING','DELIVERED'].indexOf(st)>=0){x.paidOrders++;x.value+=Number(r.Total||0);}if(['PENDING_PAYMENT','PAYMENT_PROCESSING'].indexOf(st)>=0)x.pendingOrders++;if(st==='DELIVERED')x.deliveredOrders++;});
  var userMap={};users.forEach(function(u){userMap[String(u.UserID)]={name:u.Name||'Shopper',email:u.Email||''};});
  var shopperReport=Object.keys(byUser).map(function(uid){var x=byUser[uid],u=userMap[uid]||{};return{name:u.name||'Shopper',email:u.email||'',userId:uid,orders:x.orders,paidOrders:x.paidOrders,pendingOrders:x.pendingOrders,deliveredOrders:x.deliveredOrders,value:x.value};}).sort(function(a,b){return b.value-a.value;}).slice(0,100);
  var pendingRedemptions=redemptions.filter(function(r){return ['REQUESTED','PROCESSING'].indexOf(String(r.Status||'').toUpperCase())>=0;}).length;
  var metrics={shoppers:users.filter(function(r){return String(r.Role||'').toUpperCase()!=='ADMIN';}).length,orders:orders.length,pendingOrders:orders.filter(function(r){return String(r.Status||'').toUpperCase()==='PENDING_PAYMENT';}).length,paidOrders:paidOrders.length,revenue:collected,cashback:cashback,pendingRedemptions:pendingRedemptions,availableLinks:stock.filter(function(r){return String(r.Status||'').toUpperCase()==='AVAILABLE';}).length};
  var result={admin:publicUser_(admin),tables:tables,metrics:metrics,worklist:worklist.slice(0,100),sheetCounts:{},reports:{pnl:{grossSales:grossSales,discounts:cashback,collected:collected,refunds:refunds,paidOrders:paidOrders.length,refundedOrders:refundedOrders.length},status:status},shopperReport:shopperReport};names.forEach(function(name){result.sheetCounts[name]=(raw[name]||[]).length;});return result;
}
function adminTable_(data){adminAuthenticate_(data.token);var sheetName=cleanText_(data.sheet,60),idField=TC_ADMIN_SHEETS[sheetName];require_(idField,'Unknown ERP sheet.');var rows=adminCachedRows_(sheetName);return{sheet:sheetName,table:{idField:idField,columns:rows.length?Object.keys(rows[0]):getSheetHeaders_(sheetName),rows:rows.slice(-500).reverse()}};}
