/** Fast admin overview. Reads only operational sheets and caches them briefly. */
function adminCachedRows_(name){var key='tc_admin_rows_'+String(name),cache=CacheService.getScriptCache(),hit=cache.get(key);if(hit){try{return JSON.parse(hit);}catch(e){}}var rows=getRows_(TC_CONFIG.SHEETS[name]||name);try{cache.put(key,JSON.stringify(rows),12);}catch(e){}return rows;}
function adminDashboardFast_(data){
  var admin=adminAuthenticate_(data.token),names=['Users','Orders','Payments','PaymentLinkRequests','Vouchers','Products','Brands','Cart','Notifications'],raw={};
  names.forEach(function(name){raw[name]=adminCachedRows_(name);});
  var tables={};['Users','Orders','Payments','PaymentLinkRequests','Vouchers','Products','Brands'].forEach(function(name){var rows=raw[name]||[];tables[name]={idField:TC_ADMIN_SHEETS[name],columns:rows.length?Object.keys(rows[0]):getSheetHeaders_(name),rows:rows.slice(-120).reverse()};});
  var orders=raw.Orders||[],users=raw.Users||[],payments=raw.Payments||[],requests=raw.PaymentLinkRequests||[],vouchers=raw.Vouchers||[];
  var worklist=[];
  orders.forEach(function(r){var st=String(r.Status||'').toUpperCase();if(['PENDING_PAYMENT','PAYMENT_PROCESSING','PROCESSING'].indexOf(st)>=0)worklist.push({sheet:'Orders',type:'Order',priority:st==='PENDING_PAYMENT'?'High':'Normal',title:'Order '+(r.OrderNumber||'needs attention'),detail:st.replace(/_/g,' ')+' · ₹'+Number(r.Total||0).toLocaleString('en-IN'),status:st,when:r.UpdatedAt||r.CreatedAt,recordId:r.OrderID});});
  payments.forEach(function(r){var st=String(r.Status||'').toUpperCase();if(['PENDING','PROCESSING'].indexOf(st)>=0)worklist.push({sheet:'Payments',type:'Payment',priority:'High',title:'Payment needs review',detail:(r.Provider||'Payment')+' · ₹'+Number(r.Amount||0).toLocaleString('en-IN'),status:st,when:r.UpdatedAt||r.CreatedAt,recordId:r.PaymentID});});
  requests.forEach(function(r){var st=String(r.Status||'').toUpperCase();if(['REQUESTED','PROCESSING'].indexOf(st)>=0)worklist.push({sheet:'PaymentLinkRequests',type:'Payment link',priority:'High',title:'Payment link request',detail:st.replace(/_/g,' '),status:st,when:r.UpdatedAt||r.CreatedAt,recordId:r.RequestID});});
  vouchers.forEach(function(r){var st=String(r.Status||'').toUpperCase();if(['PENDING','PROCESSING'].indexOf(st)>=0)worklist.push({sheet:'Vouchers',type:'Voucher',priority:'High',title:'Voucher needs delivery',detail:st.replace(/_/g,' '),status:st,when:r.IssuedAt||r.CreatedAt,recordId:r.VoucherID});});
  (raw.Notifications||[]).forEach(function(r){if(!r.ReadAt)worklist.push({sheet:'Notifications',type:'Notification',priority:'Normal',title:r.Title||'Unread notification',detail:r.Message||'Unread notification',status:'UNREAD',when:r.CreatedAt,recordId:r.NotificationID});});
  (raw.Cart||[]).forEach(function(r){if(Number(r.Quantity||0)>0)worklist.push({sheet:'Cart',type:'Cart',priority:'Low',title:'Open cart item',detail:'Quantity '+Number(r.Quantity||0),status:'OPEN',when:r.UpdatedAt||r.CreatedAt,recordId:r.CartID});});
  worklist.sort(function(a,b){return String(b.when||'').localeCompare(String(a.when||''));});
  var paidOrders=orders.filter(function(r){return ['PAID','PROCESSING','DELIVERED'].indexOf(String(r.Status||'').toUpperCase())>=0;});
  var grossSales=paidOrders.reduce(function(sum,r){return sum+Number(r.Subtotal||r.Total||0);},0),discounts=paidOrders.reduce(function(sum,r){return sum+Number(r.Discount||0);},0),collected=payments.filter(function(r){return ['VERIFIED','PAID','CAPTURED'].indexOf(String(r.Status||'').toUpperCase())>=0;}).reduce(function(sum,r){return sum+Number(r.Amount||0);},0),refundedOrders=orders.filter(function(r){return String(r.Status||'').toUpperCase()==='REFUNDED';}),refunds=refundedOrders.reduce(function(sum,r){return sum+Number(r.Total||0);},0);
  var status={};orders.forEach(function(r){var st=String(r.Status||'UNKNOWN').toUpperCase();status[st]=(status[st]||0)+1;});
  var byUser={};orders.forEach(function(r){var uid=String(r.UserID||'');if(!uid)return;if(!byUser[uid])byUser[uid]={orders:0,paidOrders:0,pendingOrders:0,deliveredOrders:0,value:0};var x=byUser[uid],st=String(r.Status||'').toUpperCase();x.orders++;if(['PAID','PROCESSING','DELIVERED'].indexOf(st)>=0){x.paidOrders++;x.value+=Number(r.Total||0);}if(['PENDING_PAYMENT','PAYMENT_PROCESSING'].indexOf(st)>=0)x.pendingOrders++;if(st==='DELIVERED')x.deliveredOrders++;});
  var userMap={};users.forEach(function(u){userMap[String(u.UserID)]={name:u.Name||'Shopper',email:u.Email||''};});
  var shopperReport=Object.keys(byUser).map(function(uid){var x=byUser[uid],u=userMap[uid]||{};return{name:u.name||'Shopper',email:u.email||'',userId:uid,orders:x.orders,paidOrders:x.paidOrders,pendingOrders:x.pendingOrders,deliveredOrders:x.deliveredOrders,value:x.value};}).sort(function(a,b){return b.value-a.value;}).slice(0,100);
  var metrics={shoppers:users.filter(function(r){return String(r.Role||'').toUpperCase()!=='ADMIN';}).length,orders:orders.length,pendingOrders:orders.filter(function(r){return String(r.Status||'').toUpperCase()==='PENDING_PAYMENT';}).length,paidOrders:paidOrders.length,revenue:collected};
  var result={admin:publicUser_(admin),tables:tables,metrics:metrics,worklist:worklist.slice(0,100),sheetCounts:{},reports:{pnl:{grossSales:grossSales,discounts:discounts,collected:collected,refunds:refunds,paidOrders:paidOrders.length,refundedOrders:refundedOrders.length},status:status},shopperReport:shopperReport};names.forEach(function(name){result.sheetCounts[name]=(raw[name]||[]).length;});return result;
}
function adminTable_(data){adminAuthenticate_(data.token);var sheetName=cleanText_(data.sheet,60),idField=TC_ADMIN_SHEETS[sheetName];require_(idField,'Unknown ERP sheet.');var rows=adminCachedRows_(sheetName);return{sheet:sheetName,table:{idField:idField,columns:rows.length?Object.keys(rows[0]):getSheetHeaders_(sheetName),rows:rows.slice(-500).reverse()}};}
