/** Trusted Circle ERP work queue, controlled admin actions and complete activity logging. */
var TC_ADMIN_PROTECTED_FIELDS=['UserID','OrderID','OrderItemID','PaymentID','PaymentLinkID','PaymentLinkStockID','RequestID','VoucherID','WalletID','TransactionID','RedemptionID','ProductID','BrandID','CartID','NotificationID','OtpID','SessionID','AuditID','TokenHash','OtpHash','CreatedAt','LastLoginAt','RevokedAt','ExpiresAt','UsedAt'];
var TC_ADMIN_PROTECTED_SHEETS={AuditLogs:true,UserSessions:true,OTP:true};
function adminEditableFields_(sheetName){var headers=getSheetHeaders_(sheetName);return headers.filter(function(h){return TC_ADMIN_PROTECTED_FIELDS.indexOf(h)<0;});}
function adminEditAnyRow_(data){var admin=adminAuthenticate_(data.token),sheetName=cleanText_(data.sheet,60),idField=TC_ADMIN_SHEETS[sheetName],id=cleanText_(data.id,200),patch=data.patch||{};require_(idField,'Unknown ERP sheet.');require_(id,'Row ID is required.');require_(!TC_ADMIN_PROTECTED_SHEETS[sheetName],'This system record is read-only.');var allowed=adminEditableFields_(sheetName),clean={};Object.keys(patch).forEach(function(key){if(allowed.indexOf(key)>=0)clean[key]=cleanText_(patch[key],10000);});require_(Object.keys(clean).length>0,'No editable fields supplied.');require_(findOne_(sheetName,idField,id),'Record not found.');clean.UpdatedAt=isoNow_();require_(updateRowById_(sheetName,idField,id,clean),'Record not found.');appendAudit_(admin.UserID,'ADMIN_EDIT_UPDATE',sheetName,id,{fields:Object.keys(clean),changes:clean});return{ok:true,row:findOne_(sheetName,idField,id)};}
function adminWorklist_(data){adminAuthenticate_(data.token);var names=['Orders','Payments','PaymentLinkRequests','PaymentLinkStock','Vouchers','WalletRedemptions','Notifications'],raw={};names.forEach(function(n){raw[n]=getRows_(TC_CONFIG.SHEETS[n]||n);});var items=[];
 raw.Payments.forEach(function(p){var st=String(p.Status||'PENDING').toUpperCase();if(['PENDING','PAYMENT_PENDING','UNVERIFIED'].indexOf(st)>=0){var o=findOne_(TC_CONFIG.SHEETS.ORDERS,'OrderID',p.OrderID);items.push({sheet:'Payments',recordId:p.PaymentID,kind:'payment',priority:'High',title:'Payment requires verification',subtitle:o?o.OrderNumber:p.ProviderOrderID||p.PaymentID,detail:'₹'+Number(p.Amount||0).toLocaleString('en-IN')+' · '+(p.Provider||'PAYMENT_LINK'),status:st,when:p.CreatedAt||p.UpdatedAt,actions:['VERIFY_PAYMENT','APPROVE','REJECT','CANCEL','REMOVE']});}});
 raw.Orders.forEach(function(o){var st=String(o.Status||'').toUpperCase();if(['PAID','PROCESSING'].indexOf(st)>=0){var delivered=raw.Vouchers.some(function(v){return String(v.OrderID)===String(o.OrderID)&&String(v.Status||'').toUpperCase()==='DELIVERED';});if(!delivered)items.push({sheet:'Orders',recordId:o.OrderID,kind:'voucher',priority:'High',title:'Voucher ready to send',subtitle:o.OrderNumber||o.OrderID,detail:'₹'+Number(o.Total||0).toLocaleString('en-IN')+' · '+st,status:'READY',when:o.UpdatedAt||o.CreatedAt,actions:['SEND_VOUCHER','APPROVE','REJECT','CANCEL','REMOVE']});}});
 raw.WalletRedemptions.forEach(function(r){var st=String(r.Status||'').toUpperCase();if(['REQUESTED','PROCESSING'].indexOf(st)>=0)items.push({sheet:'WalletRedemptions',recordId:r.RedemptionID,kind:'cashback',priority:'Normal',title:'Cashback payout requires processing',subtitle:st.replace(/_/g,' '),detail:'₹'+Number(r.Amount||0).toLocaleString('en-IN')+' · '+(r.Method||''),status:st,when:r.CreatedAt||r.UpdatedAt,actions:['PROCESS_CASHBACK','APPROVE','REJECT','CANCEL','REMOVE']});});
 raw.PaymentLinkRequests.forEach(function(r){var st=String(r.Status||'').toUpperCase();if(['REQUESTED','PENDING','PROCESSING'].indexOf(st)>=0)items.push({sheet:'PaymentLinkRequests',recordId:r.RequestID,kind:'payment',priority:'Normal',title:'Payment-link request requires attention',subtitle:r.Email||r.RequestID,detail:st.replace(/_/g,' '),status:st,when:r.CreatedAt||r.UpdatedAt,actions:['APPROVE','REJECT','CANCEL','REMOVE']});});
 var available={500:0,1000:0,1500:0,2000:0};raw.PaymentLinkStock.forEach(function(r){if(String(r.Status||'').toUpperCase()==='AVAILABLE'&&available[Number(r.Denomination)]!==undefined)available[Number(r.Denomination)]++;});[500,1000,1500,2000].forEach(function(d){if(!available[d])items.push({sheet:'PaymentLinkStock',recordId:'stock-'+d,kind:'cashback',priority:'High',title:'₹'+d.toLocaleString('en-IN')+' payment-link stock is empty',subtitle:'Restock required',detail:'No AVAILABLE link for this denomination',status:'LOW_STOCK',when:isoNow_(),actions:['APPROVE','REMOVE']});});
 items.sort(function(a,b){return String(b.when||'').localeCompare(String(a.when||''));});return{items:items.slice(0,200)};}
function adminVerifyPayment_(data){var admin=adminAuthenticate_(data.token),orderId=cleanText_(data.orderId,100),provider=cleanText_(data.provider||'ADMIN_VERIFIED',100),providerPaymentId=cleanText_(data.providerPaymentId||'',200),order=findOne_(TC_CONFIG.SHEETS.ORDERS,'OrderID',orderId);require_(order,'Order not found.');require_(['PENDING_PAYMENT','PAYMENT_PROCESSING','PROCESSING'].indexOf(String(order.Status||'').toUpperCase())>=0,'Order is not awaiting payment verification.');var payments=getRows_(TC_CONFIG.SHEETS.PAYMENTS).filter(function(p){return String(p.OrderID)===orderId;});var payment=payments.length?payments[payments.length-1]:null;require_(payment,'Payment record not found.');var now=isoNow_();updateRowById_(TC_CONFIG.SHEETS.PAYMENTS,'PaymentID',payment.PaymentID,{Status:'VERIFIED',VerifiedAt:now,Provider:provider,ProviderPaymentID:providerPaymentId,UpdatedAt:now});updateRowById_(TC_CONFIG.SHEETS.ORDERS,'OrderID',orderId,{Status:'PAID',UpdatedAt:now});creditCashbackForOrder_(order);if(String(payment.Provider||'').toUpperCase().indexOf('PAYMENT_LINK')>=0){try{getRows_(TC_CONFIG.SHEETS.PAYMENT_LINKS).filter(function(l){return String(l.OrderID)===orderId;}).forEach(function(l){updateRowById_(TC_CONFIG.SHEETS.PAYMENT_LINKS,'PaymentLinkID',l.PaymentLinkID,{Status:'USED',UpdatedAt:now});if(l.PaymentLinkStockID)updateRowById_(TC_CONFIG.SHEETS.PAYMENT_LINK_STOCK,'PaymentLinkStockID',l.PaymentLinkStockID,{Status:'USED',UpdatedAt:now});});}catch(e){}}
 appendAudit_(admin.UserID,'PAYMENT_VERIFIED','Order',orderId,{paymentId:payment.PaymentID,provider:provider,providerPaymentId:providerPaymentId,cashback:Number(order.Discount||0)});return{order:findOne_(TC_CONFIG.SHEETS.ORDERS,'OrderID',orderId),payment:findOne_(TC_CONFIG.SHEETS.PAYMENTS,'PaymentID',payment.PaymentID)};}
function adminWorklistAction_(data){var admin=adminAuthenticate_(data.token),action=cleanText_(data.actionName||'',40).toUpperCase(),sheet=cleanText_(data.sheet,60),recordId=cleanText_(data.recordId,200),reason=cleanText_(data.reason||'',1000);require_(action,'Action is required.');if(action==='REMOVE'){appendAudit_(admin.UserID,'WORKLIST_REMOVE',sheet,recordId,{reason:reason});return{removed:true};}
 if(action==='VERIFY_PAYMENT'){var payment=findOne_(TC_CONFIG.SHEETS.PAYMENTS,'PaymentID',recordId);require_(payment,'Payment record not found.');return adminVerifyPayment_({token:data.token,orderId:payment.OrderID,provider:'PAYTM_MANUAL_ADMIN_VERIFIED',providerPaymentId:''});}
 if(action==='SEND_VOUCHER'){require_(sheet==='Orders','Voucher work item must reference an order.');throw new Error('Use Send Voucher action with voucher code and product.');}
 var row=findOne_(sheet,TC_ADMIN_SHEETS[sheet],recordId);if(!row){if(action==='APPROVE'||action==='REJECT'||action==='CANCEL')throw new Error('Work item record not found.');return{ok:true};}var now=isoNow_();if(action==='APPROVE'){if(sheet==='WalletRedemptions')updateRowById_(sheet,'RedemptionID',recordId,{Status:'PROCESSING',AdminNote:reason,UpdatedAt:now});else if(sheet==='PaymentLinkRequests')updateRowById_(sheet,'RequestID',recordId,{Status:'APPROVED',AdminNote:reason,UpdatedAt:now});else if(sheet==='Orders')updateRowById_(sheet,'OrderID',recordId,{Status:'PROCESSING',UpdatedAt:now});else updateRowById_(sheet,TC_ADMIN_SHEETS[sheet],recordId,{Status:'APPROVED',UpdatedAt:now});}
 else if(action==='REJECT'){if(sheet==='WalletRedemptions')updateRowById_(sheet,'RedemptionID',recordId,{Status:'REJECTED',AdminNote:reason,UpdatedAt:now});else if(sheet==='PaymentLinkRequests')updateRowById_(sheet,'RequestID',recordId,{Status:'REJECTED',AdminNote:reason,UpdatedAt:now});else updateRowById_(sheet,TC_ADMIN_SHEETS[sheet],recordId,{Status:'REJECTED',UpdatedAt:now});}
 else if(action==='CANCEL'){if(sheet==='WalletRedemptions')updateRowById_(sheet,'RedemptionID',recordId,{Status:'CANCELLED',AdminNote:reason,UpdatedAt:now});else if(sheet==='Orders')updateRowById_(sheet,'OrderID',recordId,{Status:'CANCELLED',UpdatedAt:now});else updateRowById_(sheet,TC_ADMIN_SHEETS[sheet],recordId,{Status:'CANCELLED',UpdatedAt:now});}
 else if(action==='PROCESS_CASHBACK'){require_(sheet==='WalletRedemptions','Cashback action requires a payout request.');updateRowById_(sheet,'RedemptionID',recordId,{Status:'COMPLETED',AdminNote:reason,UpdatedAt:now});}
 else throw new Error('Unsupported worklist action.');appendAudit_(admin.UserID,'WORKLIST_'+action,sheet,recordId,{reason:reason});return{ok:true,action:action,row:findOne_(sheet,TC_ADMIN_SHEETS[sheet],recordId)};}
function auditApiActor_(input){var token=String(input&&input.token||'');if(token){try{return authenticate_(token);}catch(e){}}return null;}
function logApiActivity_(input,action,success,errorMessage){var actor=auditApiActor_(input),userId=actor?actor.UserID:'',email=actor?actor.Email:normalizeEmail_(input&&input.email||'');try{appendAudit_(userId,'API_'+(success?'SUCCESS':'FAILED'),action,'',{email:email,success:success,error:errorMessage||'',method:'WEB_API'});}catch(e){}}
