/** Trusted Circle ERP — admin-only service layer. Secrets stay in Script Properties. */
var TC_ADMIN_SHEETS={Users:'UserID',OTP:'OtpID',UserSessions:'SessionID',AuditLogs:'AuditID',Products:'ProductID',Brands:'BrandID',Cart:'CartID',Orders:'OrderID',OrderItems:'OrderItemID',Payments:'PaymentID',PaymentLinks:'PaymentLinkID',PaymentLinkRequests:'RequestID',PaymentLinkStock:'PaymentLinkStockID',Vouchers:'VoucherID',Notifications:'NotificationID',CashbackWallet:'WalletID',CashbackTransactions:'TransactionID',WalletRedemptions:'RedemptionID'};
var TC_ADMIN_EDITABLE={Users:['Email','Name','Role','Status'],Products:['BrandID','SKU','Title','Description','FaceValue','SellingPrice','DiscountPercent','Currency','InventoryStatus','Active'],Brands:['Name','Slug','LogoURL','Active'],Cart:['Quantity'],Notifications:['Type','Title','Message','ReadAt'],WalletRedemptions:['Status','AdminNote']};
function ensurePaymentLinksSheet_(){return ensureSheet_(TC_CONFIG.SHEETS.PAYMENT_LINKS,['PaymentLinkID','OrderID','Link','Label','Status','PaymentLinkStockID','ProviderLinkID','CreatedAt','UpdatedAt']);}
function ensurePaymentLinkRequestsSheet_(){return ensureSheet_(TC_CONFIG.SHEETS.PAYMENT_LINK_REQUESTS,['RequestID','OrderID','UserID','Email','Status','AdminNote','PaymentLinkID','CreatedAt','UpdatedAt']);}
function ensurePaymentLinkStockSheet_(){var sheet=ensureSheet_(TC_CONFIG.SHEETS.PAYMENT_LINK_STOCK,['PaymentLinkStockID','Denomination','Link','Label','Status','OrderID','PaymentLinkID','ProviderLinkID','ReservedAt','ExpiresAt','CreatedAt','UpdatedAt']);ensureColumns_(TC_CONFIG.SHEETS.PAYMENT_LINK_STOCK,['ProviderLinkID','ReservedAt','ExpiresAt']);return sheet;}
function adminLogin_(data){var email=normalizeEmail_(data.email),password=String(data.password||'');require_(email===getAdminEmail_(),'Invalid ERP credentials.');var configured=getAdminPassword_();require_(configured,'ERP admin password is not configured in Script Properties.');require_(constantTimeEquals_(password,configured),'Invalid ERP credentials.');var user=getUserByEmail_(email)||createOrGetUser_(email,'Admin');require_(String(user.Role).toUpperCase()==='ADMIN','ERP access denied.');updateRowById_(TC_CONFIG.SHEETS.USERS,'UserID',user.UserID,{Role:'ADMIN',Status:'ACTIVE',LastLoginAt:isoNow_(),UpdatedAt:isoNow_()});var refreshed=getUserByEmail_(email),session=issueSession_(refreshed);appendAudit_(refreshed.UserID,'ERP_LOGIN','Admin','',{});return{user:publicUser_(refreshed),session:session};}
function adminAuthenticate_(token){var user=authenticate_(token);require_(String(user.Role||'').toUpperCase()==='ADMIN','ERP administrator access required.');require_(normalizeEmail_(user.Email)===getAdminEmail_(),'ERP administrator access required.');return user;}
function appendAudit_(userId,action,entity,entityId,metadata){appendRowObject_(TC_CONFIG.SHEETS.AUDIT,{AuditID:newId_('TCAUD'),UserID:userId,Action:action,Entity:entity,EntityID:entityId||'',Metadata:JSON.stringify(metadata||{}),CreatedAt:isoNow_()});}
function getSheetHeaders_(name){var sheet=getSpreadsheet_().getSheetByName(name);return sheet?sheet.getRange(1,1,1,Math.max(1,sheet.getLastColumn())).getValues()[0]:[];}
function adminDashboard_(data){var admin=adminAuthenticate_(data.token);ensurePaymentLinksSheet_();ensurePaymentLinkRequestsSheet_();ensurePaymentLinkStockSheet_();if(typeof expirePaymentLinkReservations_==='function')expirePaymentLinkReservations_();ensureWalletSheets_();var sheetNames=Object.keys(TC_ADMIN_SHEETS),tables={};sheetNames.forEach(function(name){var rows=getRows_(TC_CONFIG.SHEETS[name]||name);tables[name]={idField:TC_ADMIN_SHEETS[name],columns:rows.length?Object.keys(rows[0]):getSheetHeaders_(name),rows:rows.slice(-500).reverse()};});return{admin:publicUser_(admin),tables:tables,metrics:{shoppers:(tables.Users?.rows||[]).filter(function(r){return String(r.Role||'').toUpperCase()!=='ADMIN';}).length,orders:(tables.Orders?.rows||[]).length,pendingOrders:(tables.Orders?.rows||[]).filter(function(r){return String(r.Status||'').toUpperCase()==='PENDING_PAYMENT';}).length,paidOrders:(tables.Orders?.rows||[]).filter(function(r){return ['PAID','PROCESSING','DELIVERED'].indexOf(String(r.Status||'').toUpperCase())>=0;}).length,revenue:(tables.Payments?.rows||[]).filter(function(r){return String(r.Status||'').toUpperCase()==='VERIFIED';}).reduce(function(s,r){return s+Number(r.Amount||0);},0)}};}
function adminTable_(data){var admin=adminAuthenticate_(data.token),sheet=cleanText_(data.sheet,60),idField=TC_ADMIN_SHEETS[sheet];require_(idField,'Unknown ERP sheet.');var rows=getRows_(TC_CONFIG.SHEETS[sheet]||sheet);return{table:{idField:idField,columns:rows.length?Object.keys(rows[0]):getSheetHeaders_(sheet),rows:rows.slice(-500).reverse()}};}
function adminUpdateRow_(data){var admin=adminAuthenticate_(data.token),sheetName=cleanText_(data.sheet,60),idField=TC_ADMIN_SHEETS[sheetName],id=cleanText_(data.id,200),patch=data.patch||{};require_(idField,'Unknown ERP sheet.');require_(id,'Row ID is required.');var allowed=TC_ADMIN_EDITABLE[sheetName]||[];var clean={};Object.keys(patch).forEach(function(key){if(allowed.indexOf(key)>=0)clean[key]=cleanText_(patch[key],10000);});require_(Object.keys(clean).length>0,'This record is managed automatically.');require_(findOne_(sheetName,idField,id),'Record not found.');require_(updateRowById_(sheetName,idField,id,clean),'Record not found.');appendAudit_(admin.UserID,'UPDATE',sheetName,id,clean);return{ok:true,row:findOne_(sheetName,idField,id)};}
function adminAddPaymentLinkStock_(data){var admin=adminAuthenticate_(data.token);ensurePaymentLinkStockSheet_();var denomination=Number(data.denomination),link=cleanText_(data.link,2000),label=cleanText_(data.label||'Pay securely',100),providerLinkId=cleanText_(data.providerLinkId||'',200);require_([500,1000,1500,2000].indexOf(denomination)>=0,'Invalid denomination.');require_(/^https:\/\//i.test(link),'Payment link must use HTTPS.');var existing=getRows_(TC_CONFIG.SHEETS.PAYMENT_LINK_STOCK).some(function(r){return String(r.Link||'').trim()===link;});require_(!existing,'This payment link is already stocked.');var now=isoNow_(),id=newId_('TCPLS');appendRowObject_(TC_CONFIG.SHEETS.PAYMENT_LINK_STOCK,{PaymentLinkStockID:id,Denomination:denomination,Link:link,Label:label,Status:'AVAILABLE',OrderID:'',PaymentLinkID:'',ProviderLinkID:providerLinkId,ReservedAt:'',ExpiresAt:'',CreatedAt:now,UpdatedAt:now});appendAudit_(admin.UserID,'PAYMENT_LINK_STOCKED','PaymentLinkStock',id,{denomination:denomination,providerLinkId:providerLinkId});return{stock:findOne_(TC_CONFIG.SHEETS.PAYMENT_LINK_STOCK,'PaymentLinkStockID',id)};}
function adminCreatePaymentLink_(data){adminAuthenticate_(data.token);throw new Error('Payment links are now assigned automatically from stock.');}
function adminPaymentLinkRequest_(data){adminAuthenticate_(data.token);throw new Error('Payment-link requests are processed automatically from stocked links.');}
function adminConfirmPayment_(data){adminAuthenticate_(data.token);throw new Error('Payment verification is automatic. Manual confirmation is disabled.');}
function adminSendVoucher_(data){var admin=adminAuthenticate_(data.token),orderId=cleanText_(data.orderId,100),code=cleanText_(data.code,500),pin=cleanText_(data.pin||'',200),productId=cleanText_(data.productId||'',100),sendEmail=String(data.sendEmail||'true').toLowerCase()!=='false',order=findOne_(TC_CONFIG.SHEETS.ORDERS,'OrderID',orderId);require_(order&&code,'Order and voucher code are required.');require_(String(order.Status||'').toUpperCase()==='PAID','Payment must be verified before sending the voucher.');var user=findOne_(TC_CONFIG.SHEETS.USERS,'UserID',order.UserID);require_(user,'Shopper not found.');var already=getRows_(TC_CONFIG.SHEETS.VOUCHERS).some(function(v){return String(v.OrderID)===String(orderId)&&String(v.Status||'').toUpperCase()==='DELIVERED';});require_(!already,'Voucher has already been delivered for this order.');var now=isoNow(),id=newId_('TCVOU');appendRowObject_(TC_CONFIG.SHEETS.VOUCHERS,{VoucherID:id,ProductID:productId,OrderID:orderId,Code:code,Pin:pin,Status:'DELIVERED',IssuedAt:now,DeliveredAt:now});updateRowById_(TC_CONFIG.SHEETS.ORDERS,'OrderID',orderId,{Status:'DELIVERED',UpdatedAt:now});appendRowObject_(TC_CONFIG.SHEETS.NOTIFICATIONS,{NotificationID:newId_('TCNOT'),UserID:user.UserID,Type:'VOUCHER',Title:'Voucher delivered',Message:'Your voucher is ready.',ReadAt:'',CreatedAt:now});if(sendEmail&&typeof sendVoucherEmails_==='function')sendVoucherEmails_(order,user,code,pin);appendAudit_(admin.UserID,'VOUCHER_SENT','Order',orderId,{voucherId:id});return{voucher:findOne_(TC_CONFIG.SHEETS.VOUCHERS,'VoucherID',id),order:findOne_(TC_CONFIG.SHEETS.ORDERS,'OrderID',orderId)};}
function adminConfirmOrder_(data){adminAuthenticate_(data.token);throw new Error('Order status is managed automatically.');}
