/** Persistent shopping cart service. Voucher values are fixed to four choices. */
var TC_DENOMINATIONS=[500,1000,1500,2000];
function normalizeDenomination_(value,fallback){var amount=value===undefined||value===null||value===''?Number(fallback||0):Number(value);require_(TC_DENOMINATIONS.indexOf(amount)>=0,'Choose ₹500, ₹1,000, ₹1,500 or ₹2,000.');return amount;}
var CartService={
 getCart:function(data){var user=authenticate_(data.token);var rows=getRows_(TC_CONFIG.SHEETS.CART).filter(function(r){return String(r.UserID)===String(user.UserID)&&Number(r.Quantity||0)>0;});return{items:rows};},
 addItem:function(data){var user=authenticate_(data.token),productId=cleanText_(data.productId||'',80),quantity=Number(data.quantity||1);require_(productId&&isFinite(quantity)&&Math.floor(quantity)===quantity&&quantity>=1&&quantity<=9999,'Valid product and quantity are required.');var product=findOne_(TC_CONFIG.SHEETS.PRODUCTS,'ProductID',productId);if(!product||String(product.Active).toUpperCase()==='FALSE')throw new Error('Product unavailable.');if(String(product.InventoryStatus||'AVAILABLE').toUpperCase()==='OUT_OF_STOCK')throw new Error('Product is out of stock.');var denomination=normalizeDenomination_(data.denomination,1000),rows=getRows_(TC_CONFIG.SHEETS.CART),existing=rows.find(function(r){return String(r.UserID)===String(user.UserID)&&String(r.ProductID)===productId&&Number(r.Denomination||0)===denomination;});if(existing){updateRowById_(TC_CONFIG.SHEETS.CART,'CartID',existing.CartID,{Quantity:Number(existing.Quantity||0)+quantity,UpdatedAt:isoNow_()});}else appendRowObject_(TC_CONFIG.SHEETS.CART,{CartID:newId_('TCART'),UserID:user.UserID,ProductID:productId,Quantity:quantity,Denomination:denomination,CreatedAt:isoNow_(),UpdatedAt:isoNow_()});return this.getCart(data);},
 updateItem:function(data){var user=authenticate_(data.token),itemId=cleanText_(data.cartItemId||'',80),quantity=Number(data.quantity);var item=findOne_(TC_CONFIG.SHEETS.CART,'CartID',itemId);require_(item&&String(item.UserID)===String(user.UserID),'Cart item not found.');require_(isFinite(quantity)&&Math.floor(quantity)===quantity&&quantity>=1&&quantity<=9999,'Quantity must be a positive whole number.');updateRowById_(TC_CONFIG.SHEETS.CART,'CartID',itemId,{Quantity:quantity,UpdatedAt:isoNow_()});return this.getCart(data);},
 removeItem:function(data){var user=authenticate_(data.token),itemId=cleanText_(data.cartItemId||'',80),item=findOne_(TC_CONFIG.SHEETS.CART,'CartID',itemId);require_(item&&String(item.UserID)===String(user.UserID),'Cart item not found.');updateRowById_(TC_CONFIG.SHEETS.CART,'CartID',itemId,{Quantity:0,UpdatedAt:isoNow_()});return this.getCart(data);}
};
