function authorizeTrustedCircleEmail(){var quota=MailApp.getRemainingDailyQuota();return{authorized:true,remainingDailyQuota:quota};}

function testTrustedCircleEmail(){
  var recipient=normalizeEmail_(getScriptProperties_().getProperty('TEST_EMAIL')||TC_CONFIG.PRIMARY_EMAIL||TC_CONFIG.ADMIN_EMAIL);
  require_(isValidEmail_(recipient),'Set TEST_EMAIL in Script Properties to a valid email address.');
  var quotaBefore=MailApp.getRemainingDailyQuota();
  var subject='Trusted Circle · Email delivery test';
  var body='This is a Trusted Circle email delivery test. If you received this message, Apps Script email authorization and delivery are working.';
  var started=isoNow_();
  try{
    MailApp.sendEmail({to:recipient,subject:subject,body:body,htmlBody:'<div style="font-family:Arial,sans-serif"><h2>Trusted Circle</h2><p>Email delivery test successful.</p><p>Started: '+started+'</p></div>',name:'Trusted Circle',replyTo:TC_EMAIL.INFO});
    var quotaAfter=MailApp.getRemainingDailyQuota();
    console.log(JSON.stringify({ok:true,to:recipient,quotaBefore:quotaBefore,quotaAfter:quotaAfter,started:started,completedAt:isoNow_()}));
    return {ok:true,to:recipient,quotaBefore:quotaBefore,quotaAfter:quotaAfter,started:started,completedAt:isoNow_()};
  }catch(error){
    console.error(JSON.stringify({ok:false,to:recipient,quotaBefore:quotaBefore,error:String(error&&error.message||error),stack:String(error&&error.stack||'')}));
    throw new Error('Trusted Circle email test failed: '+String(error&&error.message||error));
  }
}

function doGet(e){return handleRequest_(e,false);}
function doPost(e){return handleRequest_(e,true);}
function handleRequest_(e,isPost){try{let input={};if(isPost){const body=e&&e.postData?String(e.postData.contents||''):'';const type=e&&e.postData?String(e.postData.type||'').toLowerCase():'';const parameters=e&&e.parameter?e.parameter:{};const hasParameters=Object.keys(parameters).length>0;if(body&&(type.indexOf('application/json')>=0||looksLikeJson_(body)))input=safeJsonParse_(body)||{};else if(hasParameters)input=parameters;else if(body)input=parseUrlEncoded_(body);}else input=e&&e.parameter?e.parameter:{};const action=cleanText_(input.action||'health',50);if(action!=='health')require_(input&&typeof input==='object'&&Object.keys(input).length>0,'Invalid request.');const result=routeAction_(action,input);if(typeof appendRequestActivity_==='function')appendRequestActivity_(input,action,true,'');return jsonResponse_(success_(result));}catch(err){try{if(typeof appendRequestActivity_==='function')appendRequestActivity_(typeof input==='object'?input:{},typeof action==='string'?action:'unknown',false,err.message||'Request failed.');}catch(ignore){}console.error(err&&err.stack?err.stack:err);return jsonResponse_(failure_('REQUEST_FAILED',err.message||'Request failed.'));}}
function looksLikeJson_(value){const text=String(value||'').trim();return text.charAt(0)==='{'||text.charAt(0)==='[';}
function parseUrlEncoded_(body){const result={};String(body||'').split('&').forEach(function(pair){if(!pair)return;const index=pair.indexOf('=');const rawKey=index>=0?pair.substring(0,index):pair;const rawValue=index>=0?pair.substring(index+1):'';result[decodeURIComponent(rawKey.replace(/\+/g,' '))]=decodeURIComponent(rawValue.replace(/\+/g,' '));});return result;}
function routeAction_(action,input){switch(action){case'health':return{service:TC_CONFIG.APP_NAME+' API',status:'ok',version:'2.5.0'};case'setupBackend':return setupBackend();case'requestOtp':return requestOtp_(input);case'verifyOtp':return verifyOtpAndLogin_(input);case'adminLogin':return adminLogin_(input);case'adminDashboard':return adminDashboardFast_(input);case'adminTable':return adminTable_(input);case'adminUpdateRow':return adminUpdateRow_(input);case'adminEditAnyRow':return adminEditAnyRow_(input);case'adminWorklist':return adminWorklist_(input);case'adminWorklistAction':return adminWorklistAction_(input);case'adminFindUserForRemoval':return adminFindUserForRemoval_(input);case'adminRemoveUser':return adminRemoveUser_(input);case'adminAddPaymentLinkStock':return adminAddPaymentLinkStock_(input);case'adminAddPaymentLinkStockBulk':return adminAddPaymentLinkStockBulk_(input);case'adminCreatePaymentLink':return adminCreatePaymentLink_(input);case'adminPaymentLinkRequest':return adminPaymentLinkRequest_(input);case'adminConfirmPayment':return adminConfirmPayment_(input);case'adminVerifyPayment':return adminVerifyPayment_(input);case'adminSendVoucher':return adminSendVoucher_(input);case'adminUpdateOrder':return adminConfirmOrder_(input);case'requestPaymentLink':return requestPaymentLink_(input);case'createInvoicePdf':return createInvoicePdf_(input);case'paymentWebhook':return paymentWebhook_(input);case'wallet':return walletData_(input);case'redeemWallet':return requestWalletRedemption_(input);case'logout':return{loggedOut:revokeSession_(input.token)};case'me':return publicUser_(authenticate_(input.token));case'profileUpdate':return updateProfile_(input);case'catalog':return catalogFast_();case'brands':return ProductService.listBrands(input);case'products':return ProductService.listProducts(input);case'product':return ProductService.getProduct(input);case'cart':return CartService.getCart(input);case'cartAdd':return CartService.addItem(input);case'cartUpdate':return CartService.updateItem(input);case'cartDenomination':return CartService.updateDenomination(input);case'cartRemove':return CartService.removeItem(input);case'placeOrder':return OrderService.placeOrder(input);case'orders':return OrderService.listOrders(input);case'orderDetails':return OrderService.getOrderDetails(input);case'cancelOrder':return OrderService.cancelOrder(input);default:throw new Error('Unknown API action.');}}
function isReadOnlyApiAction_(action){return['adminDashboard','adminTable','adminWorklist','adminFindUserForRemoval','wallet','me','brands','products','product','cart','orders','orderDetails'].indexOf(String(action||''))>=0;}
function appendRequestActivity_(input,action,success,errorMessage){try{if(action==='health')return;if(success&&isReadOnlyApiAction_(action))return;ensureColumns_('AuditLogs',['ActorType','Email','Success','Method','Error']);var userId='',email=normalizeEmail_(input.email||'');if(input.token){try{var user=authenticate_(input.token);userId=user.UserID;email=email||normalizeEmail_(user.Email);}catch(ignore){}}else if(email){var existing=getUserByEmail_(email);if(existing)userId=existing.UserID;}var actor=userId&&email===normalizeEmail_(getAdminEmail_())?'ADMIN':(userId?'USER':'ANONYMOUS'),safe={};Object.keys(input||{}).forEach(function(k){if(['token','password','otp','Otp','code','pin','OtpHash','TokenHash'].indexOf(k)<0)safe[k]=input[k];});safe.error=errorMessage||'';appendRowObject_('AuditLogs',{AuditID:newId_('TCAUD'),UserID:userId,Action:'API_'+String(action).toUpperCase(),Entity:'API',EntityID:String(input.orderId||input.recordId||input.sheet||''),Metadata:JSON.stringify(safe),CreatedAt:isoNow_(),ActorType:actor,Email:email,Success:success?'TRUE':'FALSE',Method:String(input.method||'API'),Error:errorMessage||''});}catch(ignore){}}
function verifyOtpAndLogin_(input){verifyOtp_(input);const email=normalizeEmail_(input.email);const user=createOrGetUser_(email,input.name);require_(String(user.Status||'ACTIVE').toUpperCase()==='ACTIVE','This shopper account is not active.');updateRowById_(TC_CONFIG.SHEETS.USERS,'UserID',user.UserID,{LastLoginAt:isoNow_(),UpdatedAt:isoNow_()});const refreshedUser=getUserByEmail_(email);return{user:publicUser_(refreshedUser),session:issueSession_(refreshedUser)};}
function issueSession_(user){const rawToken=Utilities.getUuid()+'.'+Utilities.getUuid();const sessionId=newId_('TCSES');const expires=new Date(Date.now()+getSessionTtl_()*1000);appendRowObject_(TC_CONFIG.SHEETS.SESSIONS,{SessionID:sessionId,UserID:user.UserID,TokenHash:hash_(rawToken),ExpiresAt:expires.toISOString(),CreatedAt:isoNow_(),RevokedAt:'',Status:'ACTIVE'});return{token:rawToken,expiresAt:expires.toISOString()};}
function authenticate_(token){require_(token,'Authentication required.');const tokenHash=hash_(String(token));const rows=getRows_(TC_CONFIG.SHEETS.SESSIONS);for(let i=rows.length-1;i>=0;i--){const row=rows[i];if(row.Status==='ACTIVE'&&constantTimeEquals_(String(row.TokenHash),tokenHash)){require_(new Date(row.ExpiresAt).getTime()>Date.now(),'Session expired.');const user=findOne_(TC_CONFIG.SHEETS.USERS,'UserID',row.UserID);require_(user&&user.Status==='ACTIVE','User account is inactive.');return user;}}throw new Error('Invalid session.');}
function revokeSession_(token){const tokenHash=hash_(String(token||''));const rows=getRows_(TC_CONFIG.SHEETS.SESSIONS);for(let i=rows.length-1;i>=0;i--){if(constantTimeEquals_(String(rows[i].TokenHash),tokenHash)&&rows[i].Status==='ACTIVE'){updateRowById_(TC_CONFIG.SHEETS.SESSIONS,'SessionID',rows[i].SessionID,{Status:'REVOKED',RevokedAt:isoNow_()});return true;}}return false;}
