function doGet(e){return handleRequest_(e,false);}
function doPost(e){return handleRequest_(e,true);}
function handleRequest_(e,isPost){try{let input={};if(isPost){const body=e&&e.postData?String(e.postData.contents||''):'';const type=e&&e.postData?String(e.postData.type||'').toLowerCase():'';const parameters=e&&e.parameter?e.parameter:{};const hasParameters=Object.keys(parameters).length>0;if(body&&(type.indexOf('application/json')>=0||looksLikeJson_(body)))input=safeJsonParse_(body)||{};else if(hasParameters)input=parameters;else if(body)input=parseUrlEncoded_(body);}else input=e&&e.parameter?e.parameter:{};require_(input&&typeof input==='object'&&Object.keys(input).length>0,'Invalid request.');const action=cleanText_(input.action||'health',50);return jsonResponse_(success_(routeAction_(action,input)));}catch(err){console.error(err&&err.stack?err.stack:err);return jsonResponse_(failure_('REQUEST_FAILED',err.message||'Request failed.'));}}
function looksLikeJson_(value){const text=String(value||'').trim();return text.charAt(0)==='{'||text.charAt(0)==='[';}
function parseUrlEncoded_(body){const result={};String(body||'').split('&').forEach(function(pair){if(!pair)return;const index=pair.indexOf('=');const rawKey=index>=0?pair.substring(0,index):pair;const rawValue=index>=0?pair.substring(index+1):'';result[decodeURIComponent(rawKey.replace(/\+/g,' '))]=decodeURIComponent(rawValue.replace(/\+/g,' '));});return result;}
function routeAction_(action,input){switch(action){case'health':return{service:TC_CONFIG.APP_NAME+' API',status:'ok',version:'2.2.0'};case'setupBackend':return setupBackend();case'requestOtp':return requestOtp_(input);case'verifyOtp':return verifyOtpAndLogin_(input);case'adminLogin':return adminLogin_(input);case'adminDashboard':return adminDashboard_(input);case'adminUpdateRow':return adminUpdateRow_(input);case'adminCreatePaymentLink':return adminCreatePaymentLink_(input);case'adminPaymentLinkRequest':return adminPaymentLinkRequest_(input);case'adminConfirmPayment':return adminConfirmPayment_(input);case'adminSendVoucher':return adminSendVoucher_(input);case'adminUpdateOrder':return adminConfirmOrder_(input);case'requestPaymentLink':return requestPaymentLink_(input);case'createInvoicePdf':return createInvoicePdf_(input);case'logout':return{loggedOut:revokeSession_(input.token)};case'me':return publicUser_(authenticate_(input.token));case'profileUpdate':return updateProfile_(input);case'brands':return ProductService.listBrands(input);case'products':return ProductService.listProducts(input);case'product':return ProductService.getProduct(input);case'cart':return CartService.getCart(input);case'cartAdd':return CartService.addItem(input);case'cartUpdate':return CartService.updateItem(input);case'cartDenomination':return CartService.updateDenomination(input);case'cartRemove':return CartService.removeItem(input);case'placeOrder':return OrderService.placeOrder(input);case'orders':return OrderService.listOrders(input);default:throw new Error('Unknown API action.');}}
function verifyOtpAndLogin_(input){verifyOtp_(input);const email=normalizeEmail_(input.email);const user=createOrGetUser_(email,input.name);updateRowById_(TC_CONFIG.SHEETS.USERS,'UserID',user.UserID,{LastLoginAt:isoNow_(),UpdatedAt:isoNow_()});const refreshedUser=getUserByEmail_(email);return{user:publicUser_(refreshedUser),session:issueSession_(refreshedUser)};}
function issueSession_(user){const rawToken=Utilities.getUuid()+'.'+Utilities.getUuid();const sessionId=newId_('TCSES');const expires=new Date(Date.now()+getSessionTtl_()*1000);appendRowObject_(TC_CONFIG.SHEETS.SESSIONS,{SessionID:sessionId,UserID:user.UserID,TokenHash:hash_(rawToken),ExpiresAt:expires.toISOString(),CreatedAt:isoNow_(),RevokedAt:'',Status:'ACTIVE'});return{token:rawToken,expiresAt:expires.toISOString()};}
function authenticate_(token){require_(token,'Authentication required.');const tokenHash=hash_(String(token));const rows=getRows_(TC_CONFIG.SHEETS.SESSIONS);for(let i=rows.length-1;i>=0;i--){const row=rows[i];if(row.Status==='ACTIVE'&&constantTimeEquals_(String(row.TokenHash),tokenHash)){require_(new Date(row.ExpiresAt).getTime()>Date.now(),'Session expired.');const user=findOne_(TC_CONFIG.SHEETS.USERS,'UserID',row.UserID);require_(user&&user.Status==='ACTIVE','User account is inactive.');return user;}}throw new Error('Invalid session.');}
function revokeSession_(token){const tokenHash=hash_(String(token||''));const rows=getRows_(TC_CONFIG.SHEETS.SESSIONS);for(let i=rows.length-1;i>=0;i--){if(constantTimeEquals_(String(rows[i].TokenHash),tokenHash)&&rows[i].Status==='ACTIVE'){updateRowById_(TC_CONFIG.SHEETS.SESSIONS,'SessionID',rows[i].SessionID,{Status:'REVOKED',RevokedAt:isoNow_()});return true;}}return false;}
