/** Trusted Circle transactional email service. Only OTP, payment-link and voucher emails go to shoppers. */
var TC_EMAIL={PRIMARY:'trustedcircle2026@gmail.com',INFO:'info@trustedcircle.in'};
function emailEscape_(value){return escapeHtml_(String(value===undefined||value===null?'':value));}
function emailMoney_(value){return '₹'+Number(value||0).toLocaleString('en-IN',{maximumFractionDigits:2});}
function emailAliasList_(){try{return GmailApp.getAliases().map(function(a){return normalizeEmail_(a);});}catch(e){return [];}}
function sendTransactionalEmail_(to,subject,htmlBody,textBody){if(!isValidEmail_(to))return false;var from=normalizeEmail_(getScriptProperties_().getProperty('EMAIL_FROM')||TC_EMAIL.PRIMARY),options={htmlBody:htmlBody,body:textBody,name:'Trusted Circle',replyTo:TC_EMAIL.INFO},aliases=emailAliasList_();if(aliases.indexOf(from)>=0)options.from=from;try{GmailApp.sendEmail(to,subject,textBody,options);return true;}catch(e){try{MailApp.sendEmail({to:to,subject:subject,htmlBody:htmlBody,body:textBody,name:'Trusted Circle',replyTo:TC_EMAIL.INFO});return true;}catch(ignore){console.error('Transactional email failed: '+e.message);return false;}}}
function sendDualTransactionalEmail_(subject,htmlBody,textBody,userEmail){return{userSent:sendTransactionalEmail_(userEmail,subject,htmlBody,textBody),infoSent:sendTransactionalEmail_(TC_EMAIL.INFO,'[Trusted Circle] '+subject,htmlBody,textBody)};}
function orderEmailItems_(items){return(items||[]).map(function(i){var product=findOne_(TC_CONFIG.SHEETS.PRODUCTS,'ProductID',i.ProductID)||{},brand=findOne_(TC_CONFIG.SHEETS.BRANDS,'BrandID',product.BrandID)||{};return{title:product.Title||'Gift voucher',brand:brand.Name||'',qty:Number(i.Quantity||1),value:Number(i.Denomination||i.FaceValue||0),total:Number(i.Total||0)};});}
function orderEmailDetails_(order,user,items){var lines=orderEmailItems_(items),rows=lines.map(function(i){return '<tr><td style="padding:10px;border-bottom:1px solid #edf1ee"><b>'+emailEscape_(i.brand)+'</b><br><span style="color:#5f6b64">'+emailEscape_(i.title)+'</span></td><td style="padding:10px;border-bottom:1px solid #edf1ee">'+i.qty+'</td><td style="padding:10px;border-bottom:1px solid #edf1ee">'+emailMoney_(i.value)+'</td><td style="padding:10px;border-bottom:1px solid #edf1ee">'+emailMoney_(i.total)+'</td></tr>';}).join('');return '<div style="font-family:Arial,sans-serif;max-width:680px;margin:auto;color:#18241e"><div style="padding:24px;border-radius:16px;background:#173c2a;color:#fff"><div style="font-size:22px;font-weight:800">Trusted Circle</div><div style="margin-top:5px;opacity:.8">Secure digital gifting</div></div><div style="padding:24px"><p style="font-size:17px">Hi '+emailEscape_(user&&user.Name||'there')+',</p><p>Order <b>'+emailEscape_(order.OrderNumber)+'</b> · '+emailMoney_(order.Total)+'</p>'+(rows?'<table style="border-collapse:collapse;width:100%;margin-top:18px"><tr><th align="left" style="padding:10px">Voucher</th><th align="left" style="padding:10px">Qty</th><th align="left" style="padding:10px">Value</th><th align="left" style="padding:10px">Total</th></tr>'+rows+'</table>':'')+'</div><div style="padding:18px 24px;background:#f5f8f6;color:#68736d;font-size:12px">Trusted Circle · info@trustedcircle.in</div></div>';}
function sendOrderPlacedEmails_(){return false;}
function sendPaymentStatusEmails_(){return false;}
function sendPaymentLinkRequestEmails_(){return false;}
function sendPaymentLinkEmails_(order,user,link,label){var safeLink=emailEscape_(link),html=orderEmailDetails_(order,user,[])+'<div style="padding:0 24px 24px"><div style="padding:18px;border:1px solid #dce9e0;border-radius:14px;background:#f5fbf7"><h2 style="margin:0 0 8px">Your payment link is ready</h2><p style="margin:0 0 16px">Hi '+emailEscape_(user&&user.Name||'there')+', your payment link for this order is ready.</p><a href="'+safeLink+'" style="display:inline-block;padding:13px 20px;background:#173c2a;color:#fff;text-decoration:none;border-radius:10px;font-weight:700">'+emailEscape_(label||'Make Payment')+'</a></div></div>',text='Hi '+(user&&user.Name||'there')+', your Trusted Circle payment link is ready: '+link;return sendDualTransactionalEmail_('Your payment link is ready · '+order.OrderNumber,html,text,user.Email);}
function sendVoucherEmails_(order,user,code,pin){var items=getRows_(TC_CONFIG.SHEETS.ORDER_ITEMS).filter(function(r){return String(r.OrderID)===String(order.OrderID);}),lines=orderEmailItems_(items),cards=lines.map(function(i){return '<div style="margin:12px 0;padding:16px;border:1px solid #dce9e0;border-radius:14px;background:#fbfdfb"><div style="font-weight:800">'+emailEscape_(i.brand)+'</div><div style="margin-top:3px;color:#65716a">'+emailEscape_(i.title)+' · ₹'+Number(i.value||0).toLocaleString('en-IN')+'</div></div>';}).join(''),html=orderEmailDetails_(order,user,items)+'<div style="padding:0 24px 24px"><div style="padding:18px;border-radius:14px;background:#eef8f1"><h2 style="margin:0 0 8px">Your voucher is ready 🎁</h2><p style="margin:0 0 14px">Hi '+emailEscape_(user&&user.Name||'there')+', your digital voucher is ready.</p>'+cards+'<div style="padding-top:10px;border-top:1px solid #cfe2d4"><b>Voucher Code</b><div style="font-size:20px;font-weight:800;letter-spacing:1px;margin-top:6px">'+emailEscape_(code)+'</div>'+(pin?'<div style="margin-top:10px"><b>PIN</b><div style="font-size:18px;font-weight:800">'+emailEscape_(pin)+'</div></div>':'')+'</div></div></div>',text='Hi '+(user&&user.Name||'there')+', your Trusted Circle voucher for '+order.OrderNumber+' is ready. Code: '+code+(pin?' | PIN: '+pin:'');return sendDualTransactionalEmail_('Your voucher is ready 🎁 · '+order.OrderNumber,html,text,user.Email);}
