/** Trusted Circle transactional email service. */
var TC_EMAIL={PRIMARY:'trustedcircle2026@gmail.com',INFO:'info@trustedcircle.in'};
function emailEscape_(value){return escapeHtml_(String(value===undefined||value===null?'':value));}
function emailMoney_(value){return '₹'+Number(value||0).toLocaleString('en-IN',{maximumFractionDigits:2});}
function emailAliasList_(){try{return GmailApp.getAliases().map(function(a){return normalizeEmail_(a);});}catch(e){return [];}}
function sendTransactionalEmail_(to,subject,htmlBody,textBody){if(!isValidEmail_(to))return false;var from=normalizeEmail_(getScriptProperties_().getProperty('EMAIL_FROM')||TC_EMAIL.PRIMARY);var options={htmlBody:htmlBody,body:textBody,name:'Trusted Circle',replyTo:TC_EMAIL.INFO};var aliases=emailAliasList_();if(aliases.indexOf(from)>=0)options.from=from;try{GmailApp.sendEmail(to,subject,textBody,options);return true;}catch(e){try{MailApp.sendEmail({to:to,subject:subject,htmlBody:htmlBody,body:textBody,name:'Trusted Circle',replyTo:TC_EMAIL.INFO});return true;}catch(ignore){console.error('Transactional email failed: '+e.message);return false;}}}
function sendDualTransactionalEmail_(subject,htmlBody,textBody,userEmail){var userSent=sendTransactionalEmail_(userEmail,subject,htmlBody,textBody);var infoSubject='[Trusted Circle] '+subject;var infoSent=sendTransactionalEmail_(TC_EMAIL.INFO,infoSubject,htmlBody,textBody);return{userSent:userSent,infoSent:infoSent};}
function orderEmailDetails_(order,user,items){var rows=(items||[]).map(function(i){return '<tr><td style="padding:7px;border-bottom:1px solid #eee">'+emailEscape_(i.title||i.ProductID||'Voucher')+'</td><td style="padding:7px;border-bottom:1px solid #eee">'+Number(i.Quantity||1)+'</td><td style="padding:7px;border-bottom:1px solid #eee">'+emailMoney_(i.Denomination||i.FaceValue)+'</td><td style="padding:7px;border-bottom:1px solid #eee">'+emailMoney_(i.Total)+'</td></tr>';}).join('');return '<div style="font-family:Arial,sans-serif;color:#172033"><h2>Trusted Circle</h2><p><b>Order:</b> '+emailEscape_(order.OrderNumber)+'</p><p><b>Customer:</b> '+emailEscape_(user&&user.Name||'')+' &lt;'+emailEscape_(user&&user.Email||'')+'&gt;</p><p><b>Status:</b> '+emailEscape_(order.Status)+'</p><p><b>Total:</b> '+emailMoney_(order.Total)+'</p>'+(rows?'<table style="border-collapse:collapse;width:100%"><tr><th align="left" style="padding:7px">Item</th><th align="left" style="padding:7px">Qty</th><th align="left" style="padding:7px">Denomination</th><th align="left" style="padding:7px">Total</th></tr>'+rows+'</table>':'')+'<p style="margin-top:20px">Trusted Circle Operations</p></div>';}
function sendOrderPlacedEmails_(order,user,items){var html=orderEmailDetails_(order,user,items)+'<p>Your order has been received and is currently <b>pending payment</b>.</p>';var text='Trusted Circle order '+order.OrderNumber+' received. Status: '+order.Status+'. Total: '+emailMoney_(order.Total)+'.';return sendDualTransactionalEmail_('Order received — '+order.OrderNumber,html,text,user.Email);}
function sendPaymentStatusEmails_(order,user,items,oldStatus,newStatus){var html=orderEmailDetails_(order,user,items)+'<p>Payment/order status changed from <b>'+emailEscape_(oldStatus)+'</b> to <b>'+emailEscape_(newStatus)+'</b>.</p>';var text='Trusted Circle order '+order.OrderNumber+' status changed from '+oldStatus+' to '+newStatus+'. Total: '+emailMoney_(order.Total)+'.';return sendDualTransactionalEmail_('Payment / order status — '+order.OrderNumber,html,text,user.Email);}
function sendPaymentLinkEmails_(order,user,link,label){var safeLink=emailEscape_(link);var html=orderEmailDetails_(order,user,[])+'<p>Your requested payment link is ready.</p><p><a href="'+safeLink+'" style="display:inline-block;padding:12px 18px;background:#111;color:#fff;text-decoration:none;border-radius:8px">'+emailEscape_(label||'Make Payment')+'</a></p><p>Payment link: '+safeLink+'</p>';var text='Your Trusted Circle payment link for '+order.OrderNumber+' is ready: '+link;return sendDualTransactionalEmail_('Payment link ready — '+order.OrderNumber,html,text,user.Email);}
function sendPaymentLinkRequestEmails_(order,user,requestId){var html=orderEmailDetails_(order,user,[])+'<p>We have received your request for a payment link.</p><p><b>Request ID:</b> '+emailEscape_(requestId)+'</p><p>Our operations team will send the payment link after it is created.</p>';var text='Payment link requested for '+order.OrderNumber+'. Request ID: '+requestId+'.';return sendDualTransactionalEmail_('Payment link requested — '+order.OrderNumber,html,text,user.Email);}
function sendVoucherEmails_(order,user,code,pin){var html=orderEmailDetails_(order,user,[])+'<p>Your voucher has been delivered.</p><p><b>Voucher Code:</b> '+emailEscape_(code)+(pin?'<br><b>PIN:</b> '+emailEscape_(pin):'')+'</p>';var text='Voucher delivered for '+order.OrderNumber+'. Code: '+code+(pin?' | PIN: '+pin:'');return sendDualTransactionalEmail_('Voucher delivered — '+order.OrderNumber,html,text,user.Email);}
