import { useEffect,useMemo,useState } from 'react'
import { Activity,AlertTriangle,BarChart3,CheckCircle2,ChevronDown,ChevronRight,CircleDollarSign,ClipboardList,Database,Edit3,Filter,KeyRound,LayoutDashboard,Link2,LogOut,Menu,PackageCheck,Plus,RefreshCw,Search,ShieldCheck,ShoppingBag,Users,WalletCards,X } from 'lucide-react'
import { api } from './api'
import './admin-workspace.css'
import './admin-upgrade.css'

const LOGO='https://raw.githubusercontent.com/trustedcircle2026-cloud/Trusted-Circle/main/Logo%20new.jpg'
const MONEY=v=>`₹${Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`
const fmt=v=>v===null||v===undefined?'':typeof v==='object'?JSON.stringify(v):String(v)
const STATUS=v=>String(v||'').toUpperCase()
const LABEL={Users:'Shoppers',Orders:'Orders',OrderItems:'Order Items',Payments:'Payments',PaymentLinks:'Payment Links',PaymentLinkRequests:'Link Requests',PaymentLinkStock:'Payment Link Stock',Vouchers:'Vouchers',Products:'Products',Brands:'Brands',Cart:'Cart',Notifications:'Notifications',OTP:'OTP Logs',UserSessions:'Sessions',AuditLogs:'Web Activity',CashbackWallet:'Cashback Wallet',CashbackTransactions:'Cashback History',WalletRedemptions:'Cashback Payouts'}
const DATA_SHEETS=['Users','Orders','OrderItems','Payments','PaymentLinks','PaymentLinkRequests','PaymentLinkStock','Vouchers','Products','Brands','Cart','Notifications','OTP','UserSessions','AuditLogs','CashbackWallet','CashbackTransactions','WalletRedemptions']
const MENU=[
 {section:'COMMAND',items:[['dashboard','Command Center',LayoutDashboard],['work','Work Queue',ClipboardList]]},
 {section:'SALES',items:[['Orders','Orders',ShoppingBag],['Payments','Payments',CircleDollarSign],['PaymentLinks','Payment Links',Link2],['PaymentLinkStock','Link Stock',Database]]},
 {section:'CATALOG',items:[['Products','Products',PackageCheck],['Brands','Brands',ShoppingBag]]},
 {section:'FINANCE',items:[['WalletRedemptions','Cashback Payouts',WalletCards],['CashbackWallet','Cashback Wallet',WalletCards],['CashbackTransactions','Cashback History',Activity]]},
 {section:'CUSTOMERS',items:[['Users','Shoppers',Users]]},
 {section:'INSIGHTS',items:[['reports','Reports',BarChart3],['all-data','All Data',Database]]},
 {section:'SYSTEM',items:[['AuditLogs','Web Activity',Activity],['Notifications','Notifications',Activity],['OTP','OTP Logs',KeyRound],['UserSessions','Sessions',ShieldCheck]]}
]

export default function AdminWorkspace(){
 const[token,setToken]=useState(()=>localStorage.getItem('tc_erp_session')||''),[user,setUser]=useState(null),[login,setLogin]=useState({email:'trustedcircle2026@gmail.com',password:''}),[error,setError]=useState(''),[loading,setLoading]=useState(false),[data,setData]=useState(null),[active,setActive]=useState('dashboard'),[mobile,setMobile]=useState(false),[query,setQuery]=useState(''),[filter,setFilter]=useState({field:'',value:''}),[filterOpen,setFilterOpen]=useState(false),[edit,setEdit]=useState(null),[work,setWork]=useState(null),[workItems,setWorkItems]=useState([]),[stockOpen,setStockOpen]=useState(false)
 useEffect(()=>{if(!window.location.hash.replace(/^#\/?/,'').startsWith('erp'))return;const saved=localStorage.getItem('tc_erp_session');if(saved){setToken(saved);refresh(saved)}},[])
 async function refresh(t=token){setLoading(true);setError('');try{const r=await api.adminDashboard(t);setData(r);setUser(r.admin);const w=await api.adminWorklist(t);setWorkItems(w?.items||[])}catch(e){localStorage.removeItem('tc_erp_session');setToken('');setUser(null);setData(null);setError(e.message||'ERP session expired.')}finally{setLoading(false)}}
 async function openMenu(id){setActive(id);setQuery('');setFilter({field:'',value:''});setFilterOpen(false);setMobile(false);if(DATA_SHEETS.includes(id)&&!data?.tables?.[id]){setLoading(true);try{const r=await api.adminTable(token,id);setData(p=>({...p,tables:{...(p?.tables||{}),[id]:r.table}}))}catch(e){setError(e.message)}finally{setLoading(false)}}}
 async function loginSubmit(e){e.preventDefault();setLoading(true);setError('');try{const r=await api.adminLogin(login.email,login.password);localStorage.setItem('tc_erp_session',r.session.token);setToken(r.session.token);setUser(r.user);await refresh(r.session.token)}catch(e){setError(e.message||'Invalid ERP credentials.')}finally{setLoading(false)}}
 function logout(){localStorage.removeItem('tc_erp_session');setToken('');setUser(null);setData(null);window.location.hash='#/home'}
 async function applyWork(action,item,extra={}){try{await api.adminWorklistAction(token,action,item.sheet,item.recordId,extra.reason||'');setWork(null);await refresh()}catch(e){setError(e.message||'Action failed.')}}
 const tables=data?.tables||{},current=tables[active],rows=current?.rows||[]
 const filtered=useMemo(()=>rows.filter(r=>{const q=!query||Object.values(r).some(v=>fmt(v).toLowerCase().includes(query.toLowerCase()));const f=!filter.field||!filter.value||STATUS(r[filter.field])===STATUS(filter.value);return q&&f}),[rows,query,filter])
 if(!token||!user)return <Login loading={loading} error={error} login={login} setLogin={setLogin} onSubmit={loginSubmit}/>
 return <div className="tc-admin-shell"><aside className={`tc-admin-sidebar ${mobile?'open':''}`}><div className="tc-admin-brand"><img src={LOGO} alt="Trusted Circle"/><div><b>Trusted Circle</b><small>OPERATIONS ERP</small></div><button onClick={()=>setMobile(false)}><X size={17}/></button></div><div className="tc-admin-nav">{MENU.map(group=><div key={group.section}><div className="tc-admin-label">{group.section}</div>{group.items.map(([id,text,Icon])=><button key={id} className={active===id?'active':''} onClick={()=>openMenu(id)}><Icon size={16}/><span>{text}</span>{id==='work'&&workItems.length>0&&<b className="tc-admin-count">{workItems.length}</b>}{active===id&&<ChevronRight size={14}/>}</button>)}</div>)}</div><div className="tc-admin-foot"><span><i/> Live backend</span><button onClick={logout}><LogOut size={15}/> Sign out</button></div></aside><main className="tc-admin-main"><header className="tc-admin-header"><button className="tc-admin-mobile" onClick={()=>setMobile(true)}><Menu size={20}/></button><div><small>TRUSTED CIRCLE · PRIVATE ERP</small><h1>{pageTitle(active)}</h1></div><div className="tc-admin-head-actions"><button onClick={()=>refresh()} title="Refresh"><RefreshCw size={16} className={loading?'tc-spin':''}/></button><span><i/> {user.email}</span></div></header>{error&&<div className="tc-admin-alert"><AlertTriangle size={15}/><span>{error}</span><button onClick={()=>setError('')}><X size={14}/></button></div>}
 {active==='dashboard'?<CommandCenter metrics={data?.metrics||{}} workItems={workItems.length} onWork={()=>openMenu('work')} onOrders={()=>openMenu('Orders')} onStock={()=>openMenu('PaymentLinkStock')}/>:active==='work'?<WorkQueue items={workItems} onAction={setWork}/>:active==='reports'?<Reports data={data}/>:active==='all-data'?<AllData tables={tables} onOpen={openMenu}/>:active==='PaymentLinkStock'?<StockPage rows={filtered} onOpen={()=>setStockOpen(true)} onEdit={setEdit}/>:<DataPage title={pageTitle(active)} rows={filtered} columns={current?.columns||[]} idField={current?.idField} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} filterOpen={filterOpen} setFilterOpen={setFilterOpen} onEdit={setEdit} loading={loading}/>}</main>{work&&<WorkModal item={work} tables={tables} token={token} onClose={()=>setWork(null)} onAction={applyWork} onError={setError}/>} {edit&&<EditModal edit={edit} token={token} onClose={()=>setEdit(null)} onDone={async()=>{setEdit(null);await refresh()}} onError={setError}/>} {stockOpen&&<StockModal token={token} onClose={()=>setStockOpen(false)} onDone={async()=>{setStockOpen(false);await refresh()}} onError={setError}/>}</div>
}

function Login({loading,error,login,setLogin,onSubmit}){return <div className="admin-login"><div className="admin-login-panel"><div className="admin-login-logo"><img src={LOGO} alt="Trusted Circle"/></div><span className="admin-eyebrow">PRIVATE OPERATIONS</span><h2>Trusted Circle ERP</h2><p>Complete operational control for payments, vouchers, cashback and customer activity.</p><form onSubmit={onSubmit}><label>Email<input type="email" value={login.email} onChange={e=>setLogin({...login,email:e.target.value})} required/></label><label>Password<input type="password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})} required/>{error&&<div className="admin-login-error">{error}</div>}<button className="admin-primary" disabled={loading}>{loading?'Signing in…':'Enter operations ERP'}<ChevronRight size={16}/></button></form></div><div className="admin-login-side"><span>OPERATE WITH CLARITY</span><h1>Everything<br/><em>visible.</em></h1><p>Work queues, editable operational records, filters and a complete web activity trail.</p></div></div>}
function CommandCenter({metrics,workItems,onWork,onOrders,onStock}){return <section className="tc-admin-page"><div className="tc-admin-hero"><div><small>COMMAND CENTER</small><h2>Operations at a glance.</h2><p>Prioritise payment verification, voucher delivery and cashback work.</p></div><button onClick={onWork}><ClipboardList size={16}/> Open Work Queue <ChevronRight size={14}/></button></div><div className="tc-kpis"><Kpi icon={ShoppingBag} label="Orders" value={metrics.orders}/><Kpi icon={CircleDollarSign} label="Verified sales" value={MONEY(metrics.revenue)}/><Kpi icon={WalletCards} label="Cashback" value={MONEY(metrics.cashback)}/><Kpi icon={Link2} label="Links available" value={metrics.availableLinks}/><Kpi icon={ClipboardList} label="Open work" value={workItems}/></div><div className="tc-priority"><b>{workItems}</b><div><strong>Admin work waiting</strong><span>Approve, reject, cancel, remove, verify payments, send vouchers and process cashback from Work Queue.</span></div><button onClick={onWork}>Work now <ChevronRight size={14}/></button></div><div className="tc-quick"><Quick title="Orders" text="Review and edit order records" icon={ShoppingBag} onClick={onOrders}/><Quick title="Payment Link Stock" text="Maintain ₹500 / ₹1,000 / ₹1,500 / ₹2,000 stock" icon={Link2} onClick={onStock}/></div></section>}
function Kpi({icon:Icon,label,value}){return <div className="tc-kpi"><span><Icon size={17}/></span><small>{label}</small><strong>{value??0}</strong></div>}
function Quick({title,text,icon:Icon,onClick}){return <button className="tc-quick-card" onClick={onClick}><Icon size={18}/><div><b>{title}</b><small>{text}</small></div><ChevronRight size={15}/></button>}
function WorkQueue({items,onAction}){return <section className="tc-admin-page"><div className="tc-admin-hero"><div><small>WORK QUEUE</small><h2>Everything that needs admin attention.</h2><p>Every work item has explicit admin controls. Remove hides it without changing the business record.</p></div><div className="tc-work-count">{items.length} open</div></div><div className="tc-work-flow"><span>01 Verify Payment</span><b>→</b><span>02 Voucher / Cashback</span><b>→</b><span>03 Complete / Close</span></div><div className="tc-work-list">{items.length?items.map((item,i)=><article className="tc-work-card" key={`${item.sheet}-${item.recordId}-${i}`}><div className="tc-work-icon">{item.kind==='payment'?<CircleDollarSign size={18}/>:item.kind==='voucher'?<PackageCheck size={18}/>:<WalletCards size={18}/>}</div><div className="tc-work-copy"><div><span>{item.kind==='payment'?'PAYMENT':item.kind==='voucher'?'VOUCHER':'CASHBACK'}</span><b>{item.priority}</b></div><h3>{item.title}</h3><strong>{item.subtitle}</strong><small>{item.detail}</small></div><div className="tc-work-actions"><button className="primary" onClick={()=>onAction(item)}>{item.kind==='payment'?'Verify':item.kind==='voucher'?'Send voucher':'Process'} <ChevronRight size={13}/></button><button onClick={()=>onAction({...item,force:'menu'})}>More <ChevronDown size={13}/></button></div></article>):<div className="tc-empty"><CheckCircle2 size={32}/><b>Work queue is clear.</b><span>No open operational actions.</span></div>}</div></section>}
function DataPage({title,rows,columns,idField,query,setQuery,filter,setFilter,filterOpen,setFilterOpen,onEdit,loading}){const shown=columns.length?columns:Object.keys(rows[0]||{}),filterField=filter.field||(['Status','Role','Active','InventoryStatus','Provider','Method','Type'].find(f=>shown.includes(f))||''),values=filterField?[...new Set(rows.map(r=>fmt(r[filterField])).filter(Boolean))].slice(0,100):[];return <section className="tc-admin-page"><div className="tc-data-head"><div><small>DATA CONTROL</small><h2>{title}</h2><span>{rows.length} records shown</span></div><div className="tc-data-tools"><div className="tc-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search anything…"/></div><button className={filterOpen||filter.value?'active':''} onClick={()=>setFilterOpen(v=>!v)}><Filter size={15}/> Filter {filter.value&&<b>1</b>}</button></div></div>{filterOpen&&<div className="tc-filter-panel"><label>Important field<select value={filterField} onChange={e=>setFilter({field:e.target.value,value:''})}><option value="">Choose field</option>{shown.filter(c=>['Status','Role','Active','InventoryStatus','Provider','Method','Type'].includes(c)).map(c=><option key={c}>{c}</option>)}</select></label><label>Value<select value={filter.value} onChange={e=>setFilter({field:filterField,value:e.target.value})}><option value="">All</option>{values.map(v=><option key={v} value={v}>{v}</option>)}</select></label><button onClick={()=>setFilter({field:'',value:''})}>Clear</button></div>}<div className="tc-table-wrap">{loading&&!rows.length?<div className="tc-empty"><RefreshCw className="tc-spin"/> Loading…</div>:rows.length?<table><thead><tr>{shown.map(c=><th key={c}>{c}</th>)}<th>Action</th></tr></thead><tbody>{rows.map((r,i)=><tr key={String(r[idField]||i)}>{shown.map(c=><td key={c} title={fmt(r[c])}>{fmt(r[c])}</td>)}<td><button className="tc-edit" onClick={()=>onEdit({sheet:titleToSheet(title),id:r[idField],idField,row:r,columns:shown})}><Edit3 size={13}/> Edit / Update</button></td></tr>)}</tbody></table>:<div className="tc-empty"><Database size={28}/><b>No records</b><span>Change the search or filter.</span></div>}</div></section>}
function titleToSheet(title){return Object.keys(LABEL).find(k=>LABEL[k]===title)||title}
function WorkModal({item,tables,token,onClose,onAction,onError}){const[menu,setMenu]=useState(item.force==='menu'),[reason,setReason]=useState(''),[code,setCode]=useState(''),[pin,setPin]=useState(''),[productId,setProductId]=useState('');const doAction=async action=>{if(action==='SEND_VOUCHER'){if(!code.trim()){onError('Voucher code is required.');return}try{await api.adminSendVoucher(token,item.recordId,code.trim(),pin.trim(),productId,true);onClose();window.location.reload()}catch(e){onError(e.message)}}else await onAction(action,item,{reason})};return <div className="tc-modal-backdrop"><div className="tc-modal"><button className="tc-modal-x" onClick={onClose}><X size={17}/></button><small>WORK ACTION</small><h3>{item.title}</h3><p>{item.subtitle} · {item.detail}</p>{item.kind==='voucher'&&<div className="tc-form-grid"><label>Voucher code<input value={code} onChange={e=>setCode(e.target.value)} placeholder="Enter voucher code"/></label><label>PIN (optional)<input value={pin} onChange={e=>setPin(e.target.value)} placeholder="PIN"/></label><label>Product<select value={productId} onChange={e=>setProductId(e.target.value)}><option value="">Select product</option>{(tables.Products?.rows||[]).map(p=><option key={p.ProductID} value={p.ProductID}>{p.Title}</option>)}</select></label></div>}<label>Reason / admin note<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Optional reason or note"/></label><div className="tc-action-grid">{(item.actions||[]).filter(a=>menu||['VERIFY_PAYMENT','SEND_VOUCHER','PROCESS_CASHBACK'].includes(a)).map(a=><button key={a} className={['REJECT','CANCEL','REMOVE'].includes(a)?'danger':['VERIFY_PAYMENT','SEND_VOUCHER','PROCESS_CASHBACK'].includes(a)?'primary':''} onClick={()=>doAction(a)}>{actionLabel(a)}</button>)}</div>{!menu&&<button className="tc-more" onClick={()=>setMenu(true)}>Show approve / reject / cancel / remove <ChevronDown size={14}/></button>}</div></div>}
function actionLabel(a){return({VERIFY_PAYMENT:'Verify Payment',SEND_VOUCHER:'Send Voucher',PROCESS_CASHBACK:'Process Cashback',COMPLETE_CASHBACK:'Complete Cashback',APPROVE:'Approve',REJECT:'Reject',CANCEL:'Cancel',REMOVE:'Remove from Work Queue'}[a]||a)}
function EditModal({edit,token,onClose,onDone,onError}){const[patch,setPatch]=useState(()=>{const p={};(edit.columns||[]).forEach(c=>{if(c!==edit.idField)p[c]=fmt(edit.row?.[c])});return p});const save=async()=>{try{await api.adminEditAnyRow(token,edit.sheet,edit.id,patch);await onDone()}catch(e){onError(e.message)}};return <div className="tc-modal-backdrop"><div className="tc-modal tc-edit-modal"><button className="tc-modal-x" onClick={onClose}><X size={17}/></button><small>ADMIN EDIT / UPDATE</small><h3>{LABEL[edit.sheet]||edit.sheet}</h3><p>All operational fields are editable. Security hashes, session tokens and audit IDs remain protected.</p><div className="tc-edit-grid">{Object.entries(patch).map(([key,value])=><label key={key}>{key}<textarea value={value} onChange={e=>setPatch(p=>({...p,[key]:e.target.value}))}/></label>)}</div><div className="tc-modal-actions"><button onClick={onClose}>Cancel</button><button className="primary" onClick={save}>Save & Update</button></div></div></div>}
function StockPage({rows,onOpen,onEdit}){return <section className="tc-admin-page"><div className="tc-data-head"><div><small>PAYMENT LINKS</small><h2>Payment Link Stock</h2><span>{rows.length} records</span></div><button className="tc-add" onClick={onOpen}><Plus size={15}/> Add stock</button></div><DataPage title="Payment Link Stock" rows={rows} columns={rows[0]?Object.keys(rows[0]):['PaymentLinkStockID','Denomination','Link','Label','Status']} idField="PaymentLinkStockID" query="" setQuery={()=>{}} filter={{field:'',value:''}} setFilter={()=>{}} filterOpen={false} setFilterOpen={()=>{}} onEdit={onEdit} loading={false}/></section>}
function StockModal({token,onClose,onDone,onError}){const[amount,setAmount]=useState(''),[links,setLinks]=useState('');const save=async()=>{try{const rows=links.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(![500,1000,1500,2000].includes(Number(amount)))throw new Error('Select ₹500, ₹1,000, ₹1,500 or ₹2,000.');if(!rows.length)throw new Error('Paste at least one payment link.');if(rows.some(x=>!/^https:\/\//i.test(x)))throw new Error('Each payment link must start with https://');await api.adminAddPaymentLinkStockBulk(token,rows.map(link=>({denomination:Number(amount),link,label:`Pay ₹${Number(amount).toLocaleString('en-IN')}`})));await onDone()}catch(e){onError(e.message)}};return <div className="tc-modal-backdrop"><div className="tc-modal"><button className="tc-modal-x" onClick={onClose}><X size={17}/></button><small>LINK STOCK</small><h3>Add payment links</h3><label>Amount<select value={amount} onChange={e=>setAmount(e.target.value)}><option value="">Select amount</option><option value="500">₹500</option><option value="1000">₹1,000</option><option value="1500">₹1,500</option><option value="2000">₹2,000</option></select></label><label>Payment links<textarea value={links} onChange={e=>setLinks(e.target.value)} placeholder="Paste one Paytm link per line" rows="7"/></label><div className="tc-modal-actions"><button onClick={onClose}>Cancel</button><button className="primary" onClick={save}>Add to Stock</button></div></div></div>}
function Reports({data}){const m=data?.metrics||{};return <section className="tc-admin-page"><div className="tc-admin-hero"><div><small>REPORTS</small><h2>Business control</h2><p>Live operational metrics and status counts.</p></div></div><div className="tc-kpis"><Kpi icon={ShoppingBag} label="Orders" value={m.orders}/><Kpi icon={CircleDollarSign} label="Revenue" value={MONEY(m.revenue)}/><Kpi icon={WalletCards} label="Cashback" value={MONEY(m.cashback)}/><Kpi icon={Link2} label="Links" value={m.availableLinks}/></div></section>}
function AllData({tables,onOpen}){return <section className="tc-admin-page"><div className="tc-admin-hero"><div><small>ALL DATA</small><h2>Every operational dataset.</h2><p>Open any dataset to filter, edit and update operational records.</p></div></div><div className="tc-data-cards">{DATA_SHEETS.filter(x=>x!=='AuditLogs').map(name=><button key={name} onClick={()=>onOpen(name)}><Database size={17}/><div><b>{LABEL[name]}</b><span>{tables[name]?.rows?.length||0} loaded records</span></div><ChevronRight size={14}/></button>)}</div><button className="tc-data-card-wide" onClick={()=>onOpen('AuditLogs')}><Activity size={17}/><div><b>Web Activity</b><span>Complete user + admin activity and edit/update trail</span></div><ChevronRight size={14}/></button></section>}
function pageTitle(active){return active==='dashboard'?'Command Center':active==='work'?'Work Queue':active==='reports'?'Reports':active==='all-data'?'All Data':LABEL[active]||active}
