import {useEffect,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {Activity,ArrowUpRight,BarChart3,CheckCircle2,CircleDollarSign,Clock3,ExternalLink,Link2,PackageCheck,RefreshCw,ShoppingBag,WalletCards} from 'lucide-react'
import {api} from './api'
import './admin-dashboard-redesign.css'

const money=v=>`₹${Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`
const text=v=>String(v??'').trim()
const upper=v=>text(v).toUpperCase()
const num=v=>{const n=Number(text(v).replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0}
const status=r=>upper(r.Status||r.PaymentStatus||r.OrderStatus||r.State||r.InventoryStatus)
const amount=r=>num(r.Amount??r.TotalAmount??r.OrderValue??r.Total??r.Price??r.Denomination)
const rows=async(token,sheet)=>{try{return (await api.adminTable(token,sheet))?.table?.rows||[]}catch{return[]}}
const go=label=>{const b=[...document.querySelectorAll('.tc-admin-nav button')].find(x=>text(x.textContent).toLowerCase().includes(label.toLowerCase()));b?.click()}
const good=['VERIFIED','SUCCESS','PAID','COMPLETED','CONFIRMED','DELIVERED','SENT','FULFILLED']
const pending=['PENDING','INITIATED','PROCESSING','REQUESTED','PENDING_PAYMENT']
const bad=['FAILED','ERROR','REJECTED','CANCELLED']
function Tile({icon:Icon,label,value,sub,target,tone=''}){return <button type="button" className={`tc-dr-metric ${tone}`} onClick={()=>go(target)}><span className="tc-dr-icon"><Icon size={18}/></span><div><small>{label}</small><strong>{value}</strong><em>{sub}</em></div><ArrowUpRight size={15}/></button>}
function Action({icon:Icon,label,value,sub,target,tone=''}){return <button type="button" className={`tc-dr-action ${tone}`} onClick={()=>go(target)}><span><Icon size={16}/></span><div><b>{label}</b><strong>{value}</strong><small>{sub}</small></div><ArrowUpRight size={14}/></button>}
function Mini({label,value,sub,target}){return <button type="button" className="tc-dr-mini" onClick={()=>go(target)}><span>{label}</span><b>{value}</b><small>{sub}</small></button>}
function Dashboard(){
 const[data,setData]=useState(null),[loading,setLoading]=useState(true)
 const token=localStorage.getItem('tc_erp_session')||''
 useEffect(()=>{let live=true;(async()=>{const names=['Orders','Payments','PaymentLinkStock','PaymentLinkRequests','Vouchers','CashbackWallet','CashbackTransactions','WalletRedemptions','Users','Products','Brands','Cart','Notifications','OTP','UserSessions','AuditLogs'];const vals=await Promise.all(names.map(n=>rows(token,n)));const x={};names.forEach((n,i)=>x[n]=vals[i]);let work=[];try{work=(await api.adminWorklist(token))?.items||[]}catch{};if(live){setData({x,work});setLoading(false)}})();return()=>{live=false}},[token])
 if(loading)return <section className="tc-dr-page"><div className="tc-dr-loading"><RefreshCw className="tc-spin" size={18}/> Loading live operations data…</div></section>
 const x=data?.x||{},work=data?.work||[],orders=x.Orders||[],payments=x.Payments||[],stock=x.PaymentLinkStock||[],requests=x.PaymentLinkRequests||[],vouchers=x.Vouchers||[],wallet=x.CashbackWallet||[],cash=x.CashbackTransactions||[],payouts=x.WalletRedemptions||[],users=x.Users||[],products=x.Products||[],brands=x.Brands||[],cart=x.Cart||[],notifications=x.Notifications||[],otp=x.OTP||[],sessions=x.UserSessions||[],audit=x.AuditLogs||[]
 const verified=payments.filter(r=>good.includes(status(r))),payPending=payments.filter(r=>pending.includes(status(r))),payFailed=payments.filter(r=>bad.includes(status(r))),delivered=vouchers.filter(r=>good.includes(status(r))),voucherPending=vouchers.filter(r=>pending.includes(status(r))),linkAvailable=stock.filter(r=>['','AVAILABLE','READY','ACTIVE','IN_STOCK'].includes(status(r))),linkReserved=stock.filter(r=>status(r)==='RESERVED'),linkUsed=stock.filter(r=>['USED','CONSUMED'].includes(status(r))),requestPending=requests.filter(r=>pending.includes(status(r))),payoutPending=payouts.filter(r=>pending.includes(status(r)))
 const sales=verified.reduce((s,r)=>s+num(r.Amount??r.PaidAmount??r.TotalAmount),0),walletBalance=wallet.reduce((s,r)=>s+num(r.Balance??r.AvailableBalance),0),stockValue=linkAvailable.reduce((s,r)=>s+amount(r),0),unread=notifications.filter(r=>['UNREAD','0','FALSE','PENDING'].includes(upper(r.Read??r.Status))).length,otpFails=otp.filter(r=>bad.includes(status(r))||upper(r.Success)==='FALSE').length,activeSessions=sessions.filter(r=>['','ACTIVE','TRUE','YES'].includes(status(r))&&upper(r.Revoked)!=='TRUE').length,auditErrors=audit.filter(r=>bad.includes(status(r))||upper(r.Success)==='FALSE').length
 const denom=[500,1000,1500,2000].map(v=>({v,n:stock.filter(r=>num(r.Denomination??r.Amount??r.Value??r.Price)===v&&['','AVAILABLE','READY','ACTIVE','IN_STOCK'].includes(status(r))).length}))
 return <section className="tc-dr-page"><div className="tc-dr-top"><div><span>TRUSTED CIRCLE · OPERATIONS</span><h1>Command Center</h1><p>Live business position, operational workload and system health — in one view.</p></div><button type="button" onClick={()=>window.location.reload()}><RefreshCw size={15}/> Refresh data</button></div>
 <div className="tc-dr-grid-main"><div className="tc-dr-card tc-dr-operations"><div className="tc-dr-head"><div><span>OPERATIONS</span><h2>What needs attention?</h2></div><button type="button" onClick={()=>go('Work Queue')}>Open queue <ExternalLink size={13}/></button></div><div className="tc-dr-actions"><Action icon={CircleDollarSign} label="Payments to verify" value={payPending.length} sub={money(payPending.reduce((s,r)=>s+num(r.Amount),0))+' awaiting verification'} target="Payments" tone="warn"/><Action icon={Link2} label="Link requests" value={requestPending.length} sub="Waiting for fulfilment" target="Link Requests" tone="blue"/><Action icon={PackageCheck} label="Vouchers pending" value={voucherPending.length} sub={`${delivered.length} already delivered`} target="Vouchers" tone="purple"/><Action icon={WalletCards} label="Cashback payouts" value={payoutPending.length} sub={money(payoutPending.reduce((s,r)=>s+amount(r),0))+' awaiting processing'} target="Cashback Payouts" tone="green"/></div></div><div className="tc-dr-card"><div className="tc-dr-head"><div><span>PAYMENT LINK INVENTORY</span><h2>Stock by denomination</h2></div><button type="button" onClick={()=>go('Link Stock')}>Manage <ExternalLink size={13}/></button></div><div className="tc-dr-denoms">{denom.map(d=><Mini key={d.v} label={`₹${d.v.toLocaleString('en-IN')}`} value={d.n} sub="available" target="Link Stock"/>)}</div><div className="tc-dr-stock-summary"><span><b>{linkAvailable.length}</b> Available</span><span><b>{linkReserved.length}</b> Reserved</span><span><b>{linkUsed.length}</b> Used</span><span><b>{money(stockValue)}</b> Value</span></div></div></div>
 <div className="tc-dr-metrics"><Tile icon={CircleDollarSign} label="Verified Sales" value={money(sales)} sub={`${verified.length} verified payments`} target="Payments" tone="money"/><Tile icon={ShoppingBag} label="Orders" value={orders.length} sub="All customer orders" target="Orders" tone="blue"/><Tile icon={Clock3} label="Payment Pending" value={payPending.length} sub="Waiting for verification" target="Payments" tone="warn"/><Tile icon={Link2} label="Links Available" value={linkAvailable.length} sub={money(stockValue)+' stock value'} target="Link Stock" tone="green"/><Tile icon={WalletCards} label="Wallet Balance" value={money(walletBalance)} sub={`${wallet.length} wallets`} target="Cashback Wallet" tone="purple"/><Tile icon={Activity} label="Open Work" value={work.length} sub="Requires admin action" target="Work Queue" tone="danger"/></div>
 <div className="tc-dr-grid-3"><div className="tc-dr-card"><div className="tc-dr-head"><div><span>SALES PIPELINE</span><h2>Order position</h2></div><button type="button" onClick={()=>go('Orders')}>Orders <ExternalLink size={13}/></button></div><div className="tc-dr-bars"><div><span>Total orders</span><b>{orders.length}</b></div><div><span>Paid / completed</span><b>{orders.filter(r=>good.includes(status(r))).length}</b></div><div><span>Payment pending</span><b>{payPending.length}</b></div><div><span>Failed payments</span><b>{payFailed.length}</b></div></div></div><div className="tc-dr-card"><div className="tc-dr-head"><div><span>CUSTOMERS & CATALOG</span><h2>Platform scale</h2></div><button type="button" onClick={()=>go('Shoppers')}>Customers <ExternalLink size={13}/></button></div><div className="tc-dr-mini-grid"><Mini label="Shoppers" value={users.length} sub="accounts" target="Shoppers"/><Mini label="Products" value={products.length} sub="catalog" target="Products"/><Mini label="Brands" value={brands.length} sub="catalogue" target="Brands"/><Mini label="Cart lines" value={cart.length} sub="current" target="Cart"/></div></div><div className="tc-dr-card"><div className="tc-dr-head"><div><span>SYSTEM HEALTH</span><h2>Control room</h2></div><button type="button" onClick={()=>go('Web Activity')}>Activity <ExternalLink size={13}/></button></div><div className="tc-dr-health"><Mini label="Unread notifications" value={unread} sub="needs review" target="Notifications"/><Mini label="OTP failures" value={otpFails} sub="security events" target="OTP Logs"/><Mini label="Active sessions" value={activeSessions} sub="current" target="Sessions"/><Mini label="Activity errors" value={auditErrors} sub="audit records" target="Web Activity"/></div></div></div>
 <div className="tc-dr-footer-grid"><button type="button" onClick={()=>go('Payments')}><CheckCircle2 size={16}/><div><b>Payment verification</b><span>{verified.length} verified · {payFailed.length} failed</span></div><ArrowUpRight size={14}/></button><button type="button" onClick={()=>go('Cashback History')}><BarChart3 size={16}/><div><b>Cashback ledger</b><span>{cash.length} transactions</span></div><ArrowUpRight size={14}/></button><button type="button" onClick={()=>go('Cashback Payouts')}><WalletCards size={16}/><div><b>Payout processing</b><span>{payoutPending.length} pending</span></div><ArrowUpRight size={14}/></button><button type="button" onClick={()=>go('Reports')}><BarChart3 size={16}/><div><b>Business reports</b><span>Performance and operational insights</span></div><ArrowUpRight size={14}/></button></div></section>
}
export default function AdminDashboardRedesign(){useEffect(()=>{let root=null,host=null,timer;const cleanup=()=>{root?.unmount();root=null;host?.remove();host=null};const run=()=>{const main=document.querySelector('.tc-admin-main'),page=main?.querySelector('.tc-admin-page');if(!main||!page)return;const heading=text(main.querySelector('.tc-admin-header h1')?.textContent).toLowerCase();if(heading!=='dashboard'){cleanup();return}if(host?.isConnected)return;page.classList.add('tc-dashboard-redesigned');page.querySelectorAll(':scope > *').forEach(e=>{if(!e.classList.contains('tc-dashboard-redesign-host'))e.classList.add('tc-dashboard-original-hidden')});host=document.createElement('div');host.className='tc-dashboard-redesign-host';page.appendChild(host);root=createRoot(host);root.render(<Dashboard/>)};const schedule=()=>{clearTimeout(timer);timer=setTimeout(run,80)};schedule();const observer=new MutationObserver(schedule);observer.observe(document.body,{subtree:true,childList:true,characterData:true});return()=>{clearTimeout(timer);observer.disconnect();cleanup()}},[]);return null}
