import {useEffect} from 'react'
import './admin-kpi-all-pages.css'

const clean=v=>String(v??'').trim()
const upper=v=>clean(v).toUpperCase()
const num=v=>{const n=Number(String(v??'').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0}
const money=v=>'₹'+Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2})
const PAGE_MAP={'ORDERS':'Orders','PAYMENTS':'Payments','PAYMENT LINKS':'Payment Links','LINK REQUESTS':'Link Requests','LINK STOCK':'Link Stock','VOUCHERS':'Vouchers','PRODUCTS':'Products','BRANDS':'Brands','CART':'Cart','NOTIFICATIONS':'Notifications','OTP LOGS':'OTP Logs','SESSIONS':'Sessions','WEB ACTIVITY':'Web Activity','CASHBACK WALLET':'Cashback Wallet','CASHBACK HISTORY':'Cashback History','CASHBACK PAYOUTS':'Cashback Payouts','SHOPPERS':'Shoppers','ORDER ITEMS':'Order Items'}
const PENDING=['PENDING','PENDING_PAYMENT','REQUESTED','PROCESSING','INITIATED']
const DONE=['COMPLETED','PAID','DELIVERED','VERIFIED','SENT','SUCCESS','FULFILLED']
const BAD=['FAILED','REJECTED','CANCELLED','ERROR','BLOCKED']
function go(label){const needle=String(label).toLowerCase();const b=[...document.querySelectorAll('.tc-admin-nav button')].find(x=>String(x.textContent||'').toLowerCase().includes(needle));if(b)b.click()}
function read(page){const table=page.querySelector('.tc-table-wrap table');if(!table)return[];const heads=[...table.querySelectorAll('thead th')].map(x=>clean(x.textContent));return [...table.querySelectorAll('tbody tr')].map(tr=>{const cells=[...tr.querySelectorAll('td')],row={};heads.forEach((h,i)=>{if(h&&h!=='Action')row[h]=clean(cells[i]?.textContent)});return row})}
function makeCard(label,value,detail,target,tone,icon){const b=document.createElement('button');b.type='button';b.className='tc-new-kpi '+(tone||'neutral');b.innerHTML='<span class="tc-new-kpi-icon">'+(icon||'•')+'</span><div><small>'+label+'</small><strong>'+value+'</strong><em>'+detail+'</em></div><b class="tc-new-kpi-arrow">↗</b>';b.onclick=()=>go(target);return b}
function build(page,heading,key){page.querySelector('.tc-new-kpi-grid')?.remove();const rows=read(page),state=r=>upper(r.Status||r.PaymentStatus||r.OrderStatus||r.State||r.InventoryStatus),active=rows.filter(r=>['ACTIVE','TRUE','YES','AVAILABLE','READY','IN_STOCK'].includes(upper(r.Active||r.Status||r.InventoryStatus))),pending=rows.filter(r=>PENDING.includes(state(r))),done=rows.filter(r=>DONE.includes(state(r))),bad=rows.filter(r=>BAD.includes(state(r))),total=rows.reduce((s,r)=>s+num(r.Amount??r.TotalAmount??r.OrderValue??r.Total??r.Price??r.Denomination),0),items=[],add=(l,v,d,t,tone='neutral',i='•')=>items.push(makeCard(l,v,d,t,tone,i))
if(heading==='ORDERS'){add('Orders',rows.length,'All order records','Orders');add('Paid / Fulfilled',done.length,'Completed sales','Orders','good','✓');add('Payment Pending',pending.length,'Needs payment','Orders','warn','◷');add('Delivered',rows.filter(r=>state(r)==='DELIVERED').length,'Completed delivery','Vouchers','info','✓');add('Order Value',money(total),'Loaded order value','Orders','money','₹')}
else if(heading==='PAYMENTS'){const collected=rows.filter(r=>state(r)==='VERIFIED').reduce((s,r)=>s+num(r.Amount),0);add('Collected',money(collected),'Verified payments','Payments','money','₹');add('Verified',done.length,'Cleared payments','Payments','good','✓');add('Pending',pending.length,'Awaiting verification','Payments','warn','◷');add('Failed',bad.length,'Requires review','Payments','danger','!')}
else if(heading==='PAYMENT LINKS'){add('Total Links',rows.length,'Payment-link records','Payment Links');add('Ready',active.length,'Available links','Link Stock','good','✓');add('Reserved',rows.filter(r=>state(r)==='RESERVED').length,'Held links','Link Stock','warn','◷');add('Used',rows.filter(r=>state(r)==='USED').length,'Consumed links','Link Stock','info','✓')}
else if(heading==='LINK REQUESTS'){add('Requests',rows.length,'All requests','Link Requests');add('Pending',pending.length,'Needs action','Link Requests','warn','◷');add('Completed',done.length,'Processed requests','Link Requests','good','✓');add('Rejected',bad.length,'Review required','Link Requests','danger','!')}
else if(heading==='LINK STOCK'){add('Available',active.length,'Ready inventory','Link Stock','good','✓');add('Reserved',rows.filter(r=>state(r)==='RESERVED').length,'Held inventory','Link Stock','warn','◷');add('Used',rows.filter(r=>['USED','CONSUMED'].includes(state(r))).length,'Consumed links','Link Stock','info','✓');add('Stock Value',money(total),'Loaded stock value','Link Stock','money','₹')}
else if(heading==='VOUCHERS'){add('Vouchers',rows.length,'All voucher records','Vouchers');add('Delivered',done.length,'Completed delivery','Vouchers','good','✓');add('Pending',pending.length,'Awaiting delivery','Vouchers','warn','◷');add('Failed',bad.length,'Delivery issues','Vouchers','danger','!')}
else if(heading==='PRODUCTS'){const discounts=rows.map(r=>num(r.DiscountPercent)).filter(v=>v>0),avg=discounts.length?discounts.reduce((a,b)=>a+b,0)/discounts.length:0;add('Products',rows.length,'Catalog records','Products');add('Active',active.length,'Available products','Products','good','✓');add('Discounted',discounts.length,'Products with discount','Products','info','%');add('Avg Discount',avg.toFixed(2)+'%','Across loaded products','Products','money','%')}
else if(heading==='BRANDS'){add('Brands',rows.length,'Configured brands','Brands','info','◆');add('Active',active.length,'Available brands','Brands','good','✓')}
else if(heading==='CART'){add('Cart Items',rows.length,'Current cart lines','Cart');add('Quantity',rows.reduce((s,r)=>s+num(r.Quantity),0),'Units in carts','Cart','info','+');add('Cart Value',money(total),'Loaded cart value','Cart','money','₹')}
else if(heading==='NOTIFICATIONS'){add('Notifications',rows.length,'Notification records','Notifications');add('Unread',rows.filter(r=>['UNREAD','FALSE','0'].includes(upper(r.Read||r.Status))).length,'Needs review','Notifications','warn','●');add('Successful',done.length,'Sent / delivered','Notifications','good','✓')}
else if(heading==='OTP LOGS'){add('Attempts',rows.length,'OTP security records','OTP Logs');add('Successful',done.length,'Verified attempts','OTP Logs','good','✓');add('Failed',bad.length,'Failed attempts','OTP Logs','danger','!')}
else if(heading==='SESSIONS'){add('Sessions',rows.length,'Session records','Sessions');add('Active',active.length,'Current sessions','Sessions','good','✓');add('Expired',rows.filter(r=>['EXPIRED','REVOKED','INACTIVE'].includes(state(r))).length,'Closed sessions','Sessions','warn','◷')}
else if(heading==='WEB ACTIVITY'){add('Activity',rows.length,'Audit records','Web Activity');add('Successful',done.length,'Successful actions','Web Activity','good','✓');add('Errors',bad.length,'Requires investigation','Web Activity','danger','!')}
else if(heading==='CASHBACK WALLET'){add('Wallets',rows.length,'Customer wallets','Cashback Wallet');add('Balance',money(rows.reduce((s,r)=>s+num(r.Balance),0)),'Current balance','Cashback Wallet','money','₹');add('Earned',money(rows.reduce((s,r)=>s+num(r.TotalEarned),0)),'Lifetime earned','Cashback History','good','↗');add('Redeemed',money(rows.reduce((s,r)=>s+num(r.TotalRedeemed),0)),'Lifetime redeemed','Cashback History','info','✓')}
else if(heading==='CASHBACK HISTORY'){add('Transactions',rows.length,'Cashback ledger','Cashback History');add('Completed',done.length,'Completed entries','Cashback History','good','✓');add('Pending',pending.length,'Awaiting completion','Cashback History','warn','◷');add('Value',money(Math.abs(total)),'Loaded transaction value','Cashback History','money','₹')}
else if(heading==='CASHBACK PAYOUTS'){add('Requests',rows.length,'Payout requests','Cashback Payouts');add('Pending',pending.length,'Awaiting processing','Cashback Payouts','warn','◷');add('Completed',done.length,'Completed payouts','Cashback Payouts','good','✓');add('Amount',money(total),'Loaded payout value','Cashback Payouts','money','₹')}
else if(heading==='SHOPPERS'){add('Shoppers',rows.length,'Customer accounts','Shoppers','info','◉');add('Active',active.length,'Active customers','Shoppers','good','✓');add('Pending',pending.length,'Review required','Shoppers','warn','◷');add('Restricted',bad.length,'Removed / blocked','Shoppers','danger','!')}
else if(heading==='ORDER ITEMS'){add('Line Items',rows.length,'Order lines','Order Items');add('Orders',new Set(rows.map(r=>r.OrderID).filter(Boolean)).size,'Unique orders','Orders','info','▣');add('Quantity',rows.reduce((s,r)=>s+num(r.Quantity),0),'Units','Order Items','good','+')}
else return
const grid=document.createElement('div');grid.className='tc-new-kpi-grid';items.forEach(x=>grid.appendChild(x));const anchor=page.querySelector('.tc-data-head')||page.querySelector('.tc-admin-hero');if(anchor)anchor.insertAdjacentElement('afterend',grid);page.dataset.kpiKey=key}
function run(){const main=document.querySelector('.tc-admin-main');if(!main)return;const heading=clean(main.querySelector('.tc-admin-header h1')?.textContent).toUpperCase();if(!PAGE_MAP[heading]||heading==='DASHBOARD')return;const page=[...main.querySelectorAll('.tc-admin-page')].find(p=>p.querySelector('.tc-table-wrap'));if(!page)return;const rows=read(page),first=rows[0]?Object.values(rows[0]).join('|'):'';const key=heading+':'+rows.length+':'+first;if(page.dataset.kpiKey!==key)build(page,heading,key)}
export default function AdminKpiAllPages(){useEffect(()=>{let timer;const schedule=()=>{clearTimeout(timer);timer=setTimeout(run,120)};const observer=new MutationObserver(schedule);observer.observe(document.body,{subtree:true,childList:true,characterData:true});schedule();return()=>{clearTimeout(timer);observer.disconnect()}},[]);return null}
