import {useEffect,useMemo,useState} from 'react'
import {Activity,AlertTriangle,BarChart3,CheckCircle2,ChevronDown,ChevronRight,CircleDollarSign,ClipboardList,Database,Edit3,Filter,KeyRound,LayoutDashboard,Link2,LogOut,Menu,PackageCheck,Plus,RefreshCw,Search,ShieldCheck,ShoppingBag,Users,WalletCards,X} from 'lucide-react'
import {api} from './api'
import './admin-workspace.css'
import './admin-upgrade.css'

const LOGO='https://raw.githubusercontent.com/trustedcircle2026-cloud/Trusted-Circle/main/Logo%20new.jpg'
const MONEY=v=>`₹${Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`
const fmt=v=>v==null?'':typeof v==='object'?JSON.stringify(v):String(v)
const LABEL={Users:'Shoppers',Orders:'Orders',OrderItems:'Order Items',Payments:'Payments',PaymentLinks:'Payment Links',PaymentLinkRequests:'Link Requests',PaymentLinkStock:'Payment Link Stock',Vouchers:'Vouchers',Products:'Products',Brands:'Brands',Cart:'Cart',Notifications:'Notifications',OTP:'OTP Logs',UserSessions:'Sessions',AuditLogs:'Web Activity',CashbackWallet:'Cashback Wallet',CashbackTransactions:'Cashback History',WalletRedemptions:'Cashback Payouts'}
const SHEETS=Object.keys(LABEL)
const MENU=[['COMMAND',[['dashboard','Command Center',LayoutDashboard],['work','Work Queue',ClipboardList]]],['SALES',[['Orders','Orders',ShoppingBag],['Payments','Payments',CircleDollarSign],['PaymentLinks','Payment Links',Link2],['PaymentLinkStock','Link Stock',Database]]],['CATALOG',[['Products','Products',PackageCheck],['Brands','Brands',ShoppingBag]]],['FINANCE',[['WalletRedemptions','Cashback Payouts',WalletCards],['CashbackWallet','Cashback Wallet',WalletCards],['CashbackTransactions','Cashback History',Activity]]],['CUSTOMERS',[['Users','Shoppers',Users]]],['INSIGHTS',[['reports','Reports',BarChart3],['all-data','All Data',Database]]],['SYSTEM',[['AuditLogs','Web Activity',Activity],['Notifications','Notifications',Activity],['OTP','OTP Logs',KeyRound],['UserSessions','Sessions',ShieldCheck]]]]

export default function AdminWorkspaceV2(){
 const[token,setToken]=useState(()=>localStorage.getItem('tc_erp_session')||''),[user,setUser]=useState(null),[login,setLogin]=useState({email:'trustedcircle2026@gmail.com',password:''}),[error,setError]=useState(''),[loading,setLoading]=useState(false),[data,setData]=useState(null),[active,setActive]=useState('dashboard'),[mobile,setMobile]=useState(false),[query,setQuery]=useState(''),[filter,setFilter]=useState({field:'',value:''}),[showFilter,setShowFilter]=useState(false),[edit,setEdit]=useState(null),[work,setWork]=useState(null),[workItems,setWorkItems]=useState([]),[stock,setStock]=useState(false)
 useEffect(()=>{if(window.location.hash.replace(/^#\/?/,'').startsWith('erp')){const t=localStorage.getItem('tc_erp_session');if(t){setToken(t);refresh(t)}}},[])
 async function refresh(t=token){setLoading(true);setError('');try{const d=await api.adminDashboard(t);setData(d);setUser(d.admin);const w=await api.adminWorklist(t);setWorkItems(w?.items||[])}catch(e){localStorage.removeItem('tc_erp_session');setToken('');setUser(null);setData(null);setError(e.message||'ERP session expired.')}finally{setLoading(false)}}
 async function open(id){setActive(id);setQuery('');setFilter({field:'',value:''});setShowFilter(false);setMobile(false);if(SHEETS.includes(id)&&!data?.tables?.[id]){setLoading(true);try{const r=await api.adminTable(token,id);setData(p=>({...p,tables:{...(p?.tables||{}),[id]:r.table}}))}catch(e){setError(e.message)}finally{setLoading(false)}}}
 async function loginSubmit(e){e.preventDefault();setLoading(true);setError('');try{const r=await api.adminLogin(login.email,login.password);localStorage.setItem('tc_erp_session',r.session.token);setToken(r.session.token);await refresh(r.session.token)}catch(e){setError(e.message||'Invalid ERP credentials.')}finally{setLoading(false)}}
 async function workAction(action,item,reason=''){try{await api.adminWorklistAction(token,action,item.sheet,item.recordId,reason);setWork(null);await refresh()}catch(e){setError(e.message)}}
 function logout(){localStorage.removeItem('tc_erp_session');setToken('');setUser(null);window.location.hash='#/home'}
 const tables=data?.tables||{},table=tables[active],raw=table?.rows||[]
 const filtered=useMemo(()=>raw.filter(r=>{const q=!query||Object.values(r).some(v=>fmt(v).toLowerCase().includes(query.toLowerCase()));const f=!filter.value||String(r[filter.field]||'').toLowerCase()===String(filter.value).toLowerCase();return q&&f}),[raw,query,filter])
 if(!token||!user)return <Login login={login} setLogin={setLogin} loading={loading} error={error} onSubmit={loginSubmit}/>
 return <div className="tc-admin-shell"><aside className={`tc-admin-sidebar ${mobile?'open':''}`}><div className="tc-admin-brand"><img src={LOGO}/><div><b>Trusted Circle</b><small>OPERATIONS ERP</small></div><button onClick={()=>setMobile(false)}><X size={17}/></button></div><nav className="tc-admin-nav">{MENU.map(([section,items])=><div key={section}><div className="tc-admin-label">{section}</div>{items.map(([id,text,Icon])=><button key={id} className={active===id?'active':''} onClick={()=>open(id)}><Icon size={16}/><span>{text}</span>{id==='work'&&workItems.length>0&&<b className="tc-admin-count">{workItems.length}</b>}{active===id&&<ChevronRight size={14}/>}</button>)}</div>)}</nav><div className="tc-admin-foot"><span><i/> Live backend</span><button onClick={logout}><LogOut size={15}/> Sign out</button></div></aside><main className="tc-admin-main"><header className="tc-admin-header"><button className="tc-admin-mobile" onClick={()=>setMobile(true)}><Menu size={20}/></button><div><small>TRUSTED CIRCLE · PRIVATE ERP</small><h1>{title(active)}</h1></div><div className="tc-admin-head-actions"><button onClick={()=>refresh()}><RefreshCw size={16} className={loading?'tc-spin':''}/></button><span><i/> {user.email}</span></div></header>{error&&<div className="tc-admin-alert"><AlertTriangle size={15}/><span>{error}</span><button onClick={()=>setError('')}><X size={14}/></button></div>}
 {active==='dashboard'?<Dashboard metrics={data?.metrics||{}} work={workItems.length} onWork={()=>open('work')} onOrders={()=>open('Orders')} onStock={()=>open('PaymentLinkStock')}/>:active==='work'?<WorkQueue items={workItems} onOpen={setWork}/>:active==='reports'?<Reports metrics={data?.metrics||{}}/>:active==='all-data'?<AllData tables={tables} onOpen={open}/>:active==='PaymentLinkStock'?<StockPage rows={filtered} onAdd={()=>setStock(true)} onEdit={setEdit}/>:<DataPage title={title(active)} sheet={active} rows={filtered} columns={table?.columns||[]} idField={table?.idField} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} showFilter={showFilter} setShowFilter={setShowFilter} onEdit={setEdit} loading={loading}/>}</main>{work&&<WorkModal item={work} products={tables.Products?.rows||[]} token={token} onClose={()=>setWork(null)} onAction={workAction} onError={setError}/>} {edit&&<EditModal edit={edit} token={token} onClose={()=>setEdit(null)} onDone={()=>{setEdit(null);refresh()}} onError={setError}/>} {stock&&<StockModal token={token} onClose={()=>setStock(false)} onDone={()=>{setStock(false);refresh()}} onError={setError}/>}</div>
}
function Login({login,setLogin,loading,error,onSubmit}){return <div className="admin-login"><div className="admin-login-panel"><div className="admin-login-logo"><img src={LOGO}/></div><span className="admin-eyebrow">PRIVATE OPERATIONS</span><h2>Trusted Circle ERP</h2><p>Payments, vouchers, cashback, customers and complete web activity.</p><form onSubmit={onSubmit}><label>Email<input type="email" value={login.email} onChange={e=>setLogin({...login,email:e.target.value})} required/></label><label>Password<input type="password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})} required/></label>{error&&<div className="admin-login-error">{error}</div>}<button className="admin-primary" disabled={loading}>{loading?'Signing in…':'Enter operations ERP'}<ChevronRight size={16}/></button></form></div><div className="admin-login-side"><span>OPERATE WITH CLARITY</span><h1>Everything<br/><em>visible.</em></h1><p>Work queue, filters, editable data and an auditable activity trail.</p></div></div>}
function Dashboard({metrics,work,onWork,onOrders,onStock}){return <section className="tc-admin-page"><div className="tc-admin-hero"><div><small>COMMAND CENTER</small><h2>Operations at a glance.</h2><p>Payment verification → voucher delivery → cashback payout.</p></div><button onClick={onWork}><ClipboardList size={16}/> Work Queue <ChevronRight size={14}/></button></div><div className="tc-kpis"><Kpi icon={ShoppingBag} label="Orders" value={metrics.orders}/><Kpi icon={CircleDollarSign} label="Verified sales" value={MONEY(metrics.revenue)}/><Kpi icon={WalletCards} label="Cashback" value={MONEY(metrics.cashback)}/><Kpi icon={Link2} label="Links" value={metrics.availableLinks}/><Kpi icon={ClipboardList} label="Open work" value={work}/></div><div className="tc-priority"><b>{work}</b><div><strong>Open admin work</strong><span>Verify, approve, reject, cancel, remove, fulfil and process payouts.</span></div><button onClick={onWork}>Open queue</button></div><div className="tc-quick"><Quick title="Orders" text="Review and update orders" icon={ShoppingBag} onClick={onOrders}/><Quick title="Payment Link Stock" text="₹500 / ₹1,000 / ₹1,500 / ₹2,000" icon={Link2} onClick={onStock}/></div></section>}
function Kpi({icon:Icon,label,value}){return <div className="tc-kpi"><span><Icon size={17}/></span><small>{label}</small><strong>{value??0}</strong></div>}
function Quick({title,text,icon:Icon,onClick}){return <button className="tc-quick-card" onClick={onClick}><Icon size={18}/><div><b>{title}</b><small>{text}</small></div><ChevronRight size={15}/></button>}
function WorkQueue({items,onOpen}){return <section className="tc-admin-page"><div className="tc-admin-hero"><div><small>WORK QUEUE</small><h2>Everything requiring admin attention.</h2><p>Each item exposes primary action plus approve / reject / cancel / remove controls.</p></div><b>{items.length} open</b></div><div className="tc-work-flow"><span>01 Verify Payment</span><b>→</b><span>02 Voucher / Cashback</span><b>→</b><span>03 Complete</span></div><div className="tc-work-list">{items.length?items.map((x,i)=><article className="tc-work-card" key={`${x.sheet}-${x.recordId}-${i}`}><div className="tc-work-icon">{x.kind==='payment'?<CircleDollarSign size={18}/>:x.kind==='voucher'?<PackageCheck size={18}/>:<WalletCards size={18}/>}</div><div className="tc-work-copy"><div><span>{x.kind==='payment'?'PAYMENT':x.kind==='voucher'?'VOUCHER':'CASHBACK'}</span><b>{x.priority}</b></div><h3>{x.title}</h3><strong>{x.subtitle}</strong><small>{x.detail}</small></div><div className="tc-work-actions"><button className="primary" onClick={()=>onOpen(x)}>{x.kind==='payment'?'Verify':x.kind==='voucher'?'Send voucher':'Process'}</button><button onClick={()=>onOpen({...x,force:'menu'})}>More <ChevronDown size={13}/></button></div></article>):<div className="tc-empty"><CheckCircle2 size={32}/><b>Work queue is clear.</b></div>}</div></section>}
function DataPage({title,sheet,rows,columns,idField,query,setQuery,filter,setFilter,showFilter,setShowFilter,onEdit,loading}){const shown=columns.length?columns:Object.keys(rows[0]||{}),fields=shown.filter(x=>['Status','Role','Active','InventoryStatus','Provider','Method','Type','ActorType','Success'].includes(x)),field=filter.field||fields[0]||'',values=[...new Set(rows.map(r=>fmt(r[field])).filter(Boolean))].slice(0,100);return <section className="tc-admin-page"><div className="tc-data-head"><div><small>DATA CONTROL</small><h2>{title}</h2><span>{rows.length} records shown</span></div><div className="tc-data-tools"><div className="tc-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search anything…"/></div><button className={showFilter||filter.value?'active':''} onClick={()=>setShowFilter(v=>!v)}><Filter size={15}/> Filter {filter.value&&<b>1</b>}</button></div></div>{showFilter&&<div className="tc-filter-panel"><label>Important field<select value={field} onChange={e=>setFilter({field:e.target.value,value:''})}><option value="">Choose</option>{fields.map(f=><option key={f}>{f}</option>)}</select></label><label>Value<select value={filter.value} onChange={e=>setFilter({field,value:e.target.value})}><option value="">All</option>{values.map(v=><option key={v}>{v}</option>)}</select></label><button onClick={()=>setFilter({field:'',value:''})}>Clear</button></div>}<div className="tc-table-wrap">{loading&&!rows.length?<div className="tc-empty"><RefreshCw className="tc-spin"/> Loading…</div>:rows.length?<table><thead><tr>{shown.map(c=><th key={c}>{c}</th>)}<th>Action</th></tr></thead><tbody>{rows.map((r,i)=><tr key={String(r[idField]||i)}>{shown.map(c=><td key={c} title={fmt(r[c])}>{fmt(r[c])}</td>)}<td><button className="tc-edit" onClick={()=>onEdit({sheet,id:r[idField],idField,row:r,columns:shown})}><Edit3 size={13}/> Edit / Update</button></td></tr>)}</tbody></table>:<div className="tc-empty"><Database size={28}/><b>No records</b><span>Change search or filter.</span></div>}</div></section>}
function WorkModal({item,products,token,onClose,onAction,onError}){const[menu,setMenu]=useState(item.force==='menu'),[reason,setReason]=useState(''),[code,setCode]=useState(''),[pin,setPin]=useState(''),[productId,setProductId]=useState('');const run=async a=>{if(a==='SEND_VOUCHER'){if(!code.trim()){onError('Voucher code is required.');return}try{await api.adminSendVoucher(token,item.recordId,code.trim(),pin.trim(),productId,true);onClose();window.location.reload()}catch(e){onError(e.message)}}else await onAction(a,item,reason)};return <div className="tc-modal-backdrop"><div className="tc-modal"><button className="tc-modal-x" onClick={onClose}><X size={17}/></button><small>WORK ACTION</small><h3>{item.title}</h3><p>{item.subtitle} · {item.detail}</p>{item.kind==='voucher'&&<div className="tc-form-grid"><label>Voucher code<input value={code} onChange={e=>setCode(e.target.value)}/></label><label>PIN<input value={pin} onChange={e=>setPin(e.target.value)}/></label><label>Product<select value={productId} onChange={e=>setProductId(e.target.value)}><option value="">Select product</option>{products.map(p=><option key={p.ProductID} value={p.ProductID}>{p.Title}</option>)}</select></label></div>}<label>Reason / admin note<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="tc-action-grid">{(item.actions||[]).filter(a=>menu||['VERIFY_PAYMENT','SEND_VOUCHER','PROCESS_CASHBACK'].includes(a)).map(a=><button key={a} className={['REJECT','CANCEL','REMOVE'].includes(a)?'danger':['VERIFY_PAYMENT','SEND_VOUCHER','PROCESS_CASHBACK'].includes(a)?'primary':''} onClick={()=>run(a)}>{actionLabel(a)}</button>)}</div>{!menu&&<button className="tc-more" onClick={()=>setMenu(true)}>Show all admin actions <ChevronDown size={14}/></button>}</div></div>}
function actionLabel(a){return({VERIFY_PAYMENT:'Verify Payment',SEND_VOUCHER:'Send Voucher',PROCESS_CASHBACK:'Process Cashback',COMPLETE_CASHBACK:'Complete Cashback',APPROVE:'Approve',REJECT:'Reject',CANCEL:'Cancel',REMOVE:'Remove from Work Queue'}[a]||a)}
function EditModal({edit,token,onClose,onDone,onError}){const[patch,setPatch]=useState(()=>Object.fromEntries((edit.columns||[]).filter(c=>c!==edit.idField).map(c=>[c,fmt(edit.row[c])])));const save=async()=>{try{await api.adminEditAnyRow(token,edit.sheet,edit.id,patch);await onDone()}catch(e){onError(e.message)}};return <div className="tc-modal-backdrop"><div className="tc-modal tc-edit-modal"><button className="tc-modal-x" onClick={onClose}><X size={17}/></button><small>ADMIN EDIT / UPDATE</small><h3>{LABEL[edit.sheet]||edit.sheet}</h3><p>Operational fields are editable. Security hashes, session tokens and audit IDs remain protected.</p><div className="tc-edit-grid">{Object.entries(patch).map(([k,v])=><label key={k}>{k}<textarea value={v} onChange={e=>setPatch(p=>({...p,[k]:e.target.value}))}/></label>)}</div><div className="tc-modal-actions"><button onClick={onClose}>Cancel</button><button className="primary" onClick={save}>Save & Update</button></div></div></div>}
function StockPage({rows,onAdd,onEdit}){return <section className="tc-admin-page"><div className="tc-data-head"><div><small>PAYMENT LINKS</small><h2>Payment Link Stock</h2><span>{rows.length} records</span></div><button className="tc-add" onClick={onAdd}><Plus size={15}/> Add stock</button></div><DataPage title="Payment Link Stock" sheet="PaymentLinkStock" rows={rows} columns={rows[0]?Object.keys(rows[0]):['PaymentLinkStockID','Denomination','Link','Label','Status']} idField="PaymentLinkStockID" query="" setQuery={()=>{}} filter={{}} setFilter={()=>{}} showFilter={false} setShowFilter={()=>{}} onEdit={onEdit}/></section>}
function StockModal({token,onClose,onDone,onError}){const[amount,setAmount]=useState(''),[links,setLinks]=useState('');const save=async()=>{try{const list=links.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(![500,1000,1500,2000].includes(Number(amount)))throw Error('Select ₹500, ₹1,000, ₹1,500 or ₹2,000.');if(!list.length)throw Error('Paste at least one payment link.');if(list.some(x=>!/^https:\/\//i.test(x)))throw Error('Each payment link must start with https://');await api.adminAddPaymentLinkStockBulk(token,list.map(link=>({denomination:Number(amount),link,label:`Pay ₹${Number(amount).toLocaleString('en-IN')}`})));onDone()}catch(e){onError(e.message)}};return <div className="tc-modal-backdrop"><div className="tc-modal"><button className="tc-modal-x" onClick={onClose}><X size={17}/></button><small>LINK STOCK</small><h3>Add payment links</h3><label>Amount<select value={amount} onChange={e=>setAmount(e.target.value)}><option value="">Select amount</option><option value="500">₹500</option><option value="1000">₹1,000</option><option value="1500">₹1,500</option><option value="2000">₹2,000</option></select></label><label>Payment links<textarea rows="7" value={links} onChange={e=>setLinks(e.target.value)} placeholder="Paste one Paytm link per line"/></label><div className="tc-modal-actions"><button onClick={onClose}>Cancel</button><button className="primary" onClick={save}>Add to Stock</button></div></div></div>}
function Reports({metrics}){return <section className="tc-admin-page"><div className="tc-admin-hero"><div><small>REPORTS</small><h2>Business control</h2><p>Live operational metrics.</p></div></div><div className="tc-kpis"><Kpi icon={ShoppingBag} label="Orders" value={metrics.orders}/><Kpi icon={CircleDollarSign} label="Revenue" value={MONEY(metrics.revenue)}/><Kpi icon={WalletCards} label="Cashback" value={MONEY(metrics.cashback)}/><Kpi icon={Link2} label="Links" value={metrics.availableLinks}/></div></section>}
function AllData({tables,onOpen}){return <section className="tc-admin-page"><div className="tc-admin-hero"><div><small>ALL DATA</small><h2>Every operational dataset.</h2><p>Filter and edit every operational menu from its data view.</p></div></div><div className="tc-data-cards">{SHEETS.filter(x=>x!=='AuditLogs').map(s=><button key={s} onClick={()=>onOpen(s)}><Database size={17}/><div><b>{LABEL[s]}</b><span>{tables[s]?.rows?.length||0} loaded records</span></div><ChevronRight size={14}/></button>)}</div><button className="tc-data-card-wide" onClick={()=>onOpen('AuditLogs')}><Activity size={17}/><div><b>Web Activity</b><span>Every user/admin API action plus edits and updates</span></div><ChevronRight size={14}/></button></section>}
function title(x){return x==='dashboard'?'Command Center':x==='work'?'Work Queue':x==='reports'?'Reports':x==='all-data'?'All Data':LABEL[x]||x}
