import {useEffect,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {Activity,ArrowUpRight,BarChart3,CheckCircle2,CircleDollarSign,Clock3,ExternalLink,Link2,PackageCheck,RefreshCw,ShoppingBag,Users,WalletCards} from 'lucide-react'
import {api} from './api'
import './admin-dashboard-redesign.css'

const MONEY=v=>`₹${Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2})`
const str=v=>String(v??'').trim()
const upper=v=>str(v).toUpperCase()
const num=v=>{const n=Number(str(v).replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0}
const status=r=>upper(r.Status||r.PaymentStatus||r.OrderStatus||r.State||r.InventoryStatus)
const amount=r=>num(r.Amount??r.TotalAmount??r.OrderValue??r.Total??r.Price??r.Denomination)
const rowsOf=r=>r?.table?.rows||[]
const nav=label=>{const b=[...document.querySelectorAll('.tc-admin-nav button')].find(x=>str(x.textContent).toLowerCase().includes(label.toLowerCase()));if(b)b.click()}
const load=async(token,sheet)=>{try{return rowsOf(await api.adminTable(token,sheet))}catch{return[]}}
function Metric({icon:Icon,label,value,sub,target,tone='neutral'}){return <button className={`tc-dr-metric ${tone}`} onClick={()=>nav(target)} type="button"><span className="tc-dr-icon"><Icon size={17}/></span><div><small>{label}</small><strong>{value}</strong><em>{sub}</em></div><ArrowUpRight size={15}/></button>}
function Action({icon:Icon,label,value,sub,target,tone='neutral'}){return <button className={`tc-dr-action ${tone}`} onClick={()=>nav(target)} type="button"><span><Icon size={16}/></span><div><b>{label}</b><strong>{value}</strong><small>{sub}</small></div><ArrowUpRight size={14}/></button>}
function Mini({label,value,sub,target}){return <button className="tc-dr-mini" onClick={()=>nav(target)} type="button"><span>{label}</span><b>{value}</b><small>{sub}</small></button>}
function Dashboard(){
 const[d,setD]=useState(null),[loading,setLoading]=useState(true)
 const token=localStorage.getItem('tc_erp_session')||''
 useEffect(()=>{let alive=true;(async()=>{setLoading(true);const names=['Orders','Payments','PaymentLinkStock','PaymentLinkRequests','Vouchers','CashbackWallet','CashbackTransactions','WalletRedemptions','Users','Products','Brands','Cart','Notifications','OTP','UserSessions','AuditLogs'];const values=await Promise.all(names.map(s=>load(token,s)));const x={};names.forEach((n,i)=>x[n]=values[i]);let dashboard={};try{dashboard=await api.adminDashboard(token)}catch{};let work=[];try{work=(await api.adminWorklist(token))?.items||[]}catch{};if(alive){setD({x,dashboard,work});setLoading(false)}})();return()=>{alive=false}},[token])
 if(loading&&!d)return <section className="tc-dr-page"><div className="tc-dr-loading"><RefreshCw className="tc-spin" size={18}/> Loading live operations data…</div></section>
 const x=d?.x||{},work=d?.work||[],orders=x.Orders||[],payments=x.Payments||[],stock=x.PaymentLinkStock||[],requests=x.PaymentLinkRequests||[],vouchers=x.Vouchers||[],wallet=x.CashbackWallet||[],cash=x.CashbackTransactions||[],payouts=x.WalletRedemptions||[],users=x.Users||[],products=x.Products||[],brands=x.Brands||[],cart=x.Cart||[],notifications=x.Notifications||[],otp=x.OTP||[],sessions=x.UserSessions||[],audit=x.AuditLogs||[]
 const verifiedPayments=payments.filter(r=>['VERIFIED','SUCCESS','PAID','COMPLETED','CONFIRMED'].includes(status(r))),pendingPayments=payments.filter(r=>['PENDING','INITIATED','PROCESSING','REQUESTED','PENDING_PAYMENT'].includes(status(r))),failedPayments=payments.filter(r=>['FAILED','ERROR','REJECTED','CANCELLED'].includes(status(r))),delivered=vouchers.filter(r=>['DELIVERED','SENT','COMPLETED','SUCCESS'].includes(status(r))),pendingVouchers=vouchers.filter(r=>['PENDING','PROCESSING','REQUESTED','INITIATED'].includes(status(r))),availableStock=stock.filter(r=>['AVAILABLE','READY','ACTIVE','IN_STOCK',''].includes(status(r))),reservedStock=stock.filter(r=>status(r)==='RESERVED'),usedStock=stock.filter(r=>['USED','CONSUMED'].includes(status(r))),pendingRequests=requests.filter(r=>['PENDING','REQUESTED','PROCESSING','INITIATED'].includes(status(r))),pendingPayouts=payouts.filter(r=>['PENDING','REQUESTED','PROCESSING','INITIATED'].includes(status(r)))
 const walletBalance=wallet.reduce((s,r)=>s+num(r.Balance??r.AvailableBalance),0),sales=verifiedPayments.reduce((s,r)=>s+num(r.Amount??r.PaidAmount??r.TotalAmount),0),stockValue=availableStock.reduce((s,r)=>s+amount(r),0),unread=notifications.filter(r=>['UNREAD','0','FALSE','PENDING'].includes(upper(r.Read??r.Status))).length,otpFailed=otp.filter(r=>['FAILED','ERROR','INVALID'].includes(status(r))||upper(r.Success)==='FALSE').length,sessionActive=sessions.filter(r=>['ACTIVE','TRUE','YES',''].includes(status(r))&&upper(r.Revoked)!=='TRUE').length,auditErrors=audit.filter(r=>['FAILED','ERROR','REJECTED'].includes(status(r))||upper(r.Success)==='FALSE').length
 const denom=[500,1000,1500,2000].map(v=>({v,count:stock.filter(r=>num(r.Denomination??r.Amount??r.Value??r.Price)===v&&['AVAILABLE','READY','ACTIVE','IN_STOCK',''].includes(status(r))).length}))
 return <section className="tc-dr-page"><div className="tc-dr-top"><div><span>TRUSTED CIRCLE · OPERATIONS</span><h1>Command Center</h1><p>Live business position, operational workload and system health — in one view.</p></div><button onClick={()=>window.location.reload()}><RefreshCw size={15}/> Refresh data</button></div>
  <div className="tc-dr-metrics"><Metric icon={CircleDollarSign} label="Verified Sales" value={MONEY(sales||d?.dashboard?.metrics?.revenue)} sub={`${verifiedPayments.length} verified payments`} target="Payments" tone="money"/><Metric icon={ShoppingBag} label="Orders" value={orders.length||d?.dashboard?.metrics?.orders||0} sub="All customer orders" target="Orders" tone="blue"/><Metric icon={Clock3} label="Payment Pending" value={pendingPayments.length} sub="Waiting for verification" target="Payments" tone="warn"/><Metric icon={Link2} label="Links Available" value={availableStock.length||d?.dashboard?.metrics?.availableLinks||0} sub={MONEY(stockValue)+" stock value"} target="Link Stock" tone="green"/><Metric icon={WalletCards} label="Wallet Balance" value={MONEY(walletBalance)} sub={`${wallet.length} customer wallets`} target="Cashback Wallet" tone="purple"/><Metric icon={Activity} label="Open Work" value={work.length} sub="Requires admin action" target="Work Queue" tone="danger"/></div>
  <div className="tc-dr-grid-main"><div className="tc-dr-card tc-dr-operations"><div className="tc-dr-head"><div><span>OPERATIONS</span><h2>What needs attention?</h2></div><button onClick={()=>nav('Work Queue')}>Open queue <ExternalLink size={13}/></button></div><div className="tc-dr-actions"><Action icon={CircleDollarSign} label="Payments to verify" value={pendingPayments.length} sub={MONEY(pendingPayments.reduce((s,r)=>s+num(r.Amount),0))+' awaiting verification'} target="Payments" tone="warn"/><Action icon={Link2} label="Link requests" value={pendingRequests.length} sub="Requests waiting for fulfilment" target="Link Requests" tone="blue"/><Action icon={PackageCheck} label="Vouchers pending" value={pendingVouchers.length} sub={`${delivered.length} already delivered`} target="Vouchers" tone="purple"/><Action icon={WalletCards} label="Cashback payouts" value={pendingPayouts.length} sub={MONEY(pendingPayouts.reduce((s,r)=>s+amount(r),0))+' awaiting processing'} target="Cashback Payouts" tone="green"/></div></div><div className="tc-dr-card"><div className="tc-dr-head"><div><span>PAYMENT LINK INVENTORY</span><h2>Stock by denomination</h2></div><button onClick={()=>nav('Link Stock')}>Manage <ExternalLink size={13}/></button></div><div className="tc-dr-denoms">{denom.map(dn=><Mini key={dn.v} label={`₹${dn.v.toLocaleString('en-IN')}`} value={dn.count} sub="available" target="Link Stock"/>)}</div><div className="tc-dr-stock-summary"><span><b>{availableStock.length}</b> Available</span><span><b>{reservedStock.length}</b> Reserved</span><span><b>{usedStock.length}</b> Used</span></div></div></div>
  <div className="tc-dr-grid-3"><div className="tc-dr-card"><div className="tc-dr-head"><div><span>SALES PIPELINE</span><h2>Order position</h2></div><button onClick={()=>nav('Orders')}>Orders <ExternalLink size={13}/></button></div><div className="tc-dr-bars"><div><span>Total orders</span><b>{orders.length}</b></div><div><span>Paid / completed</span><b>{orders.filter(r=>['PAID','COMPLETED','DELIVERED','FULFILLED'].includes(status(r))).length}</b></div><div><span>Payment pending</span><b>{pendingPayments.length}</b></div><div><span>Failed payments</span><b>{failedPayments.length}</b></div></div></div><div className="tc-dr-card"><div className="tc-dr-head"><div><span>CUSTOMERS & CATALOG</span><h2>Platform scale</h2></div><button onClick={()=>nav('Shoppers')}>Customers <ExternalLink size={13}/></button></div><div className="tc-dr-mini-grid"><Mini label="Shoppers" value={users.length} sub="accounts" target="Shoppers"/><Mini label="Products" value={products.length} sub="catalog" target="Products"/><Mini label="Brands" value={brands.length} sub="catalogue" target="Brands"/><Mini label="Cart lines" value={cart.length} sub="current" target="Cart"/></div></div><div className="tc-dr-card"><div className="tc-dr-head"><div><span>SYSTEM HEALTH</span><h2>Control room</h2></div><button onClick={()=>nav('Web Activity')}>Activity <ExternalLink size={13}/></button></div><div className="tc-dr-health"><Mini label="Unread notifications" value={unread} sub="needs review" target="Notifications"/><Mini label="OTP failures" value={otpFailed} sub="security events" target="OTP Logs"/><Mini label="Active sessions" value={sessionActive} sub="current" target="Sessions"/><Mini label="Activity errors" value={auditErrors} sub="audit records" target="Web Activity"/></div></div></div>
  <div className="tc-dr-footer-grid"><button onClick={()=>nav('Payments')}><CheckCircle2 size={16}/><div><b>Payment verification</b><span>{verifiedPayments.length} verified · {failedPayments.length} failed</span></div><ArrowUpRight size={14}/></button><button onClick={()=>nav('Cashback History')}><BarChart3 size={16}/><div><b>Cashback ledger</b><span>{cash.length} transactions · {MONEY(cash.reduce((s,r)=>s+Math.abs(amount(r)),0))} value</span></div><ArrowUpRight size={14}/></button><button onClick={()=>nav('Cashback Payouts')}><WalletCards size={16}/><div><b>Payout processing</b><span>{pendingPayouts.length} pending · {MONEY(payouts.reduce((s,r)=>s+amount(r),0))} total</span></div><ArrowUpRight size={14}/></button><button onClick={()=>nav('Reports')}><BarChart3 size={16}/><div><b>Business reports</b><span>Open performance and operational insights</span></div><ArrowUpRight size={14}/></button></div></section>
}
function AdminDashboardRedesign(){useEffect(()=>{let root=null,host=null,timer;const cleanup=()=>{if(root){root.unmount();root=null}host?.remove();host=null};const run=()=>{const main=document.querySelector('.tc-admin-main');if(!main)return;const heading=str(main.querySelector('.tc-admin-header h1')?.textContent).toLowerCase(),page=main.querySelector('.tc-admin-page');if(heading!=='dashboard'||!page){cleanup();return}if(host&&host.isConnected)return;page.classList.add('tc-dashboard-redesigned');page.querySelectorAll(':scope > *').forEach(el=>{if(!el.classList.contains('tc-dashboard-redesign-host'))el.classList.add('tc-dashboard-original-hidden')});host=document.createElement('div');host.className='tc-dashboard-redesign-host';page.appendChild(host);root=createRoot(host);root.render(<Dashboard/>)};const schedule=()=>{clearTimeout(timer);timer=setTimeout(run,80)};schedule();const observer=new MutationObserver(schedule);observer.observe(document.body,{subtree:true,childList:true,characterData:true});return()=>{clearTimeout(timer);observer.disconnect();cleanup()}},[]);return null}
export default AdminDashboardRedesign
