import { useCallback,useEffect,useMemo,useState } from 'react'
import { ArrowRight,Search,ShoppingBag,UserRound,X } from 'lucide-react'
import { api } from './api'
import GlobalLoading from './GlobalLoading'
import WalletBadge from './components/WalletBadge'
import HomePage from './pages/HomePage'
import BrandsPage from './pages/BrandsPage'
import VouchersPage from './pages/VouchersPage'
import VoucherPage from './pages/VoucherPage'
import CartPage from './pages/CartPage'
import CheckoutPage from './pages/CheckoutPage'
import ProfilePage from './pages/ProfilePage'
import OrdersPage from './pages/OrdersPage'
import WalletPage from './pages/WalletPage'
import OrderPlacedPage from './pages/OrderPlacedPage'
import InfoPage from './pages/InfoPage'
import './app.css'
import './mobile.css'
import './site-overrides.css'
const LOGO_URL='https://raw.githubusercontent.com/trustedcircle2026-cloud/Trusted-Circle/main/Logo%20new.jpg'
const QR_URL='https://raw.githubusercontent.com/trustedcircle2026-cloud/Trusted-Circle/main/UPIQR.jpg'
const WHATSAPP_NUMBER='919442456039'
function readRoute(){const raw=window.location.hash.replace(/^#\/?/,'')||'home';const[path,id]=raw.split('/');return{path,id:id||''}}
const friendlyApiError=error=>{const message=String(error?.message||'Request failed.');if(/unknown api action/i.test(message))return'The backend needs the latest deployment.';return message}
export default function App(){
 const[route,setRoute]=useState(readRoute),[products,setProducts]=useState([]),[allProducts,setAllProducts]=useState([]),[brands,setBrands]=useState([]),[cart,setCart]=useState([]),[orders,setOrders]=useState([]),[user,setUser]=useState(null),[token,setToken]=useState(()=>localStorage.getItem('tc_session')||''),[query,setQuery]=useState(''),[brandFilter,setBrandFilter]=useState(''),[liked,setLiked]=useState(()=>{try{return JSON.parse(localStorage.getItem('tc_liked')||'[]')}catch{return[]}}),[authOpen,setAuthOpen]=useState(false),[authStep,setAuthStep]=useState('email'),[email,setEmail]=useState(''),[otp,setOtp]=useState(''),[authMessage,setAuthMessage]=useState(''),[profileOpen,setProfileOpen]=useState(false),[profileName,setProfileName]=useState(''),[paymentMethod,setPaymentMethod]=useState('upiapps'),[lastOrder,setLastOrder]=useState(null)
 const navigate=useCallback((path,id='')=>{const target=id?`#/${path}/${id}`:`#/${path}`;if(window.location.hash!==target)window.location.hash=target;else setRoute({path,id});window.scrollTo({top:0,behavior:'smooth'})},[])
 useEffect(()=>{const onHash=()=>setRoute(readRoute());window.addEventListener('hashchange',onHash);return()=>window.removeEventListener('hashchange',onHash)},[])
 const brandName=useCallback(id=>brands.find(b=>String(b.BrandID)===String(id))?.Name||'Gift Voucher',[brands])
 const loadCatalog=useCallback(async(q=query,brand=brandFilter)=>{const data=await api.products(q.trim(),brand);setProducts(data?.items||[])},[query,brandFilter])
 const loadAllProducts=useCallback(async()=>{const data=await api.products('','');const items=data?.items||[];setAllProducts(items);return items},[])
 const loadCart=useCallback(async currentToken=>{if(!currentToken){setCart([]);return}const data=await api.cart(currentToken);setCart(data?.items||[])},[])
 const loadOrders=useCallback(async currentToken=>{if(!currentToken){setOrders([]);return}const data=await api.orders(currentToken);setOrders(data?.items||[])},[])
 useEffect(()=>{let active=true;(async()=>{try{const[brandData,productData]=await Promise.all([api.brands(),api.products('','')]);if(!active)return;setBrands(brandData?.items||[]);setProducts(productData?.items||[]);setAllProducts(productData?.items||[]);if(token){try{const me=await api.me(token);if(!active)return;setUser(me);setProfileName(me.name||'');if(!me.name)setProfileOpen(true);Promise.all([loadCart(token),loadOrders(token)]).catch(()=>{})}catch{localStorage.removeItem('tc_session');setToken('');setUser(null);setCart([])}}}catch(error){console.warn('Trusted Circle startup:',error.message)}})();return()=>{active=false}},[])
 useEffect(()=>{if(!['vouchers','home'].includes(route.path))return;const timer=setTimeout(()=>{loadCatalog(query,brandFilter).catch(()=>{})},250);return()=>clearTimeout(timer)},[query,brandFilter,route.path])
 const cartDetailed=useMemo(()=>cart.map(item=>{const product=allProducts.find(p=>String(p.ProductID)===String(item.ProductID));if(!product)return null;const denomination=Number(item.Denomination||product.FaceValue||0);return{...item,product,denomination,unitPrice:denomination}}).filter(Boolean),[cart,allProducts])
 const cartCount=useMemo(()=>cart.reduce((sum,item)=>sum+Number(item.Quantity||0),0),[cart])
 const subtotal=useMemo(()=>cartDetailed.reduce((sum,item)=>sum+item.denomination*Number(item.Quantity||0),0),[cartDetailed])
 const cashback=useMemo(()=>cartDetailed.reduce((sum,item)=>sum+(item.denomination*Number(item.Quantity||0)*Number(item.product.DiscountPercent||0)/100),0),[cartDetailed])
 const total=subtotal
 const currentProduct=useMemo(()=>allProducts.find(p=>String(p.ProductID)===String(route.id)),[allProducts,route.id])
 const toggleLike=id=>setLiked(current=>{const next=current.includes(id)?current.filter(x=>x!==id):[...current,id];localStorage.setItem('tc_liked',JSON.stringify(next));return next})
 const openAuth=()=>{setAuthStep('email');setOtp('');setAuthMessage('');setAuthOpen(true)}
 const requestOtp=async event=>{event.preventDefault();setAuthMessage('');try{await api.requestOtp(email);setAuthStep('otp');setAuthMessage(`Code sent to ${email}.`)}catch(error){setAuthMessage(friendlyApiError(error))}}
 const verifyOtp=async event=>{event.preventDefault();setAuthMessage('');try{const data=await api.verifyOtp(email,otp,'');localStorage.setItem('tc_session',data.session.token);setToken(data.session.token);setUser(data.user);setProfileName(data.user.name||'');setAuthOpen(false);if(!data.user.name)setProfileOpen(true);else navigate('home');Promise.all([loadCart(data.session.token),loadOrders(data.session.token)]).catch(()=>{})}catch(error){setAuthMessage(friendlyApiError(error))}}
 const saveProfile=async event=>{event.preventDefault();setAuthMessage('');try{const data=await api.profileUpdate(token,profileName);setUser(data);setProfileOpen(false);navigate('home')}catch(error){setAuthMessage(friendlyApiError(error))}}
 const logout=async()=>{try{if(token)await api.logout(token)}catch{}localStorage.removeItem('tc_session');setToken('');setUser(null);setCart([]);setOrders([]);setProfileOpen(false);navigate('home')}
 const addToCart=async(product,quantity=1,denomination=1000)=>{if(!token){openAuth();return}try{const data=await api.cartAdd(token,product.ProductID,quantity,denomination);setCart(data?.items||[]);await loadAllProducts()}catch(error){setAuthMessage(friendlyApiError(error))}}
 const changeQty=async(item,quantity)=>{if(quantity<1)return removeItem(item);try{const data=await api.cartUpdate(token,item.CartID,quantity);setCart(data?.items||[])}catch(error){setAuthMessage(friendlyApiError(error))}}
 const removeItem=async item=>{try{const data=await api.cartRemove(token,item.CartID);setCart(data?.items||[])}catch(error){setAuthMessage(friendlyApiError(error))}}
 const checkout=()=>{if(!token){openAuth();return}if(cartDetailed.length&&subtotal<=2000){setPaymentMethod('upiapps');navigate('checkout')}}
 const createPendingOrder=async(method='upiapps')=>{if(subtotal>2000){setAuthMessage('Maximum order value is ₹2,000.');return}const snapshot={items:cartDetailed.map(i=>({title:i.product.Title,brand:brandName(i.product.BrandID),quantity:Number(i.Quantity||0),faceValue:Number(i.denomination||0),total:Number(i.denomination||0)*Number(i.Quantity||0)})),subtotal,cashback,total,user:{name:user?.name||'',email:user?.email||''}};try{const data=await api.placeOrder(token,method);setLastOrder({...data,snapshot});await Promise.all([loadCart(token),loadOrders(token)]);navigate('order-placed')}catch(error){setAuthMessage(friendlyApiError(error))}}
 const onBrandBrowse=id=>{setBrandFilter(id||'');navigate('vouchers')}
 const orderForContact=lastOrder?.order?.order||lastOrder?.order||{},contactItems=lastOrder?.snapshot?.items||[]
 const orderText=`Hello Trusted Circle,\n\nOrder Number: ${orderForContact.OrderNumber||'Pending'}\nCustomer: ${lastOrder?.snapshot?.user?.name||user?.name||''}\nEmail: ${lastOrder?.snapshot?.user?.email||user?.email||''}\n\n${contactItems.map(i=>`• ${i.brand} — ${i.title} × ${i.quantity} — ₹${i.total.toLocaleString('en-IN')}`).join('\n')}\n\nTotal: ₹${Number(lastOrder?.snapshot?.total||orderForContact.Total||0).toLocaleString('en-IN')}`
 const emailHref=`mailto:info@trustedcircle.in?subject=${encodeURIComponent(`Trusted Circle Order ${orderForContact.OrderNumber||''}`)}&body=${encodeURIComponent(orderText)}`
 const whatsappHref=`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(orderText)}`
 return <div className="app-root"><GlobalLoading/><header className="new-header"><button className="header-brand" onClick={()=>navigate('home')}><span className="header-logo-white"><img src={LOGO_URL} alt="Trusted Circle"/></span><span>Trusted<span>Circle</span></span></button><nav className="desktop-nav"><button onClick={()=>navigate('home')}>Home</button><button onClick={()=>navigate('vouchers')}>Gift Vouchers</button><button onClick={()=>navigate('brands')}>Brands</button><button onClick={()=>navigate('info','how-it-works')}>How It Works</button><button onClick={()=>navigate('info','help')}>Help</button></nav><div className="header-actions"><button className="header-tool" onClick={()=>navigate('vouchers')} aria-label="Search vouchers"><Search size={19}/></button>{user&&<WalletBadge token={token} onOpen={()=>navigate('wallet')}/>}<button className="header-tool cart-tool" onClick={()=>navigate('cart')} aria-label="Cart"><ShoppingBag size={19}/><b>{cartCount}</b></button>{user?<button className="account-tool" onClick={()=>navigate('profile')}><UserRound size={16}/><span>{user.name||'Profile'}</span></button>:<button className="login-tool" onClick={openAuth}>Login <ArrowRight size={15}/></button>}</div></header>
 {route.path==='home'&&<HomePage brands={brands} products={products} brandName={brandName} liked={liked} onLike={toggleLike} onAdd={addToCart} onOpen={id=>navigate('voucher',id)} onBrowse={(page='vouchers',filter='')=>{if(filter)setBrandFilter(filter);navigate(page)}}/>}
 {route.path==='brands'&&<BrandsPage brands={brands} onBrowse={onBrandBrowse}/>}
 {route.path==='vouchers'&&<VouchersPage products={products} brands={brands} brandFilter={brandFilter} setBrandFilter={setBrandFilter} query={query} setQuery={setQuery} brandName={brandName} liked={liked} onLike={toggleLike} onAdd={addToCart} onOpen={id=>navigate('voucher',id)}/>}
 {route.path==='voucher'&&<VoucherPage product={currentProduct} brandName={currentProduct?brandName(currentProduct.BrandID):''} onBack={()=>navigate('vouchers')} onAdd={addToCart}/>}
 {route.path==='cart'&&<CartPage items={cartDetailed} brandName={brandName} subtotal={subtotal} cashback={cashback} total={total} onQty={changeQty} onRemove={removeItem} onContinue={()=>navigate('vouchers')} onCheckout={checkout}/>}
 {route.path==='checkout'&&<CheckoutPage user={user} items={cartDetailed} total={total} savings={cashback} paymentMethod={paymentMethod} setPaymentMethod={setPaymentMethod} qrUrl={QR_URL} logoUrl={LOGO_URL} onBack={()=>navigate('cart')} onCreateOrder={createPendingOrder}/>}
 {route.path==='profile'&&user&&<ProfilePage user={user} name={profileName} setName={setProfileName} onSave={saveProfile} onLogout={logout} onOrders={()=>navigate('orders')}/>}
 {route.path==='orders'&&<OrdersPage orders={orders} onBack={()=>navigate('vouchers')}/>}
 {route.path==='wallet'&&user&&<WalletPage token={token} onBack={()=>navigate('home')}/>}
 {route.path==='order-placed'&&<OrderPlacedPage order={lastOrder} onOrders={()=>navigate('orders')} onShop={()=>navigate('vouchers')} emailHref={emailHref} whatsappHref={whatsappHref}/>} {route.path==='info'&&<InfoPage type={route.id||'about'} onNavigate={navigate}/>} 
 <footer className="site-footer"><div className="footer-main"><div className="footer-brand-block"><button className="footer-brand" onClick={()=>navigate('home')}><span className="footer-logo-white"><img src={LOGO_URL} alt="Trusted Circle"/></span><strong>TrustedCircle</strong></button><p>Gift vouchers with cashback after verified payment.</p><div className="footer-contact"><span>info@trustedcircle.in</span><span>+91 94424 56039</span></div></div><div className="footer-col"><h4>Shop</h4><button onClick={()=>navigate('vouchers')}>Gift Vouchers</button><button onClick={()=>navigate('brands')}>Brands</button><button onClick={()=>navigate('info','how-it-works')}>How It Works</button></div><div className="footer-col"><h4>Trusted Circle</h4><button onClick={()=>navigate('info','about')}>About Us</button><button onClick={()=>navigate('info','help')}>Help Centre</button><button onClick={()=>navigate('info','contact')}>Contact</button><button onClick={()=>navigate('info','faq')}>FAQs</button></div><div className="footer-col"><h4>Policies</h4><button onClick={()=>navigate('info','terms')}>Terms & Conditions</button><button onClick={()=>navigate('info','privacy')}>Privacy Policy</button><button onClick={()=>navigate('info','refund')}>Refund & Cancellation</button>{user&&<button onClick={()=>navigate('orders')}>My Orders</button>}</div></div><div className="footer-bottom"><span>© 2026 Trusted Circle. All rights reserved.</span><a href="#/erp">ERP Login</a></div></footer>
 {authOpen&&<div className="modal-layer"><div className="auth-page-modal"><button className="modal-x" onClick={()=>setAuthOpen(false)} aria-label="Close login"><X size={17}/></button><span className="modal-logo-white"><img src={LOGO_URL} alt="Trusted Circle"/></span>{authStep==='email'?<><span className="eyebrow">ACCOUNT ACCESS</span><h2>Welcome to Trusted Circle</h2><p>Enter your email to continue.</p><form onSubmit={requestOtp}><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" autoComplete="email"/><button className="btn-primary wide" type="submit">Continue <ArrowRight size={15}/></button></form></>:<><span className="eyebrow">VERIFY EMAIL</span><h2>Enter your OTP</h2><p>We sent a code to <strong>{email}</strong>.</p><form onSubmit={verifyOtp}><input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength="6" required value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,''))} placeholder="6-digit OTP"/><button className="btn-primary wide" type="submit">Verify & continue <ArrowRight size={15}/></button><button className="btn-quiet wide" type="button" onClick={()=>setAuthStep('email')}>Use another email</button></form></>}{authMessage&&<div className="form-message" role="alert">{authMessage}</div>}</div></div>}
 {profileOpen&&user&&<div className="modal-layer"><div className="profile-complete-modal"><span className="modal-logo-white"><img src={LOGO_URL} alt="Trusted Circle"/></span><span className="eyebrow">PROFILE</span><h2>Add your name</h2><p>We use your name on your account and voucher emails.</p><form onSubmit={saveProfile}><input required minLength={2} value={profileName} onChange={e=>setProfileName(e.target.value)} placeholder="Your full name" autoComplete="name"/><button className="btn-primary wide" type="submit">Save <ArrowRight size={15}/></button></form>{authMessage&&<div className="form-message" role="alert">{authMessage}</div>}</div></div>}
 </div>
}
