import React,{useEffect,useMemo,useState} from 'react'
import {Activity,ArrowLeft,BookOpen,Building2,ChevronDown,ChevronRight,FileText,Landmark,LayoutDashboard,LogOut,Menu,Plus,RefreshCw,Scale,Settings,Users,WalletCards,X} from 'lucide-react'
import {BOOKS_API_URL,BOOKS_SESSION_KEY} from './books-config'
import './books-workspace.css'

const LOGO_URL='https://raw.githubusercontent.com/trustedcircle2026-cloud/Trusted-Circle/main/Logo%20new.jpg'

async function booksRequest(action,payload={}){
 const r=await fetch(BOOKS_API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...payload})})
 const text=await r.text();let json={};try{json=JSON.parse(text)}catch{throw new Error('Books backend returned an invalid response.')}
 if(!r.ok||json.ok===false)throw new Error(json.error?.message||json.message||'Books request failed.')
 return json.data??json
}
const money=v=>`₹${Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`
const today=()=>new Date().toISOString().slice(0,10)
const currentFY=()=>{const d=new Date(),y=d.getFullYear();return d.getMonth()+1>=4?`${y}-${y+1}`:`${y-1}-${y}`}

function Field({label,...p}){return <label className="bw-field"><span>{label}</span><input {...p}/></label>}
function Select({label,children,...p}){return <label className="bw-field"><span>{label}</span><select {...p}>{children}</select></label>}
function Empty({title,text,action,onAction}){return <div className="bw-empty"><div><BookOpen size={22}/></div><b>{title}</b><p>{text}</p>{action&&<button className="bw-primary" onClick={onAction}><Plus size={16}/>{action}</button>}</div>}

function Organisation({org,onSaved}){
 const[d,setD]=useState(org||{}),[busy,setBusy]=useState(false),[msg,setMsg]=useState('')
 useEffect(()=>setD(org||{}),[org])
 const save=async e=>{e.preventDefault();setBusy(true);setMsg('');try{const x=await booksRequest('booksSaveOrganisation',{token:localStorage.getItem(BOOKS_SESSION_KEY),organisation:d});onSaved(x.organisation);setMsg('Organisation profile saved.')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 return <section className="bw-section"><div className="bw-page-head"><div><div className="bw-kicker">SETUP</div><h1>Organisation Profile</h1><p>Your legal identity, accounting period and GST-ready business settings.</p></div></div><form className="bw-card bw-form" onSubmit={save}><div className="bw-card-title"><Building2 size={18}/><span>Business details</span></div><div className="bw-form-grid"><Field label="Organisation name" required value={d.Name||''} onChange={e=>setD({...d,Name:e.target.value})}/><Field label="Legal name" value={d.LegalName||''} onChange={e=>setD({...d,LegalName:e.target.value})}/><Field label="GSTIN" value={d.GSTIN||''} onChange={e=>setD({...d,GSTIN:e.target.value.toUpperCase()})}/><Field label="PAN" value={d.PAN||''} onChange={e=>setD({...d,PAN:e.target.value.toUpperCase()})}/><Field label="CIN" value={d.CIN||''} onChange={e=>setD({...d,CIN:e.target.value.toUpperCase()})}/><Field label="Email" type="email" value={d.Email||''} onChange={e=>setD({...d,Email:e.target.value})}/><Field label="Phone" value={d.Phone||''} onChange={e=>setD({...d,Phone:e.target.value})}/><Field label="Pincode" value={d.Pincode||''} onChange={e=>setD({...d,Pincode:e.target.value})}/><Field label="State" value={d.State||''} onChange={e=>setD({...d,State:e.target.value})}/><Select label="Base currency" value={d.BaseCurrency||'INR'} onChange={e=>setD({...d,BaseCurrency:e.target.value})}><option>INR</option><option>USD</option><option>EUR</option><option>GBP</option></Select><Field label="Books start date" type="date" value={d.BooksStartDate||''} onChange={e=>setD({...d,BooksStartDate:e.target.value})}/><Select label="Financial year starts" value={d.FinancialYearStartMonth||'4'} onChange={e=>setD({...d,FinancialYearStartMonth:e.target.value})}><option value="4">April</option><option value="1">January</option></Select></div><Field label="Registered address" value={d.Address||''} onChange={e=>setD({...d,Address:e.target.value})}/><div className="bw-actions"><button className="bw-primary" disabled={busy}>{busy?'Saving…':'Save organisation'}</button>{msg&&<span className="bw-success">{msg}</span>}</div></form></section>
}

function Accounts(){
 const[rows,setRows]=useState([]),[busy,setBusy]=useState(true),[show,setShow]=useState(false),[msg,setMsg]=useState(''),[form,setForm]=useState({Type:'ASSET',NormalBalance:'DEBIT',OpeningBalance:0})
 const load=async()=>{setBusy(true);try{const x=await booksRequest('booksListAccounts',{token:localStorage.getItem(BOOKS_SESSION_KEY)});setRows(x.accounts||[])}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 useEffect(()=>{load()},[])
 const save=async e=>{e.preventDefault();try{await booksRequest('booksSaveAccount',{token:localStorage.getItem(BOOKS_SESSION_KEY),account:form});setShow(false);setForm({Type:'ASSET',NormalBalance:'DEBIT',OpeningBalance:0});load()}catch(e){setMsg(e.message)}}
 return <section className="bw-section"><PageHead kicker="ACCOUNTS" title="Chart of Accounts" text="Maintain your ledger structure before posting transactions." button="New account" onClick={()=>setShow(true)} refresh={load}/>{msg&&<div className="bw-alert">{msg}</div>}<div className="bw-card"><table className="bw-table"><thead><tr><th>Code</th><th>Account</th><th>Type</th><th>Normal balance</th><th>Opening balance</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.AccountID}><td>{r.Code||'—'}</td><td><b>{r.Name}</b></td><td>{r.Type}</td><td>{r.NormalBalance}</td><td>{money(r.OpeningBalance)}</td><td><span className="bw-status">Active</span></td></tr>)}</tbody></table>{!busy&&!rows.length&&<Empty title="No accounts yet" text="Create the first ledger account for this organisation." action="Create account" onAction={()=>setShow(true)}/>}</div>{show&&<Modal title="Create ledger account" onClose={()=>setShow(false)}><form className="bw-form" onSubmit={save}><div className="bw-form-grid"><Field label="Account code" value={form.Code||''} onChange={e=>setForm({...form,Code:e.target.value})}/><Field label="Account name" required value={form.Name||''} onChange={e=>setForm({...form,Name:e.target.value})}/><Select label="Account type" value={form.Type} onChange={e=>setForm({...form,Type:e.target.value,NormalBalance:['ASSET','EXPENSE'].includes(e.target.value)?'DEBIT':'CREDIT'})}><option>ASSET</option><option>LIABILITY</option><option>EQUITY</option><option>INCOME</option><option>EXPENSE</option></Select><Select label="Normal balance" value={form.NormalBalance} onChange={e=>setForm({...form,NormalBalance:e.target.value})}><option>DEBIT</option><option>CREDIT</option></Select><Field label="Opening balance" type="number" step="0.01" value={form.OpeningBalance} onChange={e=>setForm({...form,OpeningBalance:e.target.value})}/><Field label="Opening balance date" type="date" value={form.OpeningBalanceDate||''} onChange={e=>setForm({...form,OpeningBalanceDate:e.target.value})}/></div><button className="bw-primary">Save account</button></form></Modal>}</section>
}

function Journal(){
 const[accounts,setAccounts]=useState([]),[date,setDate]=useState(today()),[narr,setNarr]=useState(''),[lines,setLines]=useState([{AccountID:'',Debit:'',Credit:''},{AccountID:'',Debit:'',Credit:''}]),[busy,setBusy]=useState(false),[msg,setMsg]=useState('')
 useEffect(()=>{booksRequest('booksListAccounts',{token:localStorage.getItem(BOOKS_SESSION_KEY)}).then(x=>setAccounts(x.accounts||[])).catch(e=>setMsg(e.message))},[])
 const update=(i,k,v)=>setLines(lines.map((l,j)=>j===i?{...l,[k]:v}:l));const add=()=>setLines([...lines,{AccountID:'',Debit:'',Credit:''}]);const remove=i=>setLines(lines.filter((_,j)=>j!==i));const debit=lines.reduce((s,l)=>s+Number(l.Debit||0),0),credit=lines.reduce((s,l)=>s+Number(l.Credit||0),0),balanced=Math.abs(debit-credit)<.005&&debit>0
 const post=async e=>{e.preventDefault();if(!balanced){setMsg('Journal must have equal debit and credit totals.');return}setBusy(true);try{const x=await booksRequest('booksCreateJournal',{token:localStorage.getItem(BOOKS_SESSION_KEY),journal:{JournalDate:date,Narration:narr,lines}});setMsg(`Posted ${x.journalNumber} successfully.`);setNarr('');setLines([{AccountID:'',Debit:'',Credit:''},{AccountID:'',Debit:'',Credit:''}])}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 return <section className="bw-section"><PageHead kicker="BOOKS OF ACCOUNTS" title="Journal Entry" text="Post balanced double-entry transactions to the general ledger."/><form className="bw-card bw-form" onSubmit={post}><div className="bw-form-grid"><Field label="Journal date" type="date" required value={date} onChange={e=>setDate(e.target.value)}/><Field label="Narration" required value={narr} onChange={e=>setNarr(e.target.value)}/></div><div className="bw-journal"><div className="bw-journal-head"><span>Account</span><span>Description</span><span>Debit</span><span>Credit</span><span></span></div>{lines.map((l,i)=><div className="bw-journal-row" key={i}><select value={l.AccountID} required onChange={e=>update(i,'AccountID',e.target.value)}><option value="">Select account</option>{accounts.map(a=><option key={a.AccountID} value={a.AccountID}>{a.Code?`${a.Code} · `:''}{a.Name}</option>)}</select><input placeholder="Description" value={l.Description||''} onChange={e=>update(i,'Description',e.target.value)}/><input type="number" step="0.01" min="0" value={l.Debit} onChange={e=>update(i,'Debit',e.target.value)}/><input type="number" step="0.01" min="0" value={l.Credit} onChange={e=>update(i,'Credit',e.target.value)}/><button type="button" className="bw-icon" onClick={()=>remove(i)} disabled={lines.length<=2}><X size={15}/></button></div>)}<button type="button" className="bw-secondary" onClick={add}><Plus size={15}/> Add line</button></div><div className="bw-totalbar"><span>Debit <b>{money(debit)}</b></span><span>Credit <b>{money(credit)}</b></span><strong className={balanced?'ok':'bad'}>{balanced?'Balanced':'Not balanced'}</strong></div>{msg&&<div className="bw-alert">{msg}</div>}<button className="bw-primary" disabled={busy}>{busy?'Posting…':'Post journal'}</button></form></section>
}

function Reports(){
 const[report,setReport]=useState('tb'),[fy,setFy]=useState(currentFY()),[data,setData]=useState(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState('')
 const load=async()=>{setBusy(true);setMsg('');try{const action=report==='tb'?'booksTrialBalance':report==='pl'?'booksProfitLoss':'booksBalanceSheet';setData(await booksRequest(action,{token:localStorage.getItem(BOOKS_SESSION_KEY),fiscalYear:fy}))}catch(e){setMsg(e.message);setData(null)}finally{setBusy(false)}}
 useEffect(()=>{load()},[report,fy])
 return <section className="bw-section"><PageHead kicker="REPORTING" title={report==='tb'?'Trial Balance':report==='pl'?'Profit & Loss':'Balance Sheet'} text="FY-wise financial reporting generated from posted double-entry journals." refresh={load}/><div className="bw-report-controls"><Select label="Financial year" value={fy} onChange={e=>setFy(e.target.value)}><option>{currentFY()}</option><option>{Number(currentFY().slice(0,4))-1}-{Number(currentFY().slice(0,4))}</option><option>{Number(currentFY().slice(0,4))-2}-{Number(currentFY().slice(0,4))-1}</option></Select><div className="bw-tabs"><button className={report==='tb'?'active':''} onClick={()=>setReport('tb')}>Trial Balance</button><button className={report==='pl'?'active':''} onClick={()=>setReport('pl')}>Profit & Loss</button><button className={report==='bs'?'active':''} onClick={()=>setReport('bs')}>Balance Sheet</button></div></div>{msg&&<div className="bw-alert">{msg}</div>}{busy?<div className="bw-loading">Loading report…</div>:report==='tb'?<div className="bw-card"><table className="bw-table"><thead><tr><th>Code</th><th>Account</th><th>Type</th><th className="num">Debit</th><th className="num">Credit</th><th className="num">Balance</th></tr></thead><tbody>{(data?.rows||[]).map(r=><tr key={r.accountId}><td>{r.code}</td><td><b>{r.name}</b></td><td>{r.type}</td><td className="num">{money(r.debit)}</td><td className="num">{money(r.credit)}</td><td className="num">{money(r.balance)}</td></tr>)}</tbody><tfoot><tr><th colSpan="3">Totals</th><th className="num">{money(data?.totalDebit)}</th><th className="num">{money(data?.totalCredit)}</th><th></th></tr></tfoot></table></div>:report==='pl'?<ReportCards items={[["Income",data?.income],["Expenses",data?.expenses],["Net profit",data?.netProfit]]}/>:<ReportCards items={[["Assets",data?.assets],["Liabilities",data?.liabilities],["Equity",data?.equity],["Retained profit",data?.retainedProfit],["Liabilities + Equity",data?.totalLiabilitiesAndEquity]]}/>}</section>
}
function ReportCards({items}){return <div className="bw-report-grid">{items.map(([a,v])=><div className="bw-report-card" key={a}><span>{a}</span><strong>{money(v)}</strong></div>)}</div>}
function PageHead({kicker,title,text,button,onClick,refresh}){return <div className="bw-page-head"><div><div className="bw-kicker">{kicker}</div><h1>{title}</h1><p>{text}</p></div><div className="bw-head-actions">{refresh&&<button className="bw-secondary" onClick={refresh}><RefreshCw size={15}/> Refresh</button>}{button&&<button className="bw-primary" onClick={onClick}><Plus size={15}/>{button}</button>}</div></div>}
function Modal({title,onClose,children}){return <div className="bw-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="bw-modal"><div className="bw-modal-head"><b>{title}</b><button className="bw-icon" onClick={onClose}><X size={18}/></button></div>{children}</div></div>}

const NAV=[{group:'COMMAND',items:[['dashboard','Dashboard',LayoutDashboard],['organisation','Organisation',Building2]]},{group:'ACCOUNTING',items:[['accounts','Chart of Accounts',BookOpen],['journal','Journal Entry',FileText],['reports','Financial Reports',Scale]]},{group:'SALES',items:[['customers','Customers',Users],['invoices','Invoices',FileText],['receipts','Receipts',WalletCards]]},{group:'PURCHASES',items:[['vendors','Vendors',Users],['bills','Bills',FileText],['expenses','Expenses',WalletCards]]},{group:'BANKING & TAX',items:[['banking','Banking',Landmark],['gst','GST / Tax',Scale],['inventory','Inventory',Activity]]},{group:'SYSTEM',items:[['settings','Settings',Settings]]}]

function Dashboard({org,user,onNavigate}){
 const cards=[['Receivables','₹0.00','Invoices due'],['Payables','₹0.00','Bills due'],['Cash & Bank','₹0.00','Connected balances'],['Net Profit','₹0.00','Current FY']]
 return <section className="bw-section"><div className="bw-hero"><div><div className="bw-kicker">FY {currentFY()}</div><h1>{org?.Name||'Welcome to Trusted Circle Books'}</h1><p>Financial command centre for {user?.email||'your organisation'}.</p></div><button className="bw-secondary" onClick={()=>onNavigate('organisation')}><Building2 size={15}/> Organisation profile</button></div><div className="bw-kpi-grid">{cards.map(c=><div className="bw-kpi" key={c[0]}><span>{c[0]}</span><strong>{c[1]}</strong><small>{c[2]}</small></div>)}</div><div className="bw-dashboard-grid"><div className="bw-card"><div className="bw-card-title"><Scale size={18}/> Financial controls</div><div className="bw-control-list"><div><span>Trial Balance</span><b>Double-entry</b></div><div><span>Profit & Loss</span><b>FY-wise</b></div><div><span>Balance Sheet</span><b>FY-wise</b></div><div><span>Audit trail</span><b>Enabled</b></div></div></div><div className="bw-card"><div className="bw-card-title"><BookOpen size={18}/> Build your books</div><div className="bw-quick"><button onClick={()=>onNavigate('accounts')}><BookOpen/> Chart of Accounts<ChevronRight/></button><button onClick={()=>onNavigate('journal')}><FileText/> Post Journal<ChevronRight/></button><button onClick={()=>onNavigate('reports')}><Scale/> View Reports<ChevronRight/></button></div></div></div></section>
}

function Placeholder({title,text}){return <section className="bw-section"><PageHead kicker="MODULE" title={title} text={text}/><div className="bw-card"><Empty title={`${title} module is ready`} text="The navigation and data layer are prepared. This module will use the dedicated Books spreadsheet and the same organisation-level permissions."/></div></section>}

function Workspace({session,user,org,onLogout}){
 const[active,setActive]=useState(org?'dashboard':'organisation'),[side,setSide]=useState(false),[organisation,setOrganisation]=useState(org)
 const go=id=>{setActive(id);setSide(false)}
 const content=active==='dashboard'?<Dashboard org={organisation} user={user} onNavigate={go}/>:active==='organisation'?<Organisation org={organisation} onSaved={x=>setOrganisation(x)}/>:active==='accounts'?<Accounts/>:active==='journal'?<Journal/>:active==='reports'?<Reports/>:<Placeholder title={{customers:'Customers',vendors:'Vendors',invoices:'Invoices',receipts:'Receipts',bills:'Bills',expenses:'Expenses',banking:'Banking',gst:'GST / Tax',inventory:'Inventory',settings:'Settings'}[active]||active} text="Production module scaffold with organisation isolation, role controls and audit-ready data contracts."/>
 return <div className="bw-app"><header className="bw-topbar"><button className="bw-menu" onClick={()=>setSide(true)}><Menu size={21}/></button><div className="bw-top-brand"><img src={LOGO_URL}/><span>Trusted Circle <b>Books</b></span></div><div className="bw-top-right"><span className="bw-fy">FY {currentFY()}</span><span className="bw-user">{user?.email}</span><button className="bw-icon" title="Sign out" onClick={onLogout}><LogOut size={18}/></button></div></header><aside className={`bw-sidebar ${side?'open':''}`}><div className="bw-side-head"><div className="bw-side-brand"><img src={LOGO_URL}/><div><b>Trusted Circle Books</b><small>{organisation?.Name||'Organisation setup'}</small></div></div><button className="bw-icon bw-close" onClick={()=>setSide(false)}><X/></button></div><nav>{NAV.map(g=><div className="bw-nav-group" key={g.group}><small>{g.group}</small>{g.items.map(([id,label,Icon])=><button key={id} className={active===id?'active':''} onClick={()=>go(id)}><Icon size={17}/><span>{label}</span>{active===id&&<ChevronRight size={14}/>}</button>)}</div>)}</nav><div className="bw-side-foot"><button onClick={onLogout}><LogOut size={16}/> Sign out</button></div></aside>{side&&<div className="bw-overlay" onClick={()=>setSide(false)}/>}<main className="bw-main">{content}</main></div>
}

export default function BooksWorkspace({user,onLogout}){const[org,setOrg]=useState(null);const[loading,setLoading]=useState(true);const[err,setErr]=useState('');useEffect(()=>{booksRequest('booksMe',{token:localStorage.getItem(BOOKS_SESSION_KEY)}).then(x=>setOrg(x.organisation||null)).catch(e=>setErr(e.message)).finally(()=>setLoading(false))},[]);if(loading)return <div className="bw-loading">Opening Trusted Circle Books…</div>;if(err)return <div className="bw-error"><b>Books session error</b><p>{err}</p><button className="bw-primary" onClick={onLogout}>Return to login</button></div>;return <Workspace user={user} org={org} onLogout={onLogout}/>} 
