import React,{useEffect,useMemo,useState} from 'react'
import {Activity,BarChart3,BookOpen,Building2,ChevronRight,FileBarChart,FileText,Landmark,LayoutDashboard,Menu,Package,Plus,RefreshCw,Search,Settings,ShieldCheck,Users,WalletCards,X} from 'lucide-react'
import {BOOKS_API_URL,BOOKS_SESSION_KEY} from './books-config'
import {loadingPurpose} from './BooksLoading'
import './books-workspace-pro.css'

const LOGO='https://raw.githubusercontent.com/trustedcircle2026-cloud/Trusted-Circle/main/Logo%20new.jpg'
const token=()=>localStorage.getItem(BOOKS_SESSION_KEY)
const money=v=>'₹'+Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})
const fy=()=>{const d=new Date(),y=d.getFullYear();return d.getMonth()>=3?`${y}-${y+1}`:`${y-1}-${y}`}
const sleep=ms=>new Promise(r=>setTimeout(r,ms))
const inflight=new Map()

async function api(action,payload={},message){
  const key=action+':'+JSON.stringify(payload)
  const reusable=['booksGetOrganisation','booksDashboard','booksUiList'].includes(action)
  if(reusable&&inflight.has(key))return inflight.get(key)
  const run=(async()=>{
    const detail={message:message||loadingPurpose(action)}
    const timer=setTimeout(()=>window.dispatchEvent(new CustomEvent('tc-books-loading-start',{detail})),120)
    try{
      const controller=new AbortController()
      const timeout=setTimeout(()=>controller.abort(),20000)
      let response
      try{response=await fetch(BOOKS_API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...payload}),signal:controller.signal})}
      finally{clearTimeout(timeout)}
      const text=await response.text();let data
      try{data=JSON.parse(text)}catch(e){throw Error('Books backend returned an invalid response.')}
      if(!response.ok||data.ok===false)throw Error(data.error?.message||data.message||'Books request failed.')
      return data.data??data
    }catch(e){if(e?.name==='AbortError')throw Error('Books request timed out. Please try again.');throw e}
    finally{clearTimeout(timer);window.dispatchEvent(new CustomEvent('tc-books-loading-stop'))}
  })()
  if(reusable)inflight.set(key,run)
  try{return await run}finally{if(reusable)inflight.delete(key)}
}

const GROUPS=[
 ['COMMAND',[['dashboard','Dashboard',LayoutDashboard],['organisation','Organisation',Building2]]],
 ['SALES',[['customers','Customers',Users],['quotes','Quotes',FileText],['salesorders','Sales Orders',ClipboardIcon],['invoices','Invoices',ReceiptIcon],['receipts','Payments Received',WalletCards],['creditnotes','Credit Notes',FileText]]],
 ['PURCHASES',[['vendors','Vendors',Users],['purchaseorders','Purchase Orders',ClipboardIcon],['bills','Bills',FileText],['payments','Payments Made',WalletCards],['vendorcredits','Vendor Credits',FileText],['expenses','Expenses',WalletCards]]],
 ['ACCOUNTING',[['accounts','Chart of Accounts',BookOpen],['journal','Manual Journal',FileText],['generalledger','General Ledger',BookOpen],['accountledger','Account Ledger',BookOpen],['daybook','Day Book',BookOpen],['reports','Financial Reports',FileBarChart],['cashflow','Cash Flow',BarChart3],['budgets','Budgets',BarChart3]]],
 ['BANKING & TAX',[['banking','Banking',Landmark],['reconciliation','Reconciliation',Activity],['gst','GST / Tax',ShieldCheck],['gstr','GSTR Data',FileBarChart],['einvoice','E-Invoice',FileText],['eway','E-Way Bill',FileText],['tds','TDS',FileText]]],
 ['INVENTORY & PROJECTS',[['items','Items & Inventory',Package],['stockledger','Stock Ledger',BookOpen],['fifo','FIFO Valuation',BarChart3],['projects','Projects',FileText],['assets','Fixed Assets',Landmark],['recurring','Recurring Invoices',RefreshCw]]],
 ['PEOPLE & ADMIN',[['members','User Management',Users],['joinrequests','Join Requests',ShieldCheck],['employees','Employees',Users],['roles','Roles & Permissions',ShieldCheck],['approvals','Approvals',ShieldCheck],['portals','Customer / Vendor Portals',Users],['documents','Documents',FileText],['notifications','Notifications',Activity],['audit','Audit Trail',Activity],['fylock','FY Lock',ShieldCheck],['orgswitch','Organisation Switch',Building2],['settings','Settings',Settings]]]
]
const SHEETS={customers:'Customers',vendors:'Vendors',items:'Items',quotes:'Quotes',salesorders:'SalesOrders',receipts:'Receipts',creditnotes:'CreditNotes',purchaseorders:'PurchaseOrders',payments:'Payments',vendorcredits:'VendorCredits',expenses:'Expenses',accounts:'Accounts',journal:'JournalEntries',projects:'Projects',assets:'FixedAssets',budgets:'Budgets',employees:'Employees',roles:'Roles',portals:'PortalUsers',documents:'Documents',notifications:'Notifications',approvals:'Approvals',banking:'BankAccounts',reconciliation:'Reconciliations',recurring:'RecurringInvoices',tds:'TDSRecords'}
const REPORTS={generalledger:'booksGeneralLedger',accountledger:'booksAccountLedger',daybook:'booksDayBook',cashflow:'booksCashFlow',gst:'booksGstReport',gstr:'booksGstrData',stockledger:'booksStockLedger',fifo:'booksFifoValuation'}
const CONTROL=new Set(['einvoice','eway','fylock','orgswitch','settings','audit','notifications','approvals'])
const title=s=>String(s).replace(/([A-Z])/g,' $1').replace(/^./,x=>x.toUpperCase())
const prettyPage={receipts:'Payments Received',payments:'Payments Made',salesorders:'Sales Orders',purchaseorders:'Purchase Orders',creditnotes:'Credit Notes',vendorcredits:'Vendor Credits',generalledger:'General Ledger',accountledger:'Account Ledger',daybook:'Day Book',cashflow:'Cash Flow',stockledger:'Stock Ledger',fifo:'FIFO Valuation',joinrequests:'Join Requests',fylock:'Financial Year Lock',orgswitch:'Organisation Switch',einvoice:'E-Invoice',eway:'E-Way Bill',gstr:'GSTR Data'}
function ClipboardIcon(p){return <FileText {...p}/>}
function ReceiptIcon(p){return <WalletCards {...p}/>}

function Header({org,user,onMenu,onLogout,onSearch}){const[q,setQ]=useState('');return <header className="bp-header"><div className="bp-header-left"><button className="bp-menu-btn" onClick={onMenu} aria-label="Open menu" aria-expanded="false"><Menu size={21}/></button><a className="bp-logo-link" href="./books.html" aria-label="Trusted Circle Books home"><img src={LOGO} alt="Trusted Circle"/></a></div><div className="bp-header-search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&q.trim())onSearch(q.trim())}} placeholder="Search customers, invoices, bills, items…"/><kbd>Enter</kbd></div><div className="bp-org"><span>ORGANISATION</span><b title={org?.Name||'Organisation'}>{org?.Name||'Organisation'}</b></div><div className="bp-user"><span title={user?.name||user?.email}>{user?.name||user?.email||'User'}</span><button onClick={onLogout}>Sign out</button></div></header>}
function Sidebar({page,go,open,close}){useEffect(()=>{if(!open)return;const esc=e=>e.key==='Escape'&&close();document.addEventListener('keydown',esc);return()=>document.removeEventListener('keydown',esc)},[open,close]);return <><aside className={'bp-side '+(open?'open':'')} aria-hidden={!open}><div className="bp-side-head"><div className="bp-side-brand"><img src={LOGO} alt="Trusted Circle"/><div><b>Trusted Circle</b><small>BOOKS · CLOUD ACCOUNTING</small></div></div><button className="bp-close-menu" onClick={close} aria-label="Close menu"><X size={18}/></button></div><nav className="bp-nav">{GROUPS.map(([group,items])=><section key={group}><div className="bp-group">{group}</div>{items.map(([id,name,Icon])=><a href={'#'+id} key={id} className={page===id?'active':''} onClick={e=>{e.preventDefault();go(id)}}><Icon size={16}/><span>{name}</span>{page===id&&<ChevronRight size={13}/>}</a>)}</section>)}</nav><div className="bp-side-foot"><ShieldCheck size={13}/><span>Secure organisation workspace</span><b>FY {fy()}</b></div></aside>{open&&<div className="bp-overlay" onClick={close} aria-hidden="true"/>}</>}
function Page({section,name,desc,actions,children}){return <main className="bp-main"><div className="bp-pagehead"><div><span className="bp-eyebrow">{section}</span><h1>{name}</h1><p>{desc}</p></div>{actions&&<div className="bp-page-actions">{actions}</div>}</div>{children}</main>}
function Button({children,primary=false,onClick,type='button',icon:Icon}){return <button type={type} className={'bp-btn'+(primary?' primary':'')} onClick={onClick}>{Icon&&<Icon size={15}/>}<span>{children}</span></button>}
function Table({rows,fields}){const cols=fields||(rows.length?Object.keys(rows[0]).filter(x=>x!=='OrganisationID').slice(0,10):[]);return <div className="bp-table-wrap"><table><thead><tr>{cols.map(f=><th key={f}>{title(f)}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.ID||r.Id||r.CustomerID||r.InvoiceID||r.BillID||i}>{cols.map(f=><td key={f}>{r[f]===undefined||r[f]===''?'—':String(r[f])}</td>)}</tr>)}</tbody></table>{!rows.length&&<div className="bp-empty"><BookOpen size={26}/><b>No records found</b><span>Create or import records to populate this module.</span></div>}</div>}
function Modal({title,onClose,children}){return <div className="bp-modal-bg" role="dialog" aria-modal="true"><section className="bp-modal"><header className="bp-modal-head"><div><small>TRUSTED CIRCLE BOOKS</small><h3>{title}</h3></div><button className="bp-close" onClick={onClose} aria-label="Close"><X size={18}/></button></header>{children}</section></div>}
function Module({page}){const sheet=SHEETS[page],label=prettyPage[page]||title(page);const[rows,setRows]=useState([]),[q,setQ]=useState(''),[error,setError]=useState(''),[show,setShow]=useState(false),[form,setForm]=useState({}),[busy,setBusy]=useState(true);const load=()=>{setError('');setBusy(true);return api('booksUiList',{token:token(),sheet,q},`Loading ${label.toLowerCase()}…`).then(x=>setRows(x.rows||[])).catch(e=>setError(e.message)).finally(()=>setBusy(false))};useEffect(()=>{load()},[sheet]);const save=e=>{e.preventDefault();setError('');api('booksUiSave',{token:token(),sheet,record:form},`Saving ${label.toLowerCase()}…`).then(()=>{setShow(false);setForm({});load()}).catch(e=>setError(e.message))};return <Page section="MODULE" name={label} desc={`Search and manage ${label.toLowerCase()} for the active organisation.`} actions={<><Button icon={RefreshCw} onClick={load}>Refresh</Button><Button primary icon={Plus} onClick={()=>setShow(true)}>New</Button></>}><div className="bp-card"><div className="bp-toolbar"><div className="bp-search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder={`Search ${label.toLowerCase()}…`}/></div><span className="bp-count">{busy?'Loading…':`${rows.length} records`}</span></div>{error&&<div className="bp-alert">{error}</div>}{busy?<div className="bp-loading">Preparing {label.toLowerCase()}…</div>:<Table rows={rows}/>}</div>{show&&<Modal title={`New ${label.replace(/s$/,'')}`} onClose={()=>setShow(false)}><form className="bp-form" onSubmit={save}>{['Name','Email','Phone','Reference','Date','Amount','Status','Notes'].map(f=><label key={f}><span>{f}</span><input value={form[f]||''} onChange={e=>setForm({...form,[f]:e.target.value})}/></label>)}<Button primary type="submit">Save Record</Button></form></Modal>}</Page>}
function Dashboard({go}){const[d,setD]=useState(null),[error,setError]=useState('');const load=()=>api('booksDashboard',{token:token()},'Loading dashboard financial data…').then(setD).catch(e=>setError(e.message));useEffect(()=>{load()},[]);return <Page section="OVERVIEW" name="Dashboard" desc="Your financial command centre for the active organisation." actions={<Button icon={RefreshCw} onClick={load}>Refresh</Button>}><div className="bp-hero"><div><span>TRUSTED CIRCLE BOOKS</span><h2>Everything connected to one financial workspace.</h2><p>Sales, purchases, accounting, banking, GST, inventory and administration in one place.</p></div><img src={LOGO} alt="Trusted Circle"/></div>{error&&<div className="bp-alert">{error}</div>}<div className="bp-kpis">{[['Receivables',d?.receivables],['Payables',d?.payables],['Cash Received',d?.cashReceived],['Cash Paid',d?.cashPaid],['Income',d?.income],['Net Profit',d?.netProfit]].map(([n,v])=><div className="bp-kpi" key={n}><span>{n}</span><strong>{d?money(v):'—'}</strong></div>)}</div><div className="bp-dashboard-grid"><div className="bp-card"><h3>Business activity</h3><div className="bp-stat"><span>Invoices</span><b>{d?.invoiceCount??'—'}</b></div><div className="bp-stat"><span>Bills</span><b>{d?.billCount??'—'}</b></div><div className="bp-stat"><span>Expenses</span><b>{d?.expenses===undefined?'—':money(d.expenses)}</b></div></div><div className="bp-card"><h3>Quick actions</h3><div className="bp-quick"><button onClick={()=>go('customers')}><Users/><b>Customers</b><span>Manage master</span></button><button onClick={()=>go('invoices')}><FileText/><b>Invoices</b><span>Record sales</span></button><button onClick={()=>go('bills')}><FileText/><b>Bills</b><span>Record purchases</span></button><button onClick={()=>go('reports')}><FileBarChart/><b>Reports</b><span>Financial reporting</span></button></div></div></div></Page>}
function Organisation({org,onSaved}){const[d,setD]=useState(org||{}),[msg,setMsg]=useState('');useEffect(()=>setD(org||{}),[org]);const save=e=>{e.preventDefault();setMsg('');api('booksSaveOrganisation',{token:token(),organisation:d},'Saving organisation details…').then(x=>{onSaved(x.organisation);setMsg('Organisation details saved successfully.')}).catch(e=>setMsg(e.message))};const fields=['Name','LegalName','GSTIN','PAN','CIN','TAN','LLPIN','UDYAM','IEC','Email','Phone','Address','City','State','Pincode','BaseCurrency','FinancialYearStartMonth','AccountingMethod'];return <Page section="SETUP" name="Organisation Profile" desc="Legal, registration, contact and accounting details." actions={<span/>}><div className="bp-card"><div className="bp-profile-brand"><img src={LOGO} alt="Trusted Circle"/><div><b>{d.Name||'Organisation'}</b><span>Trusted Circle Books · Active organisation</span></div></div><form className="bp-form" onSubmit={save}>{fields.map(f=><label key={f}><span>{title(f)}</span><input value={d[f]||''} onChange={e=>setD({...d,[f]:e.target.value})}/></label>)}<Button primary type="submit">Save Changes</Button></form>{msg&&<div className={'bp-alert '+(msg.includes('successfully')?'success':'')}>{msg}</div>}</div></Page>}
function SearchPage({query}){const[q,setQ]=useState(query||''),[rows,setRows]=useState([]),[error,setError]=useState('');const run=()=>{if(!q.trim())return;setError('');api('booksSearch',{token:token(),q:q.trim()},'Searching your Books workspace…').then(x=>setRows(x.results||[])).catch(e=>setError(e.message))};useEffect(()=>{if(query)run()},[query]);return <Page section="COMMAND" name="Global Search" desc="Search across customers, vendors, items, transactions, projects and employees."><div className="bp-card"><div className="bp-global-search"><Search size={18}/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&run()} placeholder="Search everything…"/><Button primary onClick={run}>Search</Button></div>{error&&<div className="bp-alert">{error}</div>}{rows.map((r,i)=><div className="bp-result" key={i}><span>{r.type}</span><b>{r.id}</b><p>{JSON.stringify(r.record)}</p></div>)}{!rows.length&&!error&&<div className="bp-empty"><Search size={28}/><b>Search your Books data</b><span>Enter a customer, invoice, bill, item or transaction.</span></div>}</div></Page>}
function Reports({page}){const[data,setData]=useState(null),[error,setError]=useState(''),action=REPORTS[page],label=prettyPage[page]||'Financial Reports';const load=()=>{setError('');const p={token:token(),fiscalYear:fy()};const purpose=page==='cashflow'?'Calculating Cash Flow…':page==='gst'?'Loading GST report data…':page==='gstr'?'Preparing GSTR-oriented data…':page==='stockledger'?'Loading stock ledger…':page==='fifo'?'Calculating FIFO inventory valuation…':`Loading ${label.toLowerCase()}…`;return(action?api(action,p,purpose):api('booksReport',{...p,reportType:'trial_balance'},'Loading Trial Balance…')).then(setData).catch(e=>setError(e.message))};useEffect(()=>{load()},[page]);const rows=data?.rows||data?.entries||data?.transactions||[];return <Page section="REPORTING" name={label} desc="FY-wise reporting from the Books accounting ledger." actions={<Button icon={RefreshCw} onClick={load}>Refresh</Button>}>{error&&<div className="bp-alert">{error}</div>}<div className="bp-report-metrics"><div><span>Income</span><b>{data?.income===undefined?'—':money(data.income)}</b></div><div><span>Expenses</span><b>{data?.expenses===undefined?'—':money(data.expenses)}</b></div><div><span>Net Profit</span><b>{data?.netProfit===undefined?'—':money(data.netProfit)}</b></div><div><span>Financial Year</span><b>{fy()}</b></div></div><div className="bp-card">{rows.length?<Table rows={rows}/>:<div className="bp-empty"><FileBarChart size={28}/><b>No report rows returned</b><span>Post transactions and refresh this report.</span></div>}</div></Page>}
function Control({page}){const names={receipts:'Payments Received',payments:'Payments Made',einvoice:'E-Invoice',eway:'E-Way Bill',fylock:'Financial Year Lock',orgswitch:'Organisation Switch',approvals:'Approvals',portals:'Customer / Vendor Portals',documents:'Documents',notifications:'Notifications',audit:'Audit Trail',settings:'Settings'};return <Page section="CONTROL" name={names[page]||title(page)} desc="Organisation-scoped Books workflow and controls."><div className="bp-control-grid"><div className="bp-control-card"><ShieldCheck size={28}/><b>Organisation-scoped control</b><p>This module uses the active Books session, organisation context, permissions and audit controls.</p><Button icon={RefreshCw} onClick={()=>location.reload()}>Refresh</Button></div></div></Page>}

export default function BooksWorkspaceStable({user,onLogout}){
  const[page,setPage]=useState(location.hash.slice(1)||'dashboard'),[menu,setMenu]=useState(false),[org,setOrg]=useState(null),[search,setSearch]=useState('')
  useEffect(()=>{api('booksGetOrganisation',{token:token()},'Loading active organisation…').then(x=>setOrg(x.organisation)).catch(()=>{})},[])
  useEffect(()=>{const f=()=>{const h=location.hash.slice(1);if(h)setPage(h)};window.addEventListener('hashchange',f);return()=>window.removeEventListener('hashchange',f)},[])
  useEffect(()=>{document.body.style.overflow=menu?'hidden':'';return()=>{document.body.style.overflow=''}},[menu])
  const go=id=>{setPage(id);location.hash=id;setMenu(false)}
  const content=useMemo(()=>{
    if(page==='dashboard')return <Dashboard go={go}/>
    if(page==='organisation')return <Organisation org={org} onSaved={setOrg}/>
    if(page==='search')return <SearchPage query={search}/>
    if(page==='reports'||REPORTS[page])return <Reports page={page}/>
    if(SHEETS[page])return <Module page={page}/>
    if(CONTROL.has(page))return <Control page={page}/>
    return <Control page={page}/>
  },[page,org,search])
  return <div className="bp-app"><Header org={org} user={user} onMenu={()=>setMenu(v=>!v)} onLogout={onLogout} onSearch={q=>{setSearch(q);go('search')}}/><Sidebar page={page} go={go} open={menu} close={()=>setMenu(false)}/>{content}</div>
}
