import React,{useEffect,useMemo,useState} from 'react'
import {Activity,BarChart3,BookOpen,Building2,ChevronDown,ChevronRight,ClipboardList,FileBarChart,FileText,Landmark,LayoutDashboard,Menu,Package,Plus,Receipt,RefreshCw,Search,Settings,ShieldCheck,Users,WalletCards,X} from 'lucide-react'
import {BOOKS_API_URL,BOOKS_SESSION_KEY} from './books-config'
import './books-full-workspace.css'

const token=()=>localStorage.getItem(BOOKS_SESSION_KEY)
async function req(action,payload={}){const r=await fetch(BOOKS_API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...payload})});const t=await r.text();let j;try{j=JSON.parse(t)}catch{throw Error('Books backend returned an invalid response.')};if(!r.ok||j.ok===false)throw Error(j.error?.message||j.message||'Books request failed.');return j.data??j}
const money=v=>`₹${Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`
const today=()=>new Date().toISOString().slice(0,10)
const fy=()=>{const d=new Date(),y=d.getFullYear();return d.getMonth()+1>=4?`${y}-${y+1}`:`${y-1}-${y}`}
const NAV=[
 ['COMMAND',[['dashboard','Dashboard',LayoutDashboard],['organisation','Organisation',Building2],['search','Global Search',Search]]],
 ['SALES',[['customers','Customers',Users],['quotes','Quotes',ClipboardList],['salesorders','Sales Orders',FileText],['invoices','Invoices',Receipt],['receipts','Payments Received',WalletCards],['creditnotes','Credit Notes',FileText]]],
 ['PURCHASES',[['vendors','Vendors',Users],['purchaseorders','Purchase Orders',ClipboardList],['bills','Bills',FileText],['payments','Payments Made',WalletCards],['vendorcredits','Vendor Credits',FileText],['expenses','Expenses',WalletCards]]],
 ['ACCOUNTING',[['accounts','Chart of Accounts',BookOpen],['journal','Manual Journals',FileText],['reports','Financial Reports',FileBarChart],['budgets','Budgets',BarChart3]]],
 ['BANKING & TAX',[['banking','Banking',Landmark],['gst','GST / Tax',ShieldCheck],['tds','TDS',FileText],['reconciliation','Reconciliation',Activity]]],
 ['INVENTORY & PROJECTS',[['items','Items & Inventory',Package],['projects','Projects',ClipboardList],['assets','Fixed Assets',Landmark]]],
 ['PEOPLE & ADMIN',[['members','User Management',Users],['joinrequests','Join Requests',ShieldCheck],['employees','Employees',Users],['roles','Roles & Permissions',ShieldCheck],['notifications','Notifications',Activity],['audit','Audit Trail',Activity],['settings','Settings',Settings]]]
]
const MODULE={customers:['Customers','booksListCustomers','booksSaveCustomer','CustomerID',['Name','Email','Phone','GSTIN','PAN','BillingAddress','ShippingAddress']],vendors:['Vendors','booksListVendors','booksSaveVendor','VendorID',['Name','Email','Phone','GSTIN','PAN','Address']],items:['Items & Inventory','booksListItems','booksSaveItem','ItemID',['SKU','Name','Type','Unit','HSN','SAC','SalesRate','PurchaseRate','TaxRate','OpeningQty','OpeningValue']],quotes:['Quotes','booksListQuotes','booksSaveQuote','QuoteID',['QuoteNumber','QuoteDate','ExpiryDate','CustomerID','Status','Subtotal','TaxAmount','Discount','Total','Notes']],salesorders:['Sales Orders','booksListSalesOrders','booksSaveSalesOrder','SalesOrderID',['OrderNumber','OrderDate','ExpectedDate','CustomerID','Status','Subtotal','TaxAmount','Discount','Total','Notes']],purchaseorders:['Purchase Orders','booksListPurchaseOrders','booksSavePurchaseOrder','PurchaseOrderID',['OrderNumber','OrderDate','ExpectedDate','VendorID','Status','Subtotal','TaxAmount','Discount','Total','Notes']],projects:['Projects','booksListProjects','booksSaveProject','ProjectID',['ProjectCode','Name','CustomerID','StartDate','EndDate','Status','Budget']],assets:['Fixed Assets','booksListFixedAssets','booksSaveFixedAsset','AssetID',['AssetCode','Name','PurchaseDate','Cost','DepreciationMethod','UsefulLife','AccumulatedDepreciation','Status']],budgets:['Budgets','booksListBudgets','booksSaveBudget','BudgetID',['FiscalYear','AccountID','Amount','Notes','Status']],tds:['TDS Records','booksListTDS','booksSaveTDS','TDSID',['TxnDate','PartyType','PartyID','Section','BaseAmount','TDSRate','TDSAmount','Status']]}
function Field({name,value,onChange}){return <label><span>{name.replace(/([A-Z])/g,' $1')}</span><input value={value??''} onChange={e=>onChange(e.target.value)}/></label>}
function Modal({title,children,onClose}){return <div className="bf-modal-bg"><div className="bf-modal"><header><b>{title}</b><button onClick={onClose}><X size={18}/></button></header>{children}</div></div>}
function Header({org,user,onMenu,onLogout}){return <header className="bf-header"><button className="bf-menu" onClick={onMenu}><Menu/></button><div className="bf-title"><span className="bf-mark"><BookOpen size={17}/></span><b>Trusted Circle Books</b>{org&&<><ChevronRight size={14}/><span>{org.Name}</span></>}</div><div className="bf-user"><span>{user?.name||user?.email}</span><button onClick={onLogout}>Sign out</button></div></header>}
function Side({page,setPage,open,setOpen}){return <aside className={`bf-side ${open?'open':''}`}><div className="bf-side-brand"><BookOpen size={20}/><b>Books</b></div>{NAV.map(([group,items])=><div className="bf-nav-group" key={group}><small>{group}</small>{items.map(([id,label,I])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setOpen(false)}}><I size={16}/><span>{label}</span></button>)}</div>)}</aside>}
function Dashboard({onGo}){const[d,setD]=useState(null),[busy,setBusy]=useState(true);useEffect(()=>{req('booksDashboard',{token:token()}).then(setD).finally(()=>setBusy(false))},[]);const cards=[['Total Receivables',d?.receivables,'₹'],['Total Payables',d?.payables,'₹'],['Cash Received',d?.cashReceived,'₹'],['Cash Paid',d?.cashPaid,'₹'],['Income',d?.income,'₹'],['Net Profit',d?.netProfit,'₹']];return <Page title="Dashboard" kicker="OVERVIEW" text="A real-time view of your organisation's financial position."><div className="bf-kpis">{cards.map(([n,v])=><div className="bf-kpi" key={n}><span>{n}</span><strong>{busy?'—':money(v)}</strong></div>)}</div><div className="bf-grid2"><div className="bf-panel"><h3>Business activity</h3><div className="bf-statrow"><span>Invoices</span><b>{d?.invoiceCount||0}</b></div><div className="bf-statrow"><span>Bills</span><b>{d?.billCount||0}</b></div><div className="bf-statrow"><span>Expenses</span><b>{money(d?.expenses)}</b></div></div><div className="bf-panel"><h3>Quick actions</h3><div className="bf-actions-grid"><button onClick={()=>onGo('customers')}><Users/> New customer</button><button onClick={()=>onGo('invoices')}><Receipt/> New invoice</button><button onClick={()=>onGo('bills')}><FileText/> New bill</button><button onClick={()=>onGo('journal')}><BookOpen/> Journal entry</button></div></div></div></Page>}
function Page({kicker,title,text,children}){return <main className="bf-main"><div className="bf-pagehead"><div><small>{kicker}</small><h1>{title}</h1><p>{text}</p></div></div>{children}</main>}
function Crud({type}){const cfg=MODULE[type], [title,listAction,saveAction,idField,fields]=cfg,[rows,setRows]=useState([]),[busy,setBusy]=useState(true),[show,setShow]=useState(false),[form,setForm]=useState({}),[q,setQ]=useState(''),[msg,setMsg]=useState('');const load=()=>{setBusy(true);req(listAction,{token:token()}).then(x=>setRows(x.rows||x.customers||x.vendors||x.items||[])).catch(e=>setMsg(e.message)).finally(()=>setBusy(false))};useEffect(load,[]);const save=async e=>{e.preventDefault();try{await req(saveAction,{token:token(),record:form});setShow(false);setForm({});load()}catch(e){setMsg(e.message)}};const filtered=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q.toLowerCase()));return <Page kicker="MODULE" title={title} text="Manage organisation records with role-based access and audit-ready changes."><div className="bf-toolbar"><div className="bf-search"><Search size={16}/><input placeholder={`Search ${title.toLowerCase()}…`} value={q} onChange={e=>setQ(e.target.value)}/></div><button className="bf-primary" onClick={()=>setShow(true)}><Plus size={16}/> New</button><button className="bf-secondary" onClick={load}><RefreshCw size={15}/> Refresh</button></div>{msg&&<div className="bf-alert">{msg}</div>}<div className="bf-panel bf-table-wrap"><table><thead><tr>{fields.slice(0,7).map(f=><th key={f}>{f}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r[idField]}>{fields.slice(0,7).map(f=><td key={f}>{String(r[f]??'—')}</td>)}</tr>)}</tbody></table>{!busy&&!filtered.length&&<div className="bf-empty"><BookOpen size={24}/><b>No records</b><span>Create your first record using the New button.</span></div>}</div>{show&&<Modal title={`New ${title.replace(/s$/,'')}`} onClose={()=>setShow(false)}><form className="bf-form" onSubmit={save}>{fields.map(f=><Field key={f} name={f} value={form[f]} onChange={v=>setForm({...form,[f]:v})}/>) }<button className="bf-primary">Save record</button></form></Modal>}</Page>}
function Reports(){const[r,setR]=useState('trial_balance'),[fyv,setFy]=useState(fy()),[d,setD]=useState(null),[err,setErr]=useState('');useEffect(()=>{setErr('');req('booksReport',{token:token(),reportType:r,fiscalYear:fyv}).then(setD).catch(e=>setErr(e.message))},[r,fyv]);return <Page kicker="REPORTING" title="Financial Reports" text="FY-wise reports generated from your accounting ledger."><div className="bf-reportbar"><select value={r} onChange={e=>setR(e.target.value)}><option value="trial_balance">Trial Balance</option><option value="profit_loss">Profit & Loss</option><option value="balance_sheet">Balance Sheet</option><option value="aging">Receivables Aging</option></select><select value={fyv} onChange={e=>setFy(e.target.value)}><option>{fy()}</option><option>{Number(fy().slice(0,4))-1}-{Number(fy().slice(0,4))}</option></select></div>{err&&<div className="bf-alert">{err}</div>}<div className="bf-report-cards">{r==='profit_loss'&&[['Income',d?.income],['Expenses',d?.expenses],['Net Profit',d?.netProfit]].map(x=><div className="bf-report-card"><span>{x[0]}</span><b>{money(x[1])}</b></div>)}{r==='balance_sheet'&&[['Assets',d?.assets],['Liabilities',d?.liabilities],['Equity',d?.equity],['Retained Profit',d?.retainedProfit]].map(x=><div className="bf-report-card"><span>{x[0]}</span><b>{money(x[1])}</b></div>)}{r==='trial_balance'&&<div className="bf-panel bf-table-wrap"><table><thead><tr><th>Code</th><th>Account</th><th>Type</th><th>Debit</th><th>Credit</th><th>Balance</th></tr></thead><tbody>{(d?.rows||[]).map(x=><tr><td>{x.code}</td><td>{x.name}</td><td>{x.type}</td><td>{money(x.debit)}</td><td>{money(x.credit)}</td><td>{money(x.balance)}</td></tr>)}</tbody></table></div>}{r==='aging'&&<div className="bf-panel bf-table-wrap"><table><thead><tr><th>Invoice</th><th>Due</th><th>Days</th><th>Bucket</th><th>Balance</th></tr></thead><tbody>{(d?.rows||[]).map(x=><tr><td>{x.invoiceNumber}</td><td>{x.dueDate}</td><td>{x.daysOverdue}</td><td>{x.bucket}</td><td>{money(x.balanceDue)}</td></tr>)}</tbody></table></div>}</div></Page>}
function Members({join=false}){const[data,setData]=useState([]),[msg,setMsg]=useState('');const load=()=>req(join?'booksListJoinRequests':'booksListOrganisationMembers',{token:token()}).then(x=>setData(join?x.requests:x.members)).catch(e=>setMsg(e.message));useEffect(load,[]);const review=async(id,approve)=>{try{await req(approve?'booksApproveJoinRequest':'booksRejectJoinRequest',{token:token(),joinRequestId:id,remarks:approve?'Approved':'Rejected'});load()}catch(e){setMsg(e.message)}};return <Page kicker="PEOPLE & ADMIN" title={join?'Join Requests':'User Management'} text={join?'Review requests to join your organisation.':'Manage organisation memberships, roles and access.'}>{msg&&<div className="bf-alert">{msg}</div>}<div className="bf-panel bf-table-wrap"><table><thead><tr>{(join?['Name','Email','Status','RequestedAt','Action']:['Name','Email','Role','Status','JoinedAt']).map(x=><th>{x}</th>)}</tr></thead><tbody>{data.map(x=><tr><td>{x.Name}</td><td>{x.Email}</td><td>{join?x.Status:x.Role}</td><td>{join?x.RequestedAt:x.Status}</td>{join&&<td><button className="bf-link" onClick={()=>review(x.JoinRequestID,true)}>Approve</button><button className="bf-link danger" onClick={()=>review(x.JoinRequestID,false)}>Reject</button></td>}</tr>)}</tbody></table></div></Page>}
function Employees(){return <Crud type="employees"/>}
function SearchPage(){const[q,setQ]=useState(''),[rows,setRows]=useState([]);const go=()=>req('booksSearch',{token:token(),q}).then(x=>setRows(x.results||[]));return <Page kicker="COMMAND" title="Global Search" text="Search customers, vendors, items, transactions, projects and employees."><div className="bf-toolbar"><div className="bf-search wide"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search everything…" onKeyDown={e=>e.key==='Enter'&&go()}/></div><button className="bf-primary" onClick={go}>Search</button></div><div className="bf-panel bf-results">{rows.map(x=><div><b>{x.type}</b><span>{JSON.stringify(x.record)}</span></div>)}</div></Page>}
function App({user,onLogout}){const[page,setPage]=useState('dashboard'),[side,setSide]=useState(false),[org,setOrg]=useState(null);useEffect(()=>{req('booksGetOrganisation',{token:token()}).then(x=>setOrg(x.organisation)).catch(()=>{})},[]);let content=page==='dashboard'?<Dashboard onGo={setPage}/>:page==='reports'?<Reports/>:page==='members'?<Members/>:page==='joinrequests'?<Members join/>:page==='employees'?<Crud type="employees"/>:page==='search'?<SearchPage/>:page==='organisation'?<OrganisationPage org={org} onSaved={setOrg}/>:MODULE[page]?<Crud type={page}/>:<Coming page={page}/>;return <div className="bf-app"><Header org={org} user={user} onMenu={()=>setSide(!side)} onLogout={onLogout}/><Side page={page} setPage={setPage} open={side} setOpen={setSide}/>{side&&<div className="bf-overlay" onClick={()=>setSide(false)}/>} {content}</div>}
function OrganisationPage({org,onSaved}){const[d,setD]=useState(org||{}),save=async e=>{e.preventDefault();const x=await req('booksSaveOrganisation',{token:token(),organisation:d});onSaved(x.organisation)};return <Page kicker="SETUP" title="Organisation Profile" text="Complete legal, registration, contact and accounting details."><form className="bf-panel bf-form" onSubmit={save}>{['Name','LegalName','OrganisationType','BusinessDescription','Industry','Website','PAN','TAN','GSTIN','CIN','LLPIN','UDYAM','IEC','Email','Phone','AlternatePhone','ContactPerson','Address','Address2','City','District','State','Country','Pincode','BaseCurrency','BooksStartDate','FinancialYearStartMonth','GSTRegistered','GSTRegistrationType','GSTState','DefaultTaxTreatment','AccountingMethod'].map(f=><Field key={f} name={f} value={d?.[f]} onChange={v=>setD({...d,[f]:v})}/>) }<button className="bf-primary">Save organisation</button></form></Page>}
function Coming({page}){return <Page kicker="MODULE" title={page.replace(/([A-Z])/g,' $1')} text="This module is wired into the Books navigation and backend service layer."><div className="bf-panel bf-empty"><BookOpen size={28}/><b>Module ready</b><span>Use the dedicated workflow as its accounting APIs are enabled.</span></div></Page>}
export default function BooksFullWorkspace({user,onLogout}){return <App user={user} onLogout={onLogout}/>}
