import React,{useEffect,useMemo,useState} from 'react'
import ReactDOM from 'react-dom/client'
import {ArrowRight,Building2,CreditCard,Gift,Landmark,LockKeyhole,Mail,Percent,Plus,RefreshCw,ShieldCheck,TrendingUp,WalletCards,X} from 'lucide-react'
import {CARDS_API_URL,CARDS_SESSION_KEY} from './cards-config'
import './cards.css'
const LOGO='https://raw.githubusercontent.com/trustedcircle2026-cloud/Trusted-Circle/main/Logo%20new.jpg'
const PURPOSES={cardsRequestOtp:'Sending verification code to your email…',cardsVerifyOtp:'Verifying your OTP and creating a secure Cards session…',cardsDashboard:'Loading your personal finance dashboard…',cardsList:'Loading records…',cardsSave:'Saving your record securely…',cardsLogout:'Signing you out securely…'}
const purpose=a=>PURPOSES[a]||'Processing your Cards request…'
async function api(action,payload={},busy){if(!CARDS_API_URL)throw Error('Trusted Circle Cards backend URL is not configured.');busy?.(purpose(action));try{const c=new AbortController(),t=setTimeout(()=>c.abort(),30000);let r;try{r=await fetch(CARDS_API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...payload}),signal:c.signal})}finally{clearTimeout(t)}const txt=await r.text();let d;try{d=JSON.parse(txt)}catch(e){throw Error('Cards backend returned an invalid response.')}if(!r.ok||d.ok===false)throw Error(d.error?.message||d.message||'Cards request failed.');return d.data??d}catch(e){if(e?.name==='AbortError')throw Error('Cards request timed out. Please try again.');throw e}finally{busy?.(null)}}
function Loader({message}){return message?<div className="cards-loader"><div className="cards-loader-content"><div className="cards-spinner"/><span>{message}</span></div></div>:null}
function Login({onLogin}){const[email,setEmail]=useState(''),[otp,setOtp]=useState(''),[step,setStep]=useState('email'),[busy,setBusy]=useState(false),[loading,setLoading]=useState(''),[msg,setMsg]=useState(''),[error,setError]=useState(false)
const send=async e=>{e.preventDefault();const v=email.trim().toLowerCase();setBusy(true);setError(false);setMsg('');try{await api('cardsRequestOtp',{email:v},setLoading);setStep('otp');setMsg('Verification code sent to '+v+'.')}catch(e){setError(true);setMsg(e.message)}finally{setBusy(false)}}
const verify=async e=>{e.preventDefault();if(otp.length!==6)return;setBusy(true);setError(false);setMsg('');try{const x=await api('cardsVerifyOtp',{email:email.trim().toLowerCase(),otp},setLoading);localStorage.setItem(CARDS_SESSION_KEY,x.session.token);onLogin(x)}catch(e){setError(true);setMsg(e.message)}finally{setBusy(false)}}
return <main className="cards-login"><section className="cards-login-panel"><div className="cards-brand"><img src={LOGO}/><div><b>Trusted Circle Cards</b><small>PRIVATE FINANCE MANAGEMENT</small></div></div><div className="cards-eyebrow"><ShieldCheck size={14}/> SECURE PERSONAL ACCESS</div><h1>Your money,<br/><span>organised in one place.</span></h1><p>Bank accounts, debit cards, credit cards, FD-backed cards, rewards, purchases, returns and investments — privately managed in one workspace.</p><div className="cards-login-form">{step==='email'?<form onSubmit={send}><label>Email address</label><div className="cards-input"><Mail size={17}/><input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="your@email.com"/></div><button className="cards-primary" disabled={busy}>{busy?'Sending…':<>Continue with email <ArrowRight size={17}/></>}</button></form>:<form onSubmit={verify}><label>Verification code</label><div className="cards-input"><LockKeyhole size={17}/><input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength="6" required value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,''))} placeholder="6-digit OTP"/></div><button className="cards-primary" disabled={busy}>{busy?'Verifying…':<>Verify & continue <ArrowRight size={17}/></>}</button><button type="button" className="cards-secondary" onClick={()=>{setStep('email');setOtp('');setMsg('');setError(false)}}>Use another email</button></form>}{msg&&<div className={'cards-message '+(error?'error':'success')}>{msg}</div>}</div><div className="cards-trust"><CheckCircle2 size={16}/><span>Private records · Secure sessions · Admin controlled access</span></div></section><aside className="cards-login-side"><span className="cards-pill"><CreditCard size={14}/> TRUSTED CIRCLE CARDS</span><h2>Track the full picture of your <em>personal finance.</em></h2><div className="cards-feature"><div><Landmark/><span><b>Banking</b><small>Accounts, balances and transactions</small></span></div><div><WalletCards/><span><b>Cards</b><small>Limits, billing, rewards and FD backing</small></span></div><div><TrendingUp/><span><b>Investments</b><small>FDs, investments and returns</small></span></div></div></aside><Loader message={loading}/></main>}
const NAV=[['dashboard','Dashboard',Building2],['banks','Bank Accounts',Landmark],['debit','Debit Cards',WalletCards],['credit','Credit Cards',CreditCard],['fdcards','FD-Backed Cards',ShieldCheck],['purchases','Purchases',WalletCards],['returns','Returns',RefreshCw],['rewards','Rewards',Gift],['investments','Investments',TrendingUp],['fds','Fixed Deposits',Percent]]
const SHEETS={banks:'BankAccounts',debit:'DebitCards',credit:'CreditCards',fdcards:'FDBackedCards',purchases:'Purchases',returns:'Returns',rewards:'Rewards',investments:'Investments',fds:'FixedDeposits'}
const labels={banks:'Bank Accounts',debit:'Debit Cards',credit:'Credit Cards',fdcards:'FD-Backed Cards',purchases:'Purchases',returns:'Returns',rewards:'Rewards',investments:'Investments',fds:'Fixed Deposits'}
function App({session,onLogout}){const[page,setPage]=useState('dashboard'),[rows,setRows]=useState([]),[dash,setDash]=useState(null),[loading,setLoading]=useState(''),[error,setError]=useState('')
const load=async p=>{setError('');if(p==='dashboard'){try{setDash(await api('cardsDashboard',{token:session.token},setLoading))}catch(e){setError(e.message)}return}try{const x=await api('cardsList',{token:session.token,sheet:SHEETS[p]},setLoading);setRows(x.rows||[])}catch(e){setError(e.message)}}
useEffect(()=>{load(page)},[page])
const nav=useMemo(()=>NAV.map(([id,n,I])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><I size={17}/><span>{n}</span></button>),[page])
const logout=async()=>{try{await api('cardsLogout',{token:session.token},setLoading)}catch(e){}localStorage.removeItem(CARDS_SESSION_KEY);onLogout()}
return <div className="cards-app"><header className="cards-header"><div className="cards-head-brand"><img src={LOGO}/><div><b>Trusted Circle Cards</b><small>PRIVATE FINANCE</small></div></div><div className="cards-head-right"><span>{session.user?.email}</span><button onClick={logout}>Sign out</button></div></header><div className="cards-body"><aside className="cards-sidebar"><div className="cards-nav-title">PERSONAL FINANCE</div>{nav}<div className="cards-nav-title admin">ADMIN</div>{session.user?.role==='ADMIN'&&<button className={page==='admin'?'active':''} onClick={()=>setPage('admin')}><ShieldCheck size={17}/><span>Admin</span></button>}</aside><main className="cards-main">{page==='dashboard'?<Dashboard data={dash} error={error} refresh={()=>load('dashboard')} go={setPage}/>:page==='admin'?<Admin token={session.token} setLoading={setLoading}/>:<Records page={page} rows={rows} error={error} refresh={()=>load(page)} token={session.token} setLoading={setLoading}/>}</main></div><Loader message={loading}/></div>}
function Dashboard({data,error,refresh,go}){const m=v=>'₹'+Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});return <div><div className="cards-pagehead"><div><span>OVERVIEW</span><h1>Personal Finance Dashboard</h1><p>One private view of accounts, cards, rewards and investments.</p></div><button onClick={refresh}><RefreshCw size={15}/> Refresh</button></div>{error&&<div className="cards-alert">{error}</div>}<div className="cards-hero"><div><small>TRUSTED CIRCLE PERSONAL FINANCE</small><h2>Know what you own, what you owe, and what you earn.</h2><p>Banking, cards, rewards, purchases, returns, deposits and investments.</p></div><img src={LOGO}/></div><div className="cards-stats">{[['Bank Balance',data?.bankBalance],['Credit Limits',data?.creditLimits],['Outstanding',data?.outstanding],['Reward Value',data?.rewardValue],['Investments',data?.investments],['FD Value',data?.fdValue]].map(([n,v])=><div key={n}><span>{n}</span><b>{data?m(v):'—'}</b></div>)}</div><div className="cards-grid"><button onClick={()=>go('banks')}><Landmark/><b>Bank Accounts</b><span>Balances & transactions</span></button><button onClick={()=>go('credit')}><CreditCard/><b>Credit Cards</b><span>Limits, dues & rewards</span></button><button onClick={()=>go('rewards')}><Gift/><b>Rewards</b><span>Points, cashback & redemption</span></button><button onClick={()=>go('investments')}><TrendingUp/><b>Investments</b><span>Cost, value & returns</span></button></div></div>}
function Records({page,rows,error,refresh,token,setLoading}){const[show,setShow]=useState(false),[form,setForm]=useState({});const save=async e=>{e.preventDefault();try{await api('cardsSave',{token,sheet:SHEETS[page],record:form},setLoading);setShow(false);setForm({});refresh()}catch(err){alert(err.message)}};return <div><div className="cards-pagehead"><div><span>PERSONAL FINANCE</span><h1>{labels[page]}</h1><p>Manage your {labels[page].toLowerCase()} records.</p></div><div><button onClick={refresh}><RefreshCw size={15}/> Refresh</button><button className="primary" onClick={()=>setShow(true)}><Plus size={15}/> Add</button></div></div>{error&&<div className="cards-alert">{error}</div>}<div className="cards-table-card"><table><thead><tr>{(rows[0]?Object.keys(rows[0]).filter(k=>!['UserID','CreatedAt','UpdatedAt'].includes(k)).slice(0,10):['No records']).map(k=><th key={k}>{k.replace(/([A-Z])/g,' $1')}</th>)}</tr></thead><tbody>{rows.map((r,i)=>{const ks=Object.keys(r).filter(k=>!['UserID','CreatedAt','UpdatedAt'].includes(k)).slice(0,10);return <tr key={i}>{ks.map(k=><td key={k}>{r[k]===undefined||r[k]===''?'—':String(r[k])}</td>)}</tr>})}</tbody></table>{!rows.length&&<div className="cards-empty"><CreditCard size={28}/><b>No records yet</b><span>Add your first record to this module.</span></div>}</div>{show&&<div className="cards-modal"><section><header><b>New {labels[page]}</b><button onClick={()=>setShow(false)}><X/></button></header><form onSubmit={save}>{['Name','Reference','Date','Amount','Limit','Balance','Status','Notes'].map(k=><label key={k}><span>{k}</span><input value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<button className="primary" type="submit">Save Record</button></form></section></div>}</div>}
function Admin({token,setLoading}){const[users,setUsers]=useState([]),[message,setMessage]=useState('');const load=async()=>{try{const x=await api('cardsAdminListUsers',{token},setLoading);setUsers(x.rows||[])}catch(e){setMessage(e.message)}};useEffect(()=>{load()},[]);const update=async(u,status)=>{try{await api('cardsAdminUpdateUser',{token,userId:u.UserID,patch:{Status:status}},setLoading);load()}catch(e){setMessage(e.message)}};return <div><div className="cards-pagehead"><div><span>ADMINISTRATION</span><h1>Cards Access</h1><p>Admin-controlled access for the private workspace.</p></div></div>{message&&<div className="cards-alert">{message}</div>}<div className="cards-table-card"><table><thead><tr><th>Email</th><th>Name</th><th>Role</th><th>Status</th><th>Action</th></tr></thead><tbody>{users.map(u=><tr key={u.UserID}><td>{u.Email}</td><td>{u.Name}</td><td>{u.Role}</td><td>{u.Status}</td><td>{u.Email?.toLowerCase()==='trustedcircle2026@gmail.com'?'Admin':u.Status==='ACTIVE'?<button onClick={()=>update(u,'BLOCKED')}>Block</button>:<button onClick={()=>update(u,'ACTIVE')}>Activate</button>}</td></tr>)}</tbody></table></div></div>}
function Root(){const[session,setSession]=useState(null);useEffect(()=>{const t=localStorage.getItem(CARDS_SESSION_KEY);if(!t)return;api('cardsMe',{token:t},{}) .then(x=>setSession({token:t,user:x.user})).catch(()=>localStorage.removeItem(CARDS_SESSION_KEY))},[]);return session?<App session={session} onLogout={()=>setSession(null)}/>:<Login onLogin={x=>setSession({token:x.session.token,user:x.user})}/>}
ReactDOM.createRoot(document.getElementById('cards-root')).render(<Root/>)
