import { AlertCircle, BarChart3, CheckCircle2, ClipboardList, Clock3, Database, FileWarning, Layers3, ListTodo, TrendingUp } from 'lucide-react'
import './erp-insights.css'

const money=v=>`₹${Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`
const cleanStatus=v=>String(v||'').replaceAll('_',' ')
const statusClass=v=>String(v||'').toLowerCase().replaceAll('_','-')
const labelFor={Users:'Shoppers',Orders:'Orders',Payments:'Payments',PaymentLinkRequests:'Link Requests',Vouchers:'Vouchers',Products:'Products',Brands:'Brands',Cart:'Cart',Notifications:'Notifications',OTP:'OTP Logs',UserSessions:'Sessions',AuditLogs:'Audit Logs',OrderItems:'Order Items',PaymentLinks:'Payment Links'}
const allSheets=['Users','Orders','OrderItems','Payments','PaymentLinks','PaymentLinkRequests','Vouchers','Products','Brands','Cart','Notifications','OTP','UserSessions','AuditLogs']

export function Worklist({items=[],onOpen}){
 return <section className="erp-insights-page"><div className="erp-insights-hero"><div><span className="erp-kicker">PENDING WORK</span><h2>What needs attention</h2><p>Only admin-side items that still need action.</p></div><div className="erp-insight-count"><ListTodo size={18}/><b>{items.length}</b><span>open items</span></div></div><div className="erp-work-grid">{items.length?items.map((item,i)=><article className="erp-work-card" key={`${item.sheet}-${item.recordId||i}`}><div className="erp-work-icon"><AlertCircle size={17}/></div><div className="erp-work-main"><div className="erp-work-top"><span>{item.type||labelFor[item.sheet]||item.sheet}</span><b className={`erp-priority ${String(item.priority||'normal').toLowerCase()}`}>{item.priority||'Normal'}</b></div><h3>{item.title||'Pending item'}</h3><p>{item.detail||cleanStatus(item.status)}</p><small>{item.when||''}</small></div><button className="erp-work-open" onClick={()=>onOpen?.(item.sheet)}>Open <ClipboardList size={13}/></button></article>):<div className="erp-insight-empty"><CheckCircle2 size={28}/><b>All clear</b><span>No pending admin work right now.</span></div>}</div></section>
}

export function Reports({reports={},shopperReport=[]}){
 const pnl=reports.pnl||{}
 const status=reports.status||{}
 return <section className="erp-insights-page"><div className="erp-insights-hero"><div><span className="erp-kicker">BUSINESS REPORTS</span><h2>P&L and shopper view</h2><p>Simple operating numbers from the shopping data.</p></div><div className="erp-report-date">Live data</div></div><div className="erp-report-grid"><ReportCard icon={TrendingUp} label="Gross sales" value={money(pnl.grossSales)} note={`${pnl.paidOrders||0} paid orders`}/><ReportCard icon={BarChart3} label="Discounts" value={money(pnl.discounts)} note="Discount given"/><ReportCard icon={Layers3} label="Collected" value={money(pnl.collected)} note="Verified payments"/><ReportCard icon={FileWarning} label="Refunds" value={money(pnl.refunds)} note={`${pnl.refundedOrders||0} refunded orders`}/></div><div className="erp-report-note"><b>P&L note</b><span>Revenue and collections are shown from recorded sales. True profit needs the actual voucher purchase cost and other expenses; those are not stored in the current ERP data, so no profit figure is invented.</span></div><div className="erp-report-layout"><div className="erp-panel"><div className="erp-panel-head"><div><span>ORDER STATUS</span><h3>Overall view</h3></div></div><div className="erp-status-report">{Object.entries(status).map(([k,v])=><div key={k}><span className={`erp-status ${statusClass(k)}`}>{cleanStatus(k)}</span><b>{v}</b></div>)}</div></div><div className="erp-panel"><div className="erp-panel-head"><div><span>SHOPPERS</span><h3>Shopper-wise summary</h3></div></div><div className="erp-shopper-table"><table><thead><tr><th>Shopper</th><th>Orders</th><th>Paid</th><th>Pending</th><th>Delivered</th><th>Value</th></tr></thead><tbody>{shopperReport.length?shopperReport.map((r,i)=><tr key={r.userId||i}><td><b>{r.name||'Shopper'}</b><small>{r.email||''}</small></td><td>{r.orders}</td><td>{r.paidOrders}</td><td>{r.pendingOrders}</td><td>{r.deliveredOrders}</td><td><b>{money(r.value)}</b></td></tr>):<tr><td colSpan="6">No shopper data yet.</td></tr>}</tbody></table></div></div></div></section>
}
function ReportCard({icon:Icon,label,value,note}){return <div className="erp-report-card"><span><Icon size={18}/></span><small>{label}</small><strong>{value}</strong><em>{note}</em></div>}

export function AllData({tables={},onOpen}){
 const entries=allSheets.map(name=>[name,tables[name]||null])
 return <section className="erp-insights-page"><div className="erp-insights-hero"><div><span className="erp-kicker">DATA CONTROL</span><h2>All data</h2><p>Every ERP sheet is listed here. Open any sheet for the full table.</p></div><div className="erp-insight-count"><Database size={18}/><b>{entries.length}</b><span>ERP sheets</span></div></div><div className="erp-all-data-grid">{entries.map(([name,table])=><button className="erp-data-card" key={name} onClick={()=>onOpen?.(name)}><div className="erp-data-card-icon"><Database size={16}/></div><div><b>{labelFor[name]||name}</b><span>{table?`${table.rows?.length||0} loaded records`:'Open to load records'}</span><small>{table?(table.columns||[]).slice(0,5).join(' · '):'Full sheet data'}</small></div><Clock3 size={14}/></button>)}</div></section>
}
